// Daily briefing — multi-day archive.
// BRIEF_ARCHIVE is keyed by ISO date. BRIEF_DATES is newest-first.
// Past days carry slimmer content than today (the showcase day).

// ── Past days (compact)
function pastDay({ iso, label, shortLabel, market, ai, physical, quantum, econ, columns, invest }) {
  const obj = { date: { iso, label, shortLabel, isToday: false }, marketStrip: market, ai, econ, columns, invest };
  if (physical) obj.physical = physical;
  if (quantum)  obj.quantum  = quantum;
  return obj;
}


// 아카이브: 2026-05-25
const D_0525 = pastDay({
  iso: '2026-05-25', label: '2026년 5월 25일 월요일', shortLabel: '5월 25일 (월)',
  market: [
    { sym: 'KOSPI',   val: '7,848',   pct: '+0.41%', up: true  },
    { sym: 'S&P 500', val: '7,473',   pct: '+0.37%', up: true  },
    { sym: 'NASDAQ',  val: '26,344',  pct: '+0.19%', up: true  },
    { sym: 'BTC',     val: '$76,900', pct: '+1.75%', up: true  },
    { sym: '$/₩',    val: '1,520',   pct: '+0.00%', up: false },
    { sym: '10Y UST', val: '4.56%',  pct: '-4bp',   up: false },
    { sym: 'WTI',     val: '$92.08',  pct: '-4.73%', up: false },
  ],
  ai: {
    label: 'AI 뉴스',
    summary: '교황 레오 14세가 AI 시대 인간 보호를 다룬 첫 교황 회칙 "인류의 위엄(Magnifica Humanitas)"을 발표하며 Anthropic 공동창업자 크리스토퍼 올라와 바티칸에서 함께 공개했습니다. Anthropic은 분기 첫 흑자($5.59억)와 $900억 기업가치를 달성했고, NextEra는 AI 데이터센터 전력을 위해 Dominion Energy를 $670억에 인수하며 AI 인프라 전력 경쟁이 본격화됐습니다.',
    items: [
      { weight: 'high', time: '11:30', source: 'Vatican News / NPR',
        headline: '교황 레오 14세, AI 회칙 "인류의 위엄" 발표 — Anthropic 올라 공동 발표',
        url: 'https://www.vaticannews.va/en/pope/news/2026-05/pope-leo-xiv-first-encyclical-magnifica-humanitas.html',
        bullets: ['교황 레오 14세, 5/25 바티칸 시노드 홀에서 첫 회칙 "Magnifica Humanitas(인류의 위엄)" 공개. AI 시대 인간 존엄 보호가 핵심.', 'Anthropic 공동창업자 겸 해석가능성 연구 수장 크리스토퍼 올라(Christopher Olah)가 공식 발표자로 참석. AI 안전 연구와 종교의 만남.', '회칙 서명일은 교황 레오 13세의 "Rerum novarum" 발표 135주년인 5/15. AI를 산업혁명과 같은 역사적 전환점으로 인식.'],
        why: '교황청이 세계 최고 AI 안전 연구자와 공식 협력해 회칙을 발표한 것은 AI가 단순 기술을 넘어 인류의 가치관·윤리 체계에 근본적 변화를 불러오고 있음을 공인한 사건입니다.',
        notes: [{ term: '교황 회칙(Encyclical)', def: '교황이 전체 가톨릭 교회에 보내는 공식 편지. 교의·윤리·사회 문제에 교황청 입장 표명.' }, { term: 'Rerum novarum', def: '1891년 교황 레오 13세가 발표한 산업혁명 시대 노동자 보호 회칙. 현대 가톨릭 사회 교리의 기초.' }] },
      { weight: 'high', time: '09:00', source: 'CNBC / PYMNTS',
        headline: 'Anthropic, 분기 첫 흑자 $5.59억 · $900억 기업가치 달성 — $300억 펀딩 마감 임박',
        url: 'https://www.cnbc.com/2026/05/20/anthropic-revenue-explosive-growth-ipo-profitable-quarter.html',
        bullets: ['Anthropic, Q2 2026 영업이익 $5.59억 달성 전망. 창사 최초 분기 흑자. Q2 매출 $109억(Q1 $48억 대비 2배 이상 성장).', '$300억 펀딩 라운드 이번 주 마감 예정. 프리머니 기업가치 $900억+ — OpenAI $852억 초과해 AI 스타트업 최고 밸류.', 'ARR $440억, 연간 고객당 $100만+ 지출 기업 1,000개 돌파. Claude API 사용량 전년비 17배.'],
        why: 'AI 모델 기업 최초 분기 흑자는 LLM 비즈니스가 "돈 먹는 하마"에서 수익 사업으로 전환됐음을 의미합니다. Anthropic의 $900억 밸류는 AI 섹터 전체 재평가를 촉발합니다.',
        notes: [{ term: 'ARR(연간 반복매출)', def: '구독·API 기반 기업의 연간 매출 예측치. SaaS 기업 성장성 핵심 지표.' }, { term: '프리머니 기업가치', def: '신규 투자금 유입 전 기업가치. 투자자 신뢰도의 기준점.' }] },
      { weight: 'high', time: '08:00', source: 'Fortune / CNBC',
        headline: 'NextEra, AI 전력 위해 Dominion Energy $670억 인수 — 미국 최대 유틸리티 탄생',
        url: 'https://fortune.com/2026/05/18/nextera-dominion-67-billion-acquisition-ai-data-centers-largest-utility/',
        bullets: ['NextEra Energy, Dominion Energy를 전액 주식 교환 방식 $670억에 인수(5/18 발표). 미국 역대 최대 유틸리티 M&A.', 'Dominion은 세계 최대 데이터센터 집적지 버지니아 북부 전력 공급. Microsoft·Google·Amazon·Meta 하이퍼스케일러 AI 학습 전력 직접 연결.', '합산 재생에너지·배터리 저장·원자력 130GW 건설 수주 잔고. AI 데이터센터 2030년 미국 전력 15~25% 소비 예상에 직접 대응.'],
        why: 'AI 훈련 전력 수요가 사상 최대 유틸리티 합병을 이끌었습니다. 전력망이 AI 경쟁의 새로운 전선이 됐음을 보여주는 역사적 신호입니다.',
        notes: [{ term: '하이퍼스케일러', def: 'Microsoft·Google·Amazon·Meta 등 초대형 데이터센터 운영 빅테크. AI 훈련 전력의 주요 소비자.' }, { term: 'GW(기가와트)', def: '10억 와트. 대형 원자력발전소 1기 출력 약 1GW.' }] },
      { weight: 'low', time: '07:00', source: 'TechTimes / eWeek', headline: '미 의회, Unitree 공급업체 블랙리스트 추진 — G1 로봇 군사 전용 우려', url: 'https://www.techtimes.com/articles/316862/20260519/jal-deploys-unitree-g1-robots-haneda-us-congress-moves-blacklist-supplier-national-security.htm', bullets: ['미 의회 일부, JAL이 하네다에 배치한 Unitree G1 공급업체를 국가안보 우려로 블랙리스트 등록 추진.', 'G1 모터·센서 부품 일부가 군사용 전용 가능하다는 우려. 미중 로봇 기술 갈등 새 전선.'], why: '', notes: [] },
      { weight: 'low', time: '10:00', source: 'Anthropic / KPMG', headline: 'KPMG 27만 명 임직원에 Claude 전면 통합 — AI 컨설팅 최대 제휴', url: 'https://www.anthropic.com/news', bullets: ['KPMG, 전 세계 27.6만 명 임직원에 Claude 통합하는 전략적 제휴 발표(5/19). 감사·세무·컨설팅 AI 자동화 목표.', 'AI 거버넌스 역량 공동 개발. 빅4 회계법인 중 가장 대규모 LLM 파트너십.'], why: '', notes: [] },
      { weight: 'low', time: '08:30', source: 'Google / The Verge', headline: 'Gemini Spark, 수주 내 MCP 지원 — Canva·Instacart·OpenTable 자율 연동', url: 'https://www.cnbc.com/2026/05/19/google-ai-ultra-gemini-spark-omni.html', bullets: ['Google, Gemini Spark(24시간 개인 AI 에이전트)에 수주 내 MCP 프로토콜 지원 추가 예정.', 'Canva·Instacart·OpenTable 등 서드파티 앱 자율 실행. MCP 표준화로 AI 에이전트 생태계 확장.'], why: '', notes: [] },
      { weight: 'low', time: '06:00', source: 'ScienceDaily / Penn', headline: '광자-물질 하이브리드 입자로 AI 연산 — GPU 대비 에너지 100배 절감', url: 'https://www.sciencedaily.com/news/computers_math/artificial_intelligence/', bullets: ['펜실베이니아대, 빛과 물질의 혼성 입자(polariton) 기반 AI 연산 가속 기술 발표.', '에너지 소비 GPU 대비 최대 100배 절감 가능. 광컴퓨팅 AI 칩 상용화 로드맵 앞당겨.'], why: '', notes: [] },
      { weight: 'low', time: '09:00', source: 'OpenAI / TechCrunch', headline: 'GPT-5.5 Instant, ChatGPT 기본 모델 전환 — 할루시네이션 52.5% 감소', url: 'https://techcrunch.com/2026/05/05/openai-releases-gpt-5-5-instant-a-new-default-model-for-chatgpt/', bullets: ['OpenAI GPT-5.5 Instant, ChatGPT 기본 모델로 전환(5/5). 의료·법률·금융 고위험 영역 허위 답변 52.5% 감소.', 'AIME 수학 81.2점(전임 65.4), MMMU-Pro 멀티모달 76점(전임 69.2). 개인화 검색 기능 추가.'], why: '', notes: [] },
    ],
  },
  physical: {
    label: '피지컬 AI 뉴스',
    summary: '일본항공(JAL)이 하네다 공항에 Unitree G1 로봇을 2년간 배치하기로 확정하며 아시아 공항 자동화 시대를 열었고, Unitree는 상하이 STAR 시장 $6.1억 IPO를 추진 중입니다. 한편 미 의회가 Unitree 공급업체 블랙리스트 추진을 검토하며 미중 로봇 기술 갈등이 새로운 전선을 형성하고 있습니다.',
    items: [
      { weight: 'high', time: '09:00', source: 'CNBC / eWeek',
        headline: 'JAL, 하네다 공항에 Unitree G1 로봇 2년 배치 — 아시아 첫 공항 휴머노이드',
        url: 'https://www.cnbc.com/2026/05/01/japan-airlines-humanoid-robots-haneda-labor-shortage.html',
        bullets: ['일본항공(JAL), GMO AI & Robotics와 협력해 하네다 공항에 Unitree G1 로봇 2년 시범 배치 확정.', 'G1(키 130cm, 체중 35kg, 최대 속도 4.4mph) 2대가 수하물 처리·화물 컨테이너 이동·기내 청소 담당.', '일본 항공업계 인력 부족 대응. 로봇 1대 단가 $15,400으로 파일럿→실용화 문턱 낮춰.'],
        why: '항공 지상 조업은 반복적이고 물리적으로 까다로운 작업입니다. JAL의 2년 확정 배치는 아시아 공항 로봇화의 본격 시작을 의미합니다.',
        notes: [{ term: 'Unitree G1', def: '중국 Unitree Robotics의 보급형 휴머노이드. 130cm, 35kg. $15,400으로 글로벌 최저가 수준.' }, { term: '지상 조업', def: '항공기 이착륙 전후 수하물·급유·청소·견인 등 지상 작업 전반.' }] },
      { weight: 'high', time: '08:00', source: 'Bloomberg / Caixin',
        headline: 'Unitree Robotics, 상하이 STAR 시장 IPO — 4.2억 위안($6.1억), 밸류 $70억 목표',
        url: 'https://www.bloomberg.com/news/articles/2026-03-20/chinese-robot-maker-unitree-seeks-610-million-in-shanghai-ipo',
        bullets: ['Unitree, 상하이증권거래소 STAR 시장 IPO 신청 수리(3/20). 조달 목표 4.2억 위안(약 $6.1억).', '2025년 매출 17.1억 위안(+335% YoY), 순이익 6억 위안(+8배). 휴머노이드 매출 비중 51.5%(2023년 1.9%에서 급증).', '자금 용도: 로봇 AI 모델 R&D·신제품 개발·제조 확장. SSE·CSRC 규제 심사 중.'],
        why: 'Unitree IPO는 중국 로봇 산업의 자본시장 본격 진입을 알립니다. 성공 시 글로벌 휴머노이드 기업 밸류에이션 재평가를 이끌 수 있습니다.',
        notes: [{ term: 'STAR 시장(科創板)', def: '상하이증권거래소 첨단기술 특화 시장. 나스닥 모델 기반. 테크 기업 상장 주력 창구.' }, { term: '수익성 IPO', def: '흑자 전환 기업의 공개 상장. Unitree는 흑자를 달성하면서 IPO에 유리한 위치.' }] },
      { weight: 'low', time: '07:00', source: 'The AI Insider / KraneShares', headline: 'Figure AI, 시간당 휴머노이드 1대 생산 — 4개월 만에 24배 속도', url: 'https://theaiinsider.tech/2026/05/01/figure-ai-ramps-up-production-to-one-humanoid-robot-per-hour/', bullets: ['Figure AI Figure 03, BotQ 전용 공장에서 일 1대→시간당 1대로 4개월 만에 24배 생산속도 향상.', '350대 이상 출하. 1차 통과 수율 80%+. 단가 하락으로 기업 도입 임계점 접근.'], why: '', notes: [] },
      { weight: 'low', time: '06:00', source: 'RobotToday / Benzinga', headline: 'Boston Dynamics, IPO 검토 — 최대 $100억 밸류에이션 추정', url: 'https://robottoday.com/article/boston-dynamics-ipo-and-100-b-valuation-how-it-compares-to-tesla-optimus-figure-ai-and-humanoid-rivals', bullets: ['Boston Dynamics, 현대차 산하 IPO 가능성 검토. 전문가 밸류에이션 최대 $100억 추정.', 'Atlas 2026년 생산분 현대차 RMAC·Google DeepMind 납품 확정. 상업화 가속이 IPO 기반.'], why: '', notes: [] },
      { weight: 'low', time: '10:00', source: 'Tesla / Standard Bots', headline: 'Tesla Optimus Gen 3, 2026년 여름 프리몬트 저량 생산 목표 — AI5 칩 통합', url: 'https://standardbots.com/blog/tesla-robot', bullets: ['Tesla Optimus Gen 3, AI5 칩 통합 후 2026년 여름 프리몬트 공장 저량 생산 시작 목표.', '현재 R&D 및 학습 단계. Musk "10만 대/년" 목표 발언 유지.'], why: '', notes: [] },
      { weight: 'low', time: '11:00', source: 'Deloitte Insights', headline: 'Deloitte: "피지컬 AI, 2026 테크 트렌드 5위 내" — 제조·물류·의료 급속 확산', url: 'https://www.deloitte.com/us/en/insights/topics/technology-management/tech-trends/2026/physical-ai-humanoid-robots.html', bullets: ['Deloitte 2026 테크 트렌드 보고서: 피지컬 AI 상위 5위권 진입. 제조·물류·의료 3대 분야 급속 확산.', 'AI 기반 자율 이동·지각·행동 능력이 2026년 실질적 ROI 입증 단계 진입.'], why: '', notes: [] },
      { weight: 'low', time: '08:30', source: 'KraneShares / BCG', headline: 'BCG·KraneShares: "2026년 휴머노이드 파일럿→플랫폼 전환 원년"', url: 'https://kraneshares.com/humanoid-robotics-in-2026-the-race-from-pilot-to-platform/', bullets: ['BCG·KraneShares 공동 보고서: 2026년이 휴머노이드 파일럿→플랫폼 전환 공식 원년.', 'Airbus·BMW·Schaeffler·Siemens 등 글로벌 제조사 동시 파일럿 진행. 구속력 있는 대량 계약 증가.'], why: '', notes: [] },
      { weight: 'low', time: '09:30', source: 'Medium / Avinash Saravanan', headline: '"2026년 휴머노이드 실제 현황" — 파일럿 성공·양산 병목·비용 과제', url: 'https://medium.com/@asarav/humanoid-robots-in-2026-where-the-industry-actually-stands-6ae3dc0c7be5', bullets: ['업계 현황 분석: 파일럿 성공 사례 급증. 그러나 양산 병목·안전 인증·보험 부재가 대규모 확산 장벽.', '재훈련 비용·다양한 물리 환경 일반화가 해결 과제. 2027년이 진짜 임계점 전망.'], why: '', notes: [] },
    ],
  },
  quantum: {
    label: '양자 뉴스',
    summary: '일본 연구팀이 양자 다중 얽힘 "W 상태"를 즉시 감지하는 혁신적 방법을 개발해 양자 통신·텔레포테이션 실용화에 새로운 돌파구를 열었습니다. Google의 Willow 칩 기반 에코 알고리즘이 고전 컴퓨터 대비 13,000배 빠른 양자 우위를 입증했고, IBM Anderon 파운드리 설립이 공식 확정됐습니다.',
    items: [
      { weight: 'high', time: '10:00', source: 'ScienceDaily / Nature',
        headline: '일본 연구팀, 양자 "W 상태" 즉시 감지법 개발 — 양자통신·텔레포테이션 혁신',
        url: 'https://www.sciencedaily.com/releases/2026/05/260513034640.htm',
        bullets: ['일본 연구팀, 양자 다중 얽힘 상태인 "W 상태" 즉시 감지하는 새 방법 발표. 기존 방법보다 획기적으로 빠르고 정확.', 'W 상태는 여러 입자가 얽혀 있어 하나가 측정돼도 나머지 얽힘이 유지되는 특수 상태. 분산 양자 통신에 필수.', '양자 텔레포테이션·초고속 양자 통신·양자 암호 실용화에 직접 응용 가능.'],
        why: 'W 상태의 신뢰할 수 있는 감지는 분산 양자 네트워크 구축의 핵심 난제 중 하나였습니다. 이 돌파구는 양자 인터넷 실현을 앞당기는 기초 기술입니다.',
        notes: [{ term: 'W 상태', def: '여러 양자 입자가 얽혀 있는 다중 얽힘 상태. GHZ 상태와 달리 일부 측정 후에도 나머지 얽힘 보존.' }, { term: '양자 텔레포테이션', def: '얽힘을 이용해 양자 상태 정보를 물리적 이동 없이 전송하는 기술. 양자 통신 네트워크의 핵심.' }] },
      { weight: 'high', time: '09:00', source: 'Google / Programming Helper',
        headline: 'Google Willow, 에코 알고리즘 양자 우위 — 고전 슈퍼컴퓨터 대비 13,000배 빨라',
        url: 'https://www.programming-helper.com/tech/quantum-computing-commercial-breakthrough-2026-ibm-google-achievements',
        bullets: ['Google, Willow 양자칩 기반 "양자 에코(Quantum Echoes)" 알고리즘 발표. 상관관계 측정 연산에서 고전 슈퍼컴퓨터 대비 13,000배 빠른 속도 입증.', '최초 검증 가능한 실용 양자 우위 시연. 오류 수정 없이도 특정 연산에서 클래식 한계 초월.', 'IBM·Microsoft·IonQ 등 경쟁사 양자 우위 입증 레이스 가속.'],
        why: '검증 가능한 양자 우위 시연은 양자컴퓨팅의 "ChatGPT 순간"에 준하는 이정표입니다. 상업 워크로드 적용 가능성에 대한 투자자·기업 관심을 급증시킵니다.',
        notes: [{ term: 'Willow', def: 'Google의 최신 양자 프로세서. 오류 수정 능력·확장성이 이전 세대 대비 비약적 향상.' }, { term: '양자 우위(Quantum Advantage)', def: '특정 문제에서 양자컴퓨터가 고전 슈퍼컴퓨터보다 실질적으로 빠른 상태.' }] },
      { weight: 'low', time: '11:00', source: 'CNN Business / IBM', headline: 'IBM Anderon 양자 웨이퍼 파운드리 확정 — 정부 $10억 + 자체 $10억', url: 'https://www.cnn.com/2026/05/21/business/ibm-quantum-computing-firms-grants', bullets: ['IBM, 미 상무부 $10억 + 자체 $10억으로 뉴욕 올버니에 양자 웨이퍼 전용 파운드리 Anderon 설립 확정.', 'Heron R2 156큐비트 프로세서 현재 운영 중. 2026년 양자 우위 시연 목표.'], why: '', notes: [] },
      { weight: 'low', time: '07:00', source: 'McKinsey / Motley Fool', headline: 'McKinsey 2035년 양자시장 $720억 전망 — 정부 투자가 민간 후속 촉진', url: 'https://www.fool.com/investing/2026/05/22/why-does-quantum-computing-stock-keep-going-up/', bullets: ['McKinsey, 2035년 양자컴퓨팅 글로벌 시장 $720억 전망. 2026년 정부투자 $20억이 민간 투자 촉진 역할.', 'QTUM ETF 2026년 +40%+. D-Wave·Rigetti·IonQ 정부 투자 후 30%+ 급등.'], why: '', notes: [] },
      { weight: 'low', time: '06:00', source: 'Microsoft / Atom Computing', headline: 'Microsoft·Atom, 2026년 오류 수정 양자컴퓨터 상용 출시 — 덴마크 첫 납품', url: 'https://quantumcomputingreport.com/news/', bullets: ['Microsoft·Atom Computing, 덴마크 Novo Nordisk재단에 오류 수정 양자컴퓨터 납품 확정.', '2026년 레벨2 양자컴퓨터 최초 상업 출하 예정. Azure Quantum 통합.'], why: '', notes: [] },
      { weight: 'low', time: '08:00', source: 'Harvard / The Quantum Insider', headline: '하버드: 양자 오류 수정 18개월 앞서 — 2028년 실용 우위 가능', url: 'https://thequantuminsider.com/2026/05/04/harvard-researchers-quantum-computing-advancing-faster-than-expected/', bullets: ['하버드 연구팀, 양자 오류 수정 속도가 업계 예측보다 18개월 앞서 진행.', '현재 궤도 유지 시 2028년 특정 산업 문제 실용 우위 달성 가능.'], why: '', notes: [] },
      { weight: 'low', time: '10:30', source: '36Kr', headline: '"2026년 QPU가 GPU 대체하는 첫 해" — 에너지·속도 기준 양자 우위 확장', url: 'https://eu.36kr.com/en/p/3624758715462150', bullets: ['중국 테크 미디어 36Kr: 2026년이 특정 AI 워크로드에서 QPU가 GPU를 대체하는 원년.', '에너지 효율·연산 속도 기준 양자 우위 영역 확대. 데이터센터 비용 절감 핵심 솔루션 부상.'], why: '', notes: [] },
      { weight: 'low', time: '09:30', source: 'Quantum Computing Inc. / PR Newswire', headline: 'Quantum Computing Inc., Q1 2026 실적 발표 — 포토닉 양자 솔루션 상용화 진전', url: 'https://www.prnewswire.com/news-releases/quantum-computing-inc-reports-first-quarter-2026-financial-results-302768603.html', bullets: ['Quantum Computing Inc.(QCI), Q1 2026 실적 발표. 포토닉(광자 기반) 양자 솔루션 상용화 진전.', '실리콘 포토닉스 통합 QML 서비스 출하. 정부·방산 계약 파이프라인 확대.'], why: '', notes: [] },
    ],
  },
  econ: {
    label: '경제 뉴스',
    summary: '미·이란 핵협상 타결 기대감으로 WTI가 $92.08로 급락(-4.73%)하며 에너지 인플레이션 완화 기대가 부상했습니다. 한국은 부처님오신날 대체공휴일, 미국은 메모리얼 데이로 양국 금융시장이 동시 휴장한 가운데, 트럼프 대통령이 미·이란 협상이 "대부분 완료됐다"고 언급해 유가 하락을 주도했습니다.',
    items: [
      { weight: 'high', time: '07:00', source: 'Newspim / CNBC',
        headline: 'WTI $92.08 급락(-4.73%) — 미·이란 핵협상 타결 기대, 2주 만에 최저',
        url: 'https://www.newspim.com/news/view/20260525000018',
        bullets: ['WTI, 미·이란 7차 핵협상 진전 기대로 배럴당 $92.08(-4.73%) 급락. 5월 7일 이후 최저치.', '트럼프 대통령 "협상 대부분 완료됐다(largely negotiated)" 발언이 유가 하락 직접 촉발. 이란 석유 수출 재개 시 글로벌 공급 증가 기대.', '단, 이란 농축 우라늄 보유량·호르무즈 통행료 문제는 미합의. 협상 완전 타결까지 변동성 지속.'],
        why: 'WTI $92 하락은 에너지 인플레 완화→연준 금리 동결 유지→채권 반등 체인을 가동합니다. 이란합의 공식화 시 WTI $80대 진입 가능성이 있어 글로벌 금리 경로에 핵심 변수입니다.',
        notes: [{ term: '이란 핵협상', def: '미국과 이란 간 이란 핵 프로그램 제한·경제 제재 해제 협상. 타결 시 이란 원유 수출 재개로 글로벌 공급 증가.' }, { term: '호르무즈 해협', def: '이란-오만 사이 좁은 해협. 전 세계 원유 유통량의 약 20% 통과. 핵협상 핵심 쟁점.' }] },
      { weight: 'high', time: '09:00', source: '위키트리 / 연합뉴스',
        headline: '한국 부처님오신날 대체·미국 메모리얼 데이 — 양국 증시 동시 휴장',
        url: 'https://www.wikitree.co.kr/articles/1138079',
        bullets: ['5/25(월), 한국은 부처님오신날 대체공휴일·미국은 메모리얼 데이로 양국 증시 동시 휴장.', '주간 거래 단축(4일). 전주 S&P 500 7,473(+0.37%), KOSPI 7,848(+0.41%)이 마지막 종가.', '공휴일 기간 이란 협상·유가 급락 뉴스가 쌓여 화요일 개장 시 변동성 확대 가능성.'],
        why: '양국 동시 휴장은 이란 협상 진전·WTI 급락 같은 주요 뉴스가 시장에 미반영되어, 화요일(5/26) 개장 첫 30분이 방향성을 결정하는 중요 국면이 됩니다.',
        notes: [{ term: '부처님오신날 대체공휴일', def: '석가탄신일(음력 4/8)이 일요일과 겹칠 때 다음 평일을 공휴일로 지정하는 제도.' }] },
      { weight: 'low', time: '08:00', source: 'Reuters / Schwab', headline: '연준 금리 3.5~3.75% 동결 — 워시 6/17 FOMC, WTI 급락에 인상 압박 완화', url: 'https://www.schwab.com/learn/story/stock-market-update-open', bullets: ['연준 금리선물 시장, WTI $92 급락 후 6/17 FOMC 금리 인상 확률 14.9%로 하락. 동결 74.5%.', 'WTI 하락→에너지 인플레 완화→워시 의장 매파적 스탠스 약화 기대.'], why: '', notes: [] },
      { weight: 'low', time: '06:00', source: 'UN / 오늘의클릭', headline: 'UN, 세계 경제 성장률 2.5%로 하향 — 중동 에너지 위기·고금리 복합 압박', url: 'https://www.cliktoday.com/2026/05/20260523-today-news.html', bullets: ['UN, 2026년 세계 경제 성장률 2.7%→2.5% 하향. 중동 분쟁 장기화·유가 상승 반영.', '이란합의 타결 시 시나리오 상향 가능성. 최악의 경우 2.1% 추락 경고.'], why: '', notes: [] },
      { weight: 'low', time: '07:30', source: 'Yahoo Finance / Tax Foundation', headline: 'IEEPA 관세 환급 포털 개설 — 7월 Section 301 재부과 예고', url: 'https://finance.yahoo.com/economy/policy/live/trump-tariffs-live-updates-us-opens-tariff-refund-portal-with-checks-expected-this-summer-223100182.html', bullets: ['법원 IEEPA 관세 위헌 판결 후 미국 정부 환급 포털 개설. 환급 수표 여름 예정.', '정부, 7월부터 무역법 301조 기반 관세 재부과 예고. 한국 수출 하반기 불확실성 잔존.'], why: '', notes: [] },
      { weight: 'low', time: '10:00', source: 'Anthropic / PYMNTS', headline: 'Anthropic $300억 펀딩 이번 주 마감 — $900억 밸류 AI 섹터 역대 최대', url: 'https://www.pymnts.com/artificial-intelligence-2/2026/anthropic-eyes-900-billion-valuation-as-quarterly-revenue-doubles/', bullets: ['Anthropic $300억 펀딩 라운드 이번 주(5/26 주간) 마감 예정. 프리머니 $900억+ 확정 시 AI 역대 최대.', 'OpenAI $852억 밸류 초과. AI 스타트업 자금 조달 기록 연속 경신.'], why: '', notes: [] },
      { weight: 'low', time: '09:00', source: 'TradingEconomics', headline: '미국 10Y 국채 4.56% — WTI 급락에 인플레 우려 완화, 채권 안정화', url: 'https://tradingeconomics.com/united-states/government-bond-yield', bullets: ['미국 10년 국채 4.56%. WTI $92 급락으로 에너지 인플레 우려 완화. 채권 매도세 진정.', '6/17 FOMC 금리 동결 기대 강화 시 TLT 추가 반등 기대.'], why: '', notes: [] },
      { weight: 'low', time: '11:00', source: 'Deloitte / Wirepoints', headline: '메모리얼 데이 연휴 주간 — 미국 시장 화요일(5/26) 개장, 이란발 변동성 주목', url: 'https://wirepoints.org/memorial-day-2026/', bullets: ['메모리얼 데이 연휴로 미국 증시 5/25 휴장. 화요일 5/26 개장 시 이란협상·WTI 급락 뉴스 한꺼번에 반영.', '개장 초 채권(TLT)·에너지·방산주 변동성 집중 예상.'], why: '', notes: [] },
    ],
  },
  columns: {
    label: '컬럼 피드',
    summary: '오건영 단장은 채권 금리 급등의 역사적 선례들(22년 10월 트러스 쇼크·23년 10월·25년 4월 셀아메리카)을 시간 역순으로 분석하는 시리즈를 이어가고 있습니다. 이번 글에서는 2025년 4월 셀아메리카 국면이 어떻게 해결됐는지를 중점적으로 탐색합니다.',
    items: [
      { name: '오건영', title: '신한은행 · 디지털 크리에이터', avatar: 'OG', color: '#D97757',
        time: '5월 21일 01:00', likes: 529, comments: 15,
        post: '오늘 새벽 소폭 안정세를 보이기는 했지만 여전히 채권 금리에 대한 우려가 계속해서 확대 일로에 있는 듯 합니다. 이렇게 금리가 높았던 시기가 언제 있었을까요.. 물론 20년과 30년물 기준으로는 지금이 더 높았지만... 지난 러-우 전쟁과 연준의 자이언트 스텝 금리 인상, 그리고 영국 트러스 모멘텀이 극에 달했던 22년 10월이 있었죠. 그리고 예상했던 것보다 더 빠르게 금리를 인상하는데 대해 당혹스러운 모습을 보였던 2023년 10월도 그랬습니다. 그리고 트럼프 당선을 전후해서 트럼프 트레이드가 나타났고... 그러다 185개국에 관세를 부과한 이후 셀 아메리카가 터져나오면서 국채 금리가 재차 급등했던 기억이 있죠. 그럼.. 당시에는 어떻게 이런 상황들을 해결해나갔을까요.. 우선 시간의 역순으로 가봅니다. 2025년 4월, 셀 아메리카 때로 가보죠.',
        summary: '채권 금리 급등 역사 역추적 시리즈 — 22년 10월·23년 10월·25년 4월 셀아메리카 선례를 분석해 현재 위기 해결 실마리 탐색.',
      },
    ],
  },
  invest: {
    title: 'WTI $92 급락·이란합의 기대',
    subtitle: 'Claude가 작성한 오늘의 메모 · 5월 25일 09:00 · 5분 읽기',
    sections: [
      { h: '한 줄 요약', body: 'WTI가 미·이란 협상 기대에 $92로 급락(-4.73%)하며 에너지 인플레이션 완화 신호를 보냈습니다. Anthropic이 분기 첫 흑자($5.59억)와 $900억 기업가치를 달성했고, 교황 레오 14세의 AI 회칙이 Anthropic 공동창업자와 함께 공개되며 AI가 인류 문명의 최전선 의제가 됐습니다.' },
      { h: '오늘의 변수', body: '①WTI $92 급락 → 에너지 인플레 완화 → 6/17 FOMC 금리 인상 압박 ↓ → TLT 반등 기회. ②미·이란 협상 타결 가능성 → 이란 원유 재개 → WTI $80대 시나리오. ③Anthropic $900억 펀딩 마감(이번 주) → AI 섹터 밸류에이션 재평가. ④NextEra-Dominion $670억 합병 → AI 전력 인프라 투자 테마 본격화. ⑤화요일(5/26) 시장 개장 시 이란·유가 뉴스 한꺼번에 반영 — 변동성 집중 예상.' },
      { h: '포지셔닝', body: '단기(1-3개월): WTI 급락으로 TLT 비중 상향(채권 반등 기대). 에너지 비중 축소. AI 인프라 NVDA·MSFT 유지. 화요일 개장 초 채권·에너지주 변동성 집중 주시. 중기(6-12개월): 이란합의 완료 시 WTI $80대 → 글로벌 인플레 완화 → 성장주 재평가. Anthropic IPO·OpenAI IPO(9월) 전후 AI 섹터 최대 이벤트. 한국 반도체 수출 모멘텀(202%) 지속 시 SK하이닉스 목표주가 상향.' },
      { h: '리스크', body: '이란 협상 결렬 → WTI $105+ 재반등 → 에너지 인플레 재점화 → 연준 금리 인상. 워시 6/17 FOMC 예상 밖 금리 인상 선언 → 채권·성장주 동반 급락. Anthropic $900억 밸류 버블 논란 → AI 섹터 조정. NextEra-Dominion 합병 규제 불승인 → 유틸리티·AI 인프라 섹터 충격.' },
    ],
    watchlist: [
      { sym: '000660', name: 'SK하이닉스',  val: '1,940,000', pct: '+11.17%', up: true,  note: '반도체 수출 202% 모멘텀 — 한국 공휴일, 화요일 반응 주목' },
      { sym: '005930', name: '삼성전자',    val: '299,500',   pct: '+3.64%', up: true,  note: '노사 합의·HBM4 생산 정상화 — 화요일 추가 상승 기대' },
      { sym: 'NVDA',   name: 'NVIDIA',      val: '$246.20',   pct: '+0.29%', up: true,  note: 'NextEra-Dominion AI 전력 합병 — AI 인프라 투자 장기 수혜' },
      { sym: 'MSFT',   name: 'Microsoft',   val: '$480.50',   pct: '+0.52%', up: true,  note: 'OpenAI IPO 9월 목표·Anthropic $900억 — AI 섹터 밸류 상승' },
      { sym: 'TLT',    name: 'iShares 20Y', val: '$87.50',    pct: '+1.51%', up: true,  note: 'WTI $92 급락 → 에너지 인플레 완화 → 채권 반등 기대' },
      { sym: 'GLD',    name: 'SPDR Gold',   val: '$256.00',   pct: '+1.38%', up: true,  note: '이란 협상 완전 타결 전 지정학 헤지 유지 — 비중 유지' },
      { sym: 'VYM',    name: 'Vanguard HY', val: '$131.40',   pct: '-0.30%', up: false, note: '고금리 환경 소폭 하락 — WTI 급락 시 배당주 환경 개선 기대' },
      { sym: 'BTC',    name: 'Bitcoin',     val: '$76,900',   pct: '+1.75%', up: true,  note: '달러 약세 기대·리스크온 — 이란합의 기대에 소폭 반등' },
    ],
    portfolio: [
      { asset: '국내주식', pct: 18, color: '#3DDC97',
        tickers: [{ sym: '000660', name: 'SK하이닉스' }, { sym: '005930', name: '삼성전자' }],
        note: '반도체 수출 202% 모멘텀 유지 — 화요일 이란발 변동성 주시' },
      { asset: '미국주식', pct: 18, color: '#5B9BD5',
        tickers: [{ sym: 'NVDA', name: 'NVIDIA' }, { sym: 'MSFT', name: 'Microsoft' }],
        note: 'AI 전력 인프라 NVDA + OpenAI IPO 수혜 MSFT' },
      { asset: '채권', pct: 14, color: '#9B8EC4',
        tickers: [{ sym: 'TLT', name: 'iShares 20Y ETF' }],
        note: 'WTI 급락 → 인플레 완화 → TLT 비중 상향' },
      { asset: '금', pct: 23, color: '#F5C518',
        tickers: [{ sym: 'GLD', name: 'SPDR Gold ETF' }],
        note: '이란 협상 완전 타결 전까지 지정학 헤지 유지' },
      { asset: '배당주', pct: 18, color: '#E08A6E',
        tickers: [{ sym: 'VYM', name: 'Vanguard High Div.' }],
        note: '고금리 환경 방어 — WTI 하락 시 환경 개선' },
      { asset: '비트코인', pct: 9, color: '#F7931A',
        tickers: [{ sym: 'BTC', name: 'Bitcoin' }],
        note: '달러 약세 기대·이란합의 리스크온 — 소폭 반등' },
    ],
  },
});


// 아카이브: 2026-05-24
const D_0524 = pastDay({
  iso: '2026-05-24', label: '2026년 5월 24일 일요일', shortLabel: '5월 24일 (일)',
  market: [
    { sym: 'KOSPI',   val: '7,848',   pct: '+0.41%', up: true  },
    { sym: 'S&P 500', val: '7,473',   pct: '+0.37%', up: true  },
    { sym: 'NASDAQ',  val: '26,344',  pct: '+0.19%', up: true  },
    { sym: 'BTC',     val: '$75,580', pct: '-1.45%', up: false },
    { sym: '$/₩',    val: '1,520',   pct: '+0.66%', up: true  },
    { sym: '10Y UST', val: '4.56%',  pct: '-4bp',   up: false },
    { sym: 'WTI',     val: '$104',    pct: '+5.18%', up: true  },
  ],
  ai: {
    label: 'AI 뉴스',
    summary: 'Anthropic 공동창업자 Jack Clark가 옥스퍼드에서 2028년 AI의 재귀적 자기개선 확률을 60%+로 공식 예측했고, OpenAI는 80년 된 수학 난제를 자율 증명하며 AI 수학 역사를 새로 썼습니다. 메타는 직원 작업 패턴을 AI 학습에 활용한 뒤 8,000명을 해고한 사실이 폭로돼 윤리 논란이 커지고 있습니다.',
    items: [
      { weight: 'high', time: '20:00', source: 'Time / Axios',
        headline: 'Jack Clark(Anthropic), 옥스퍼드 강연 — 2028년 AI 재귀적 자기개선 60%+ 확률',
        url: 'https://time.com/article/2026/05/22/anthropic-claude-code-jack-clark-ai-safety/',
        bullets: ['Anthropic 공동창업자 Jack Clark, 옥스퍼드 2026 코스모스 강연. "2028년 말 AI가 스스로 더 나은 AI를 훈련할 확률 60%+" 공식 예측.', '12개월 내 AI 노벨상급 발견, 18개월 내 AI 단독 운영 기업 수백만 달러 매출 전망.', 'Anthropic 내부 문서에 "지능 폭발(intelligence explosion)" 첫 공식 등장. "AI가 모든 인류를 죽일 확률 0이 아님"도 인정.'],
        why: 'AI 개발사 공동창업자가 재귀적 자기개선을 30개월 내 현실로 명시 예측한 것은 전례 없는 일입니다. 산업계 전체의 리스크 인식과 규제 논의에 즉각적 영향을 줍니다.',
        notes: [{ term: '재귀적 자기개선', def: 'AI 시스템이 스스로 더 뛰어난 후속 AI를 설계·훈련하는 과정. 이론적으로 기술 가속을 기하급수적으로 높임.' }, { term: '지능 폭발', def: 'AI 능력이 통제 불가능한 속도로 증가하는 시나리오. AI 안전 연구의 핵심 개념.' }] },
      { weight: 'high', time: '14:00', source: 'OpenAI / Build Fast with AI',
        headline: 'OpenAI, 에르되시 80년 기하학 난제 자율 증명 — AI 수학 역사 이정표',
        url: 'https://openai.com/index/model-disproves-discrete-geometry-conjecture/',
        bullets: ['OpenAI 내부 범용 추론 모델, 1946년 폴 에르되시가 제기한 단위거리 문제 125쪽 증명 자율 완성. 80년간 미해결 난제.', '대수적 정수론의 골로드-샤파레비치 기준을 기하학 문제에 연결하는 전례 없는 접근법. 필즈 메달리스트 팀 가워스 "AI 수학의 이정표".', '모델은 이 문제에 특화 훈련 없이 문제 서술만 받고 독립 증명. 인간의 지도 없이 새로운 수학 지식 창출 첫 사례.'],
        why: 'AI가 전문가도 수십 년간 풀지 못한 수학 난제를 처음으로 독립 해결했습니다. 이는 과학·공학 분야 연구 가속화의 임계점이 가까워졌음을 시사합니다.',
        notes: [{ term: '에르되시 단위거리 문제', def: '평면 위 n개의 점 배치에서 단위 거리 쌍의 최대 수를 묻는 이산기하학 문제. 1946년 제기, 80년간 미해결.' }, { term: '골로드-샤파레비치 기준', def: '무한 유한군의 존재를 보장하는 대수적 정수론 정리. 기하학에 응용된 것은 이번이 처음.' }] },
      { weight: 'high', time: '19:00', source: 'More Perfect Union / TechStory',
        headline: '메타 저커버그, 직원 이메일·코딩 패턴 AI 학습 후 8,000명 해고 — 내부 폭로',
        url: 'https://techstory.in/leaked-audio-reveals-mark-zuckerberg-defending-internal-employee-tracking-to-feed-metas-ai/',
        bullets: ['메타 4월 30일 전사 회의 유출 음성: 저커버그, "직원 Gmail·코딩·Metamate 활동 추적해 AI 모델 학습" 인정. 같은 날 8,000명 해고 통보.', '직원들, 해고 통지 받으면서 내부 폭로 확산. "자신들을 훈련시킨 AI에 의해 대체됐다" 항의 시위.', '메타 2026년 AI 인프라 $1,250억 집행 확정. 연간 역대급 비용으로 AI 전략 가속.'],
        why: '직원 동의 없이 작업 패턴을 AI 학습에 활용하고 해당 직원을 해고한 것은 AI 윤리·노동 정책의 핵심 사례가 됩니다. AI 거버넌스 논의를 가속합니다.',
        notes: [{ term: 'MCI(Model Capability Initiative)', def: '메타 내부 AI 학습 프로그램. 직원 Gmail·VS Code·Metamate 활동을 AI 훈련 데이터로 수집.' }, { term: 'Metamate', def: '메타 내부 업무용 AI 어시스턴트.' }] },
      { weight: 'low', time: '21:00', source: 'Axios', headline: '트럼프, AI 행정명령 폐기 — 머스크·저커버그·색스 직통 전화 후 철회', url: 'https://www.axios.com/2026/05/21/trump-ai-executive-order-postponed-why', bullets: ['트럼프 AI 안전 EO, 서명 시간 직전 철회. 머스크·저커버그·데이비드 색스가 대통령에 직접 전화해 "AI 개발 저해" 경고.', '90일 사전 검토 프레임워크 무산. 국가안보 관료 수개월 작업 무력화.'], why: '', notes: [] },
      { weight: 'low', time: '08:00', source: 'The Hacker News', headline: 'GitHub 내부 레포 3,800개 탈취 — Nx Console VS Code 확장 18분 공급망 공격', url: 'https://thehackernews.com/2026/05/github-internal-repositories-breached.html', bullets: ['악성 Nx Console VS Code 확장 18분간 배포. GitHub 내부 레포 3,800개·OpenAI·Mistral AI 피해.', 'Claude Code ~/.claude/settings.json 표적. 공급망 공격 위험성 재조명.'], why: '', notes: [] },
      { weight: 'low', time: '10:00', source: 'eWeek / 9to5Google', headline: 'Gemini, Adobe·Canva·CapCut 통합 — AI 창작 스튜디오로 전환', url: 'https://www.eweek.com/news/google-gemini-adobe-canva-capcut-integrations/', bullets: ['Google Gemini, Adobe Firefly·Canva Magic Layers·CapCut 직접 통합. AI 생성 콘텐츠를 전문 편집 도구로 즉시 전달.', 'Ultra 구독자 베타 배포 중.'], why: '', notes: [] },
      { weight: 'low', time: '18:00', source: 'Anthropic', headline: 'Anthropic, Stainless 인수 — Claude API SDK 개발자 경험 강화', url: 'https://www.anthropic.com/news/anthropic-acquires-stainless', bullets: ['Anthropic, OpenAI·Cloudflare SDK 제작사 Stainless 인수. Claude Python·TypeScript·Java·Go SDK 품질 향상 목표.', '개발자 경험을 전략적 경쟁력으로.'], why: '', notes: [] },
      { weight: 'low', time: '09:00', source: 'Intuit / CNBC', headline: 'Intuit, AI 전환 가속 — 직원 3,000명 해고 후 AI 에이전트에 예산 집중', url: 'https://llm-stats.com/ai-news', bullets: ['Intuit, 전체 인력 8% 해고. AI 에이전트·QuickBooks 자동화에 예산 재투자. 연간 $5억+ 비용 절감 목표.', 'AI 전환 빅테크 대규모 인력 재편 흐름 가속.'], why: '', notes: [] },
    ],
  },
  physical: {
    label: '피지컬 AI 뉴스',
    summary: 'Figure AI가 4개월 만에 생산속도를 시간당 1대로 끌어올리며 휴머노이드 양산 시대를 본격화했고, Japan Airlines가 하네다 공항에 Unitree 로봇을 3년 운영 확정하며 아시아 물류·서비스 로봇 시장이 열렸습니다. SoftBank의 ABB 로보틱스 $54억 인수로 피지컬 AI 시장 대형화 M&A도 가속 중입니다.',
    items: [
      { weight: 'high', time: '09:00', source: 'The AI Insider / KraneShares',
        headline: 'Figure AI, 시간당 휴머노이드 1대 생산 — 4개월 만에 24배 속도 향상',
        url: 'https://theaiinsider.tech/2026/05/01/figure-ai-ramps-up-production-to-one-humanoid-robot-per-hour/',
        bullets: ['Figure AI, Figure 03 생산속도를 일 1대에서 시간당 1대로. 4개월 만에 24배 가속.', '전용 BotQ 제조 시설 150개 이상 스테이션, 1차 통과 수율 80%+.', '350대 이상 출하 완료. 납품 단가 하락으로 기업 도입 임계점 접근 중.'],
        why: '시간당 1대 생산은 휴머노이드가 실험실 단계를 벗어나 산업 공급망으로 진입하는 변곡점입니다.',
        notes: [{ term: 'BotQ', def: 'Figure AI의 전용 휴머노이드 제조 시설. 자동화 생산 라인.' }, { term: '1차 통과 수율', def: '재작업 없이 첫 시도에 합격하는 제품 비율.' }] },
      { weight: 'high', time: '10:00', source: 'NVIDIA Newsroom',
        headline: 'NVIDIA, 글로벌 로봇 파트너들과 피지컬 AI 현장 배포 확대 — 신규 모델 공개',
        url: 'https://nvidianews.nvidia.com/news/nvidia-releases-new-physical-ai-models-as-global-partners-unveil-next-generation-robots',
        bullets: ['NVIDIA, 신규 피지컬 AI 모델 및 글로벌 파트너 차세대 로봇 공개. Boston Dynamics·Figure·1X·Unitree 즉시 적용.', 'Isaac 플랫폼·디지털 트윈으로 sim-to-real 갭 해소. Qualcomm Dragonwing IQ10 협력 발표.', '제조·물류·의료 현장 배포 가속.'],
        why: 'NVIDIA의 피지컬 AI 생태계 확장은 로봇 AI 훈련 비용을 낮추고 현장 배포 속도를 높여 산업 전체 성장을 가속합니다.',
        notes: [{ term: 'Isaac 플랫폼', def: 'NVIDIA의 로봇 시뮬레이션·훈련·배포 통합 플랫폼.' }, { term: 'sim-to-real', def: '시뮬레이션에서 학습한 AI를 실제 물리 환경에 적용하는 기술.' }] },
      { weight: 'low', time: '08:00', source: 'KraneShares / Seeking Alpha', headline: '휴머노이드 로보틱스 2026 — 파일럿→플랫폼 전환 본격화', url: 'https://kraneshares.com/humanoid-robotics-in-2026-the-race-from-pilot-to-platform/', bullets: ['BVP "2026년 로보틱스의 GPT-2.5 모멘트". Airbus·BMW·Schaeffler 등 파일럿 동시 진행.', 'Unitree 2025년 5,500대 출하로 미국 3사 합산 추월.'], why: '', notes: [] },
      { weight: 'low', time: '11:00', source: 'SoftBank / Reuters', headline: 'SoftBank, ABB 로보틱스 부문 $54억 인수 — "피지컬 AI 다음 개척지"', url: 'https://artificialintelligence-news.com/news/physical-ai-humanoid-robots-factories/', bullets: ['SoftBank, ABB 산업 로봇 부문 $54억 인수. 피지컬 AI "다음 개척지" 선언.', 'ARM·비전펀드 포트폴리오와 시너지. 산업 로봇·AI 융합 가속.'], why: '', notes: [] },
      { weight: 'low', time: '07:00', source: 'Physical Intelligence', headline: 'pi-0.7, 한 번도 훈련 안 한 가전제품 조작 — 에어프라이어 2회 관찰 후 작동', url: 'https://nvidianews.nvidia.com/news/nvidia-and-global-robotics-leaders-take-physical-ai-to-the-real-world', bullets: ['Physical Intelligence의 pi-0.7, 훈련 데이터 없는 에어프라이어를 2회 관찰만으로 자율 조작 성공.', '로봇 AI 일반화 능력 획기적 향상 — 매 기기마다 재훈련 불필요 시대 가능성.'], why: '', notes: [] },
      { weight: 'low', time: '09:30', source: 'Automate 2026', headline: 'Automate 2026 — Boston Dynamics·Figure·1X·Agility 총집결, 이틀 포럼', url: 'https://www.automate.org/blogs/what-hurdles-remain-for-widespread-humanoid-adoption', bullets: ['Automate 2026 전시회, 이틀간 휴머노이드 로봇 포럼. 주요 기업 최신 기술 공개.', '피지컬 AI·디지털 트윈·시뮬레이션 2026 최신 트렌드 총람.'], why: '', notes: [] },
      { weight: 'low', time: '06:00', source: 'RobotToday', headline: 'Boston Dynamics, IPO 검토 — 밸류에이션 최대 $100억 추정', url: 'https://robottoday.com/article/boston-dynamics-ipo-and-100-b-valuation-how-it-compares-to-tesla-optimus-figure-ai-and-humanoid-rivals', bullets: ['Boston Dynamics, 현대차 산하 IPO 가능성 검토 중. Atlas 상업 배포 확대 기반.', '전문가 추정 밸류에이션 최대 $100억.'], why: '', notes: [] },
      { weight: 'low', time: '08:30', source: 'Tesla / Built In', headline: 'Tesla Optimus Gen 3, 2026년 여름 프리몬트 저량 생산 목표', url: 'https://standardbots.com/blog/tesla-robot', bullets: ['Tesla Optimus Gen 3, AI5 칩 통합 후 프리몬트 공장 2026년 여름 저량 생산 시작 목표.', '현재 R&D·학습 단계. 실제 공장 배치 로드맵 구체화.'], why: '', notes: [] },
    ],
  },
  quantum: {
    label: '양자 뉴스',
    summary: '모틀리 풀이 양자컴퓨팅을 2026년 가장 저평가된 기술 트렌드로 지목했고, 미국 정부의 $20억 투자 후속으로 IBM이 Anderon 파운드리 설립을 확정했습니다. 중성 원자 방식 양자컴퓨팅의 99.9% 게이트 충실도 달성으로 확장성 경쟁이 이온트랩 방식과 치열해지고 있습니다.',
    items: [
      { weight: 'high', time: '08:00', source: 'The Motley Fool',
        headline: '모틀리 풀: "양자컴퓨팅 — 2026 가장 저평가된 기술 트렌드"',
        url: 'https://www.fool.com/investing/2026/05/23/prediction-quantum-computing-is-2026s-most-underra/',
        bullets: ['모틀리 풀, 5월 23일 보고서: 양자컴퓨팅이 AI에 가려 저평가. 2026년이 투자 변곡점.', 'IBM·D-Wave·IonQ 정부 투자 수혜 + 민간 후속 투자 유입. 섹터 ETF(QTUM) 2026년 +40%+.', 'QPU가 특정 산업 워크로드에서 GPU를 대체하는 첫 상업 사례 가시화.'],
        why: '주류 투자 미디어가 양자컴퓨팅을 2026 핵심 테마로 지목한 것은 기관 투자자 유입을 자극하는 내러티브 전환점입니다.',
        notes: [{ term: 'QPU(양자처리장치)', def: '양자컴퓨팅의 핵심 처리 칩.' }, { term: 'QTUM', def: '글로벌 X 양자컴퓨팅 ETF.' }] },
      { weight: 'high', time: '10:00', source: 'CNN Business / IBM',
        headline: 'IBM, Anderon 양자 웨이퍼 파운드리 설립 확정 — 정부 $10억 + 자체 $10억',
        url: 'https://www.cnn.com/2026/05/21/business/ibm-quantum-computing-firms-grants',
        bullets: ['IBM, 미 상무부 $10억 + 자체 $10억으로 뉴욕 올버니에 양자 웨이퍼 전용 파운드리 Anderon 설립 확정.', 'Heron R2 156큐비트 프로세서 현재 운영 중. 2026년 양자 우위 시연 목표.', 'NYU-IBM 공동 박사후연구원 프로그램 창설. 인재 생태계 구축 가속.'],
        why: 'IBM이 양자 전용 파운드리를 확보하면 큐비트 생산 비용이 낮아지고 상업화 타임라인이 단축됩니다.',
        notes: [{ term: 'Anderon', def: 'IBM이 설립하는 양자 웨이퍼 전용 파운드리.' }, { term: 'Heron R2', def: 'IBM 156큐비트 양자 프로세서.' }] },
      { weight: 'low', time: '07:00', source: 'IEEE Spectrum', headline: '중성 원자 양자컴퓨팅 2026 대약진 — 게이트 충실도 99.9%', url: 'https://spectrum.ieee.org/neutral-atom-quantum-computing', bullets: ['중성 원자 방식 양자컴퓨팅 게이트 충실도 99.9% 달성. 이온트랩 대비 확장성 우위.', 'QuEra·Pasqal 선두. 2026년 하이브리드 첫 상업 워크로드 목표.'], why: '', notes: [] },
      { weight: 'low', time: '09:00', source: 'Harvard / The Quantum Insider', headline: '하버드: 양자 오류 수정 18개월 앞서 — 2028년 실용 우위 가능', url: 'https://thequantuminsider.com/2026/05/04/harvard-researchers-quantum-computing-advancing-faster-than-expected/', bullets: ['하버드 연구팀, 양자 오류 수정 속도가 업계 예측보다 18개월 앞서 진행.', '현재 궤도 유지 시 2028년 실용 우위 달성 가능.'], why: '', notes: [] },
      { weight: 'low', time: '06:00', source: 'Kipu Quantum', headline: 'Kipu Quantum, 오프라인 하이브리드 양자ML 프레임워크 출시', url: 'https://quantumcomputingreport.com/news/', bullets: ['Kipu Quantum, QPU 실시간 의존성 없는 오프라인 양자ML 추론 프레임워크 발표.', '비용 절감·정확도 향상. 엔터프라이즈 실용화 선제 지원.'], why: '', notes: [] },
      { weight: 'low', time: '08:30', source: 'Quantinuum / Synopsys', headline: 'Quantinuum·Synopsys, 양자컴퓨팅 엔지니어링 시뮬레이션 통합', url: 'https://quantumcomputingreport.com/news/', bullets: ['Quantinuum·Synopsys, 하이브리드 양자-클래식 엔지니어링 시뮬레이션 통합 발표.', 'HPC 한계 극복 — 소재·반도체 설계 가속.'], why: '', notes: [] },
      { weight: 'low', time: '11:00', source: '36Kr', headline: '"2026년 QPU가 GPU 대체하는 첫 해" — 36Kr 분석', url: 'https://eu.36kr.com/en/p/3624758715462150', bullets: ['중국 테크 미디어 36Kr: 2026년이 특정 AI 워크로드에서 QPU가 GPU를 대체하는 원년.', '에너지 효율·속도 기준 양자 우위 영역 확대.'], why: '', notes: [] },
      { weight: 'low', time: '09:30', source: 'HeyGoTrade / Motley Fool', headline: 'IonQ·Rigetti·D-Wave 2026 투자 가이드 — 정부 투자 낙수 효과 지속', url: 'https://www.heygotrade.com/en/blog/quantum-computing-stocks-2026/', bullets: ['IonQ·Rigetti·D-Wave, $20억 정부 투자 후 30%+ 급등 후 일부 되돌림.', '기관 유입·후속 민간 투자 기대로 2026년 하반기 재상승 전망.'], why: '', notes: [] },
    ],
  },
  econ: {
    label: '경제 뉴스',
    summary: '중동 이란 협상 교착으로 WTI가 $104를 돌파하며 호르무즈 봉쇄 우려가 재점화됐고, UN은 세계 경제 성장률을 2.5%로 하향했습니다. 한국은 5월 수출이 64.8% 폭증해 역대 최대를 기록했으나, 7월부터 미국의 Section 301 관세 재부과 예고로 하반기 불확실성이 커지고 있습니다.',
    items: [
      { weight: 'high', time: '07:00', source: '오늘의클릭 / Reuters',
        headline: 'WTI $104 돌파 — 이란 협상 교착·호르무즈 봉쇄 우려 재점화',
        url: 'https://oilprice.com/',
        bullets: ['WTI 원유 선물, 이란-미국 7차 핵 협상 최종 합의 미달로 배럴당 $104 돌파. 호르무즈 해협 봉쇄 우려 재부상.', 'UBS: 전 세계 석유 비축량 82억→76억 배럴로 감소, 2016년 이후 최저 수준 접근.', '유가 $104+는 에너지 인플레 재점화·각국 금리 인하 지연·한국 에너지 수입비 증가로 이어짐.'],
        why: '호르무즈 해협은 전 세계 원유의 20%가 통과합니다. 봉쇄 현실화 시 WTI $130+ 급등 및 글로벌 스태그플레이션 위험이 현실화됩니다.',
        notes: [{ term: '호르무즈 해협', def: '이란-오만 사이 좁은 해협. 전 세계 원유 유통량의 약 20%가 통과하는 에너지 안보 핵심 목지.' }, { term: 'IEEPA 관세', def: '국제경제비상권한법에 의거한 대통령 관세. 미국 대법원이 2026년 위헌 판결.' }] },
      { weight: 'high', time: '09:00', source: '머니투데이 / 관세청',
        headline: '한국 5월 1~20일 수출 64.8% 폭증·반도체 202% — 역대 최대',
        url: 'https://www.mt.co.kr/economy/2026/05/21/2026052108393375556',
        bullets: ['관세청, 5월 1~20일 수출 $526.5억(+64.8% YoY). 5월 기준 역대 최대 수출 기록.', '반도체 수출 $219.5억(+202.1%). AI 서버·HBM 수요 급증 견인. 컴퓨터 주변기기 +305.5%.', '무역수지 흑자 $110억. AI 인프라 투자 사이클이 한국 수출 실적에 직접 연결.'],
        why: '반도체 202% 폭증은 글로벌 AI 인프라 투자 싸이클이 한국 수출 경제에 전달되는 메커니즘입니다.',
        notes: [{ term: 'HBM(고대역폭메모리)', def: 'AI GPU에 탑재되는 초고속 메모리. SK하이닉스·삼성전자·Micron 3강 구도.' }] },
      { weight: 'low', time: '06:00', source: 'UN / 오늘의클릭', headline: 'UN, 세계 경제 성장률 2.5%로 하향 — 중동 에너지 위기·고금리 복합 압박', url: 'https://www.cliktoday.com/2026/05/20260523-today-news.html', bullets: ['UN, 2026년 세계 경제 성장률 2.7%→2.5% 하향. 중동 분쟁 장기화·유가 상승 반영.', '최악 2.1% 추락 가능성 경고.'], why: '', notes: [] },
      { weight: 'low', time: '10:00', source: 'Yahoo Finance / Tax Foundation', headline: '미국 법원 IEEPA 관세 위헌 → 환급 포털, 7월 Section 301 재부과 예고', url: 'https://finance.yahoo.com/economy/policy/live/trump-tariffs-live-updates-us-opens-tariff-refund-portal-with-checks-expected-this-summer-223100182.html', bullets: ['미국 법원 IEEPA 관세 위헌 판결. 환급 포털 개설. 환급 수표 여름 예정.', '정부, 7월부터 무역법 301조 관세 재부과 예고.'], why: '', notes: [] },
      { weight: 'low', time: '08:00', source: '오늘의클릭 / 한국 외교부', headline: '한일 정상회담 — 공급망 협력·원유 비축 정보 공유 합의', url: 'https://www.cliktoday.com/2026/05/20260523-today-news.html', bullets: ['이재명 대통령·다카이치 일본 총리, 경북 안동 정상회담. 중동 사태 대비 공급망 협력 확대.', '원유 비축 정보 공유 심화 합의.'], why: '', notes: [] },
      { weight: 'low', time: '11:00', source: 'Investing.com', headline: 'USD/KRW 1,520원 — 달러 강세·WTI 급등에 원화 약세 압력', url: 'https://kr.investing.com/currencies/usd-krw', bullets: ['달러-원 환율 1,520원. 달러 강세·WTI 급등·중동 지정학 불안 3중 압박.', '한국은행 구두 개입 경계선 접근.'], why: '', notes: [] },
      { weight: 'low', time: '07:30', source: '머니투데이 / 삼성전자', headline: '삼성전자 노사 임금협상 잠정 합의 — HBM4 공급망 정상화 기대', url: 'https://www.mt.co.kr/', bullets: ['삼성전자 노사, 2026년 임금협상 잠정 합의. 파업 위기 해소.', 'HBM4 생산 차질 없이 납품 일정 유지 전망.'], why: '', notes: [] },
      { weight: 'low', time: '09:00', source: 'TradingEconomics', headline: '미국 10Y 국채 4.56% — WTI 급등 상쇄 안전자산 수요·소폭 안정', url: 'https://tradingeconomics.com/united-states/government-bond-yield', bullets: ['미국 10년 국채 4.56%. 전일 4.60%에서 소폭 하락. WTI 급등 vs 안전자산 수요 상충.', '6/17 FOMC 전까지 방향성 탐색 구간.'], why: '', notes: [] },
    ],
  },
  columns: {
    label: '컬럼 피드',
    summary: '오건영 단장은 채권 금리 우려가 지속 확대되는 가운데, 22년 10월 영국 트러스 쇼크·23년 10월·25년 4월 셀아메리카 등 역사적 금리 급등 국면들을 역추적하며 현재 위기의 해결 실마리를 탐색하고 있습니다.',
    items: [
      { name: '오건영', title: '신한은행 · 디지털 크리에이터', avatar: 'OG', color: '#D97757',
        time: '5월 21일 01:00', likes: 514, comments: 15,
        post: '오늘 새벽 소폭 안정세를 보이기는 했지만 여전히 채권 금리에 대한 우려가 계속해서 확대 일로에 있는 듯 합니다. 이렇게 금리가 높았던 시기가 언제 있었을까요.. 물론 20년과 30년물 기준으로는 지금이 더 높았지만... 지난 러-우 전쟁과 연준의 자이언트 스텝 금리 인상, 그리고 영국 트러스 모멘텀이 극에 달했던 22년 10월이 있었죠. 그리고 예상했던 것보다 더 빠르게 금리를 인상하는데 대해 당혹스러운 모습을 보였던 2023년 10월도 그랬습니다. 그리고 트럼프 당선을 전후해서 트럼프 트레이드가 나타났고... 그러다 185개국에 관세를 부과한 이후 셀 아메리카가 터져나오면서 국채 금리가 재차 급등했던 기억이 있죠. 당시에는 어떻게 이런 상황들을 해결해나갔을까요..',
        summary: '채권 금리 역사적 급등 반복 — 22·23·25년 셀아메리카 선례 역추적해 현재 위기 해결 실마리 탐색.',
      },
    ],
  },
  invest: {
    title: 'AI 지능폭발·WTI $104 충격',
    subtitle: 'Claude가 작성한 오늘의 메모 · 5월 24일 09:00 · 5분 읽기',
    sections: [
      { h: '한 줄 요약', body: 'Jack Clark의 AI 재귀적 자기개선 60%+ 예측과 OpenAI 수학 난제 자율 증명이 AI 가속 내러티브를 강화한 반면, WTI $104 돌파와 이란 협상 교착이 에너지 인플레 재점화 리스크를 높이고 있습니다. 삼성전자 노사 합의로 HBM4 공급망은 안정됐습니다.' },
      { h: '오늘의 변수', body: '①Jack Clark 60%+ 예측 → AI 가속·지능폭발 테마 강화 → AI 인프라주 추가 모멘텀. ②WTI $104 돌파 → 에너지 인플레 재점화 → 연준 6/17 금리 인상 가능성 유지. ③삼성전자 노사 합의 → HBM4 생산 정상화 → SK하이닉스·삼성전자 단기 수혜. ④IEEPA 관세 위헌 → 7월 Section 301 재부과 예고 → 한국 수출 불확실성 재부각.' },
      { h: '포지셔닝', body: '단기(1-3개월): AI 재귀적 자기개선 테마로 NVDA·MSFT 집중. 삼성 노사 합의로 SK하이닉스 추가. WTI $104 → 금(GLD) 헤지 비중 확대. TLT 최소화 유지. 중기(6-12개월): OpenAI IPO(9월) 전후 AI 섹터 밸류에이션 재평가. 양자컴퓨팅 정부 투자 효과 지속 → IonQ 분할 진입 검토.' },
      { h: '리스크', body: 'WTI $110+ 돌파 시 에너지 인플레 재점화 → 연준 금리 인상 선언 → 성장주·채권 동반 급락. 이란 협상 완전 결렬 → 호르무즈 봉쇄 → 원유 $130+ 글로벌 충격. OpenAI IPO 고평가 논란 → AI 섹터 전반 조정. 7월 Section 301 관세 재부과 → 한국 수출 하반기 둔화.' },
    ],
    watchlist: [
      { sym: '000660', name: 'SK하이닉스',  val: '1,940,000', pct: '+11.17%', up: true,  note: '삼성 노사 합의·반도체 수출 202% — HBM4 공급 안정화 수혜' },
      { sym: '005930', name: '삼성전자',    val: '299,500',   pct: '+3.64%', up: true,  note: '노사 임금협상 잠정 합의 — HBM4 생산 정상화 기대' },
      { sym: 'NVDA',   name: 'NVIDIA',      val: '$246.20',   pct: '+0.29%', up: true,  note: 'AI 재귀적 자기개선 테마 강화 — 인프라 수요 장기 모멘텀' },
      { sym: 'MSFT',   name: 'Microsoft',   val: '$480.50',   pct: '+0.52%', up: true,  note: 'OpenAI IPO 9월 목표 — Azure AI 수혜 핵심 파트너' },
      { sym: 'TLT',    name: 'iShares 20Y', val: '$86.20',    pct: '-0.35%', up: false, note: 'WTI $104·워시 취임 — 금리 인상 압박 지속' },
      { sym: 'GLD',    name: 'SPDR Gold',   val: '$256.00',   pct: '+1.38%', up: true,  note: 'WTI $104·이란 불확실성·인플레 헤지 — 비중 확대' },
      { sym: 'VYM',    name: 'Vanguard HY', val: '$131.40',   pct: '-0.30%', up: false, note: '고금리 환경 지속 — 배당주 소폭 하락 압력' },
      { sym: 'BTC',    name: 'Bitcoin',     val: '$75,580',   pct: '-1.45%', up: false, note: '주말 거래·달러 강세 — 횡보 구간' },
    ],
    portfolio: [
      { asset: '국내주식', pct: 20, color: '#3DDC97',
        tickers: [{ sym: '000660', name: 'SK하이닉스' }, { sym: '005930', name: '삼성전자' }],
        note: '삼성 노사 합의·반도체 수출 202% — HBM4 공급 안정화' },
      { asset: '미국주식', pct: 18, color: '#5B9BD5',
        tickers: [{ sym: 'NVDA', name: 'NVIDIA' }, { sym: 'MSFT', name: 'Microsoft' }],
        note: 'AI 지능폭발 테마 NVDA + OpenAI IPO 수혜 MSFT' },
      { asset: '채권', pct: 8, color: '#9B8EC4',
        tickers: [{ sym: 'TLT', name: 'iShares 20Y ETF' }],
        note: '워시 취임·WTI 급등 — 금리 압박 최소화 유지' },
      { asset: '금', pct: 27, color: '#F5C518',
        tickers: [{ sym: 'GLD', name: 'SPDR Gold ETF' }],
        note: 'WTI $104·이란 리스크·인플레 — 헤지 비중 확대' },
      { asset: '배당주', pct: 18, color: '#E08A6E',
        tickers: [{ sym: 'VYM', name: 'Vanguard High Div.' }],
        note: '고금리 환경 방어 — 안정적 배당 유지' },
      { asset: '비트코인', pct: 9, color: '#F7931A',
        tickers: [{ sym: 'BTC', name: 'Bitcoin' }],
        note: '주말 횡보 — 소폭 비중 유지' },
    ],
  },
});


const TODAY = {
  date: { iso: '2026-05-26', label: '2026년 5월 26일 화요일', shortLabel: '5월 26일 (화)', isToday: true },
  marketStrip: [
    { sym: 'KOSPI',   val: '8,048',   pct: '+2.55%', up: true  },
    { sym: 'S&P 500', val: '7,473',   pct: '+0.37%', up: true  },
    { sym: 'NASDAQ',  val: '26,344',  pct: '+0.19%', up: true  },
    { sym: 'BTC',     val: '$76,600', pct: '-0.39%', up: false },
    { sym: '$/₩',    val: '1,514',   pct: '-0.39%', up: false },
    { sym: '10Y UST', val: '4.54%',  pct: '-2bp',   up: false },
    { sym: 'WTI',     val: '$87.30',  pct: '-5.19%', up: false },
  ],
  ai: {
    label: 'AI 뉴스',
    summary: 'Anthropic이 Mythos 모델의 일반 공개 계획을 발표하며 방어적 보안 생태계를 넓혀가고 있고, Microsoft-OpenAI 파트너십이 비독점 멀티클라우드 체제로 재편되며 AI 인프라 경쟁의 판도가 바뀌었습니다. Amazon 커스텀 칩이 연 $200억 run-rate를 돌파하며 엔비디아 외 AI 칩 시장의 새 강자로 부상했습니다.',
    items: [
      { weight: 'high', time: '09:00', source: 'Anthropic / The Register',
        headline: 'Anthropic, Mythos급 모델 일반 공개 계획 발표 — 보안 파트너 1개월 성과 공개',
        url: 'https://www.theregister.com/security/2026/05/25/anthropic-to-release-mythos-class-models-to-the-public/5245596',
        bullets: ['Anthropic, 방어 보안 특화 Mythos 모델의 일반 공개 계획 발표. 현재는 Project Glasswing 통해 50개 파트너사에만 배포 중.', '1개월 운영 결과: OSS 1,000개+ 프로젝트서 6,202개 고위험 취약점 발견, 진양성률 90.6%(1,587/1,752). 사상 최대 규모 자동화 보안 감사.', '향후 Opus 시리즈에 안전장치와 함께 통합 예정. 공개 시점 미정 — 안전성 확보 후 출시 원칙 유지.'],
        why: 'AI 모델이 사이버보안 공격 도구로 전용될 수 있다는 우려 속에, Anthropic은 방어 우선 공개 전략으로 신뢰를 쌓으면서도 결국 공개 배포를 선택했습니다. AI 안전-능력 균형 논쟁의 새 기준점입니다.',
        notes: [{ term: 'Project Glasswing', def: 'Anthropic의 방어적 보안 파트너십 프로그램. 화이트햇 해커·보안 기업에 Mythos 접근권 제공.' }, { term: 'true-positive rate', def: '모델이 탐지한 취약점 중 실제 취약점 비율. 90.6%는 오탐(false alarm) 9.4%를 의미.' }] },
      { weight: 'high', time: '08:00', source: 'Microsoft Blog / OpenAI',
        headline: 'Microsoft-OpenAI 비독점 파트너십 재편 — 멀티클라우드 허용, Azure 독점 해제',
        url: 'https://blogs.microsoft.com/blog/2026/04/27/the-next-phase-of-the-microsoft-openai-partnership/',
        bullets: ['4/27 발표: OpenAI, 이제 모든 클라우드에서 서비스 제공 가능. Microsoft Azure 독점 계약 해제.', 'Microsoft 라이선스 비독점화 · 수익공유 폐지(2030년까지 OpenAI→MS 수익공유는 유지). 2032년까지 라이선스 권리 보유.', '배경: OpenAI가 Amazon과 최대 $50억 투자·$1,380억 AWS 계약 체결. 멀티클라우드 전략 필요성 증가.'],
        why: 'AI 모델의 클라우드 배포 독점 구조가 무너지며 AWS·GCP 등이 OpenAI 서비스 제공자로 공식 참여합니다. 클라우드 AI 시장 경쟁이 全방위로 확대됩니다.',
        notes: [{ term: '멀티클라우드', def: 'AWS·Azure·GCP 등 여러 클라우드를 동시에 활용하는 전략. 벤더 종속 방지와 비용 최적화가 목적.' }, { term: '수익공유(Revenue Share)', def: '사용자가 낸 매출의 일정 비율을 파트너에게 지급하는 구조. Microsoft와 OpenAI 간 핵심 재무 조건.' }] },
      { weight: 'high', time: '07:30', source: 'Amazon Q1 2026 / The Register',
        headline: 'Amazon 커스텀 칩 연 $200억 run-rate 돌파 — Trainium 수주잔고 $2,250억',
        url: 'https://theregister.com/2026/04/29/amazon_chips_20b_business',
        bullets: ['Q1 2026 어닝콜: Amazon Graviton·Trainium·Nitro 합산 연 $200억 run-rate 달성. 전 분기 대비 40% 성장, yoy 세 자릿수 성장.', 'Trainium 수주잔고 $2,250억. Anthropic 5GW, OpenAI 2GW 용량 계약. 사실상 AI 칩 빅3(엔비디아·구글TPU·Amazon) 구도.', 'Jassy: "독립 기업으로 판다면 연 $500억 규모." 데이터센터 칩 시장 판도 재편.'],
        why: '엔비디아 GPU 외의 AI 칩 공급망이 다변화되고 있습니다. Amazon이 칩 사업만으로 빅3에 진입한 것은 AI 인프라 경쟁이 클라우드 기업의 하드웨어 내재화로 이동하고 있음을 보여줍니다.',
        notes: [{ term: 'Trainium', def: 'Amazon이 AI 학습용으로 개발한 전용 칩(ASIC). AWS 데이터센터에서 운용되며 엔비디아 H100 대체재.' }, { term: 'run-rate', def: '현재 분기 매출을 연간으로 환산한 추정치. 빠르게 성장하는 사업의 규모를 나타내는 지표.' }] },
      { weight: 'low', time: '10:00', source: 'TLT LLP / Radical Data Science',
        headline: 'EU AI법 개정 교착 — 8월 고위험 AI 시스템 규제 데드라인 유지',
        url: 'https://www.tlt.com/insights-and-events/insight/ai-brief-may-2026',
        bullets: ['EU AI법 개정 협상 교착 상태 지속. 2026년 8월 고위험 AI 시스템 규제 의무 시행 데드라인 그대로 유지.', '기업들은 8월 전까지 고위험 AI 시스템 적합성 평가·문서화·투명성 요건 준수 필요. 유럽 내 AI 서비스 진입 장벽으로 작용.'],
        why: '', notes: [] },
      { weight: 'low', time: '09:30', source: 'OpenAI / TechCrunch',
        headline: 'OpenAI DeployCo 컨설팅 자회사 출범 — $40억 초기 투자, Tomoro 인수',
        url: 'https://techdg.in/latest-ai-updates-may-2026-global-ai-news-trends/',
        bullets: ['OpenAI, AI 구현 컨설팅 자회사 "Deployment Co.(DeployCo)" 출범. 초기 $40억+ 투자.', '응용 AI 컨설팅 기업 Tomoro 인수. 기업 고객 현장 배포 지원 강화.'],
        why: '', notes: [] },
      { weight: 'low', time: '08:30', source: 'CNBC / Survey',
        headline: '기업 76% Chief AI Officer 도입 완료 — 1년 만에 26%→76% 급등',
        url: 'https://www.cnbc.com/2026/05/11/heres-how-artificial-intelligence-is-changing-boardrooms.html',
        bullets: ['2,000개+ 기업 조사: CAIO 도입률 2025년 26% → 2026년 76%로 1년 만에 3배 급증.', 'AI 활용이 신시장 개척보다 내부 프로세스 효율화에 집중. AI 거버넌스 구조화 단계 진입.'],
        why: '', notes: [] },
      { weight: 'low', time: '11:00', source: 'Google / CNBC',
        headline: 'Gemini 3.5 Flash 출시 — 최고급 모델 대비 1/2~1/3 가격에 최첨단 성능',
        url: 'https://www.cnbc.com/2026/05/19/google-ai-ultra-gemini-spark-omni.html',
        bullets: ['Google Gemini 3.5 Flash, 동급 최고 모델 대비 절반~1/3 가격으로 최첨단 멀티모달 성능 제공.', '에이전트·추론·코딩 특화. 비용 효율 AI 모델 경쟁 심화 — 기업 도입 허들 낮아짐.'],
        why: '', notes: [] },
      { weight: 'low', time: '07:00', source: 'CNBC / Trump 행정부',
        headline: '미 정부, AI 모델 공개 전 테스트 의무화 추진 — Google·MS·xAI 동의',
        url: 'https://www.cnbc.com/2026/05/05/ai-oversight-trump-google-microsoft-xai.html',
        bullets: ['트럼프 행정부, AI 모델 공개 전 정부 테스트 의무화 방침 발표. Google·Microsoft·xAI 조기 접근 제공 동의.', '기업-규제 당국 협력 모델. AI 안전 규제 프레임워크 구체화 시작.'],
        why: '', notes: [] },
    ],
  },
  physical: {
    label: '피지컬 AI 뉴스',
    summary: 'Tesla가 프리몬트 공장을 Optimus Gen3 로봇 전용 생산 시설로 전환하며 연 100만대를 목표로 삼았고, Boston Dynamics Atlas가 현대차 조지아 공장 및 Google DeepMind에 배송을 시작했습니다. Figure AI는 BMW 30,000대 생산 지원 성과를 바탕으로 독일 라이프치히 확대 및 가정용 파일럿을 시작하며 휴머노이드 상업화가 본격 가속되고 있습니다.',
    items: [
      { weight: 'high', time: '09:00', source: 'Standard Bots / VFutureMedia',
        headline: 'Tesla, 프리몬트 공장 Optimus Gen3 전용 전환 — Q2 2026, 연 100만대 목표',
        url: 'https://standardbots.com/blog/tesla-robot',
        bullets: ['Tesla, 캘리포니아 프리몬트 공장을 2026년 Q2 휴머노이드 로봇 생산 전용으로 전환. Model S·X 라인 폐지.', 'Optimus Gen3: AI5 기반 재설계, 2026년 여름 양산 시작 목표. 연 100만대 풀 캐퍼시티 계획.', 'Musk 인정: 현재 공장 내 Optimus는 학습 데이터 수집 목적 — 실질 노동 생산성은 R&D 단계.'],
        why: 'Tesla가 자동차 공장을 로봇 공장으로 전환한 것은 로봇이 자동차를 대체하는 역사적 전환점입니다. 연 100만대 목표가 실현되면 글로벌 제조업 자동화 비용이 급격히 낮아집니다.',
        notes: [{ term: 'AI5', def: 'Tesla의 5세대 AI 하드웨어. Optimus Gen3의 두뇌 역할로 실시간 동작 계획·환경 인식에 활용.' }, { term: '풀 캐퍼시티', def: '생산 설비를 최대 가동률로 운영할 때의 생산량. 초기 목표 대비 실제 달성까지 수년이 걸릴 수 있음.' }] },
      { weight: 'high', time: '08:00', source: 'The Register / GrabaRobot',
        headline: 'Boston Dynamics Atlas, 현대차 조지아·Google DeepMind 배송 시작 — 2026년 물량 모두 배정',
        url: 'https://www.theregister.com/2026/01/06/boston_dynamics_atlas_production/',
        bullets: ['Boston Dynamics, Atlas 상업 생산 최종 버전 배송 시작. 현대 Robotics Metaplant Application Center(RMAC) 및 Google DeepMind.', '2026년 전체 물량 이미 확정 배치 완료. 수만대 현대차 공장 배치 목표.', '현대차는 Atlas를 통해 제조 라인 자동화 및 로봇 운영 데이터 축적 병행.'],
        why: '세계 최고 기술력의 Atlas 로봇이 실제 산업 현장에 대규모 배치된다는 것은 피지컬 AI의 파일럿 단계 종료를 의미합니다. 현대차와 Google의 동시 배치는 제조+AI 양 섹터의 혁신을 가속합니다.',
        notes: [{ term: 'RMAC(Robotics Metaplant Application Center)', def: '현대차그룹의 로봇 적용 연구 거점. 조지아 메타플랜트에 위치하며 Atlas 운용 허브.' }] },
      { weight: 'high', time: '10:00', source: 'Figure AI / humanoid.press',
        headline: 'Figure AI, BMW 30,000대 생산 지원 완료 · 라이프치히 확대 · 가정용 파일럿 시작',
        url: 'https://humanoid.press/',
        bullets: ['Figure 02, BMW Spartanburg에서 30,000+ 차량 생산 지원. 90,000+ 판금 부품 이동, 1,250+ 시간 운영.', '독일 라이프치히 공장으로 확대 배치 확정. BMW와 멀티사이트 파트너십으로 진화.', '최초 가정용 파일럿 프로그램 시작. 일반 소비자 환경에서의 적응력 검증 단계.'],
        why: '자동차 공장을 넘어 가정으로 확장되는 Figure AI의 행보는 휴머노이드 로봇의 시장 타겟이 B2B에서 B2C로 확장되고 있음을 보여줍니다.',
        notes: [{ term: 'Figure 02', def: 'Figure AI의 2세대 휴머노이드 로봇. OpenAI와 협력해 언어-동작 통합 AI 탑재.' }] },
      { weight: 'low', time: '07:00', source: 'Physical Intelligence',
        headline: 'Physical Intelligence pi-0.7, 학습 없이 에어프라이어 조작 성공 — 범용 로봇 지능 진전',
        url: 'https://humanoid.press/',
        bullets: ['π0.7, 훈련 데이터 없이 에어프라이어 조작 성공. 웹 사전학습과 훈련 단편 합성으로 미학습 작업 수행.', '로봇 행동 기반 모델의 범용화 가능성 입증. 산업별 재학습 비용 대폭 절감 기대.'],
        why: '', notes: [] },
      { weight: 'low', time: '09:30', source: 'KraneShares / Memeburn',
        headline: 'Humanoid-Schaeffler 2032년까지 1,000~2,000대 글로벌 공장 배치 계약 체결',
        url: 'https://kraneshares.com/humanoid-robotics-in-2026-the-race-from-pilot-to-platform/',
        bullets: ['영국 Humanoid사, Schaeffler와 2032년까지 휠체어형 휴머노이드 1,000~2,000대 글로벌 공장 배치 계약(5/13).', 'Schaeffler의 전 세계 생산 거점에 단계적 배치. 유럽 제조업 로봇화 확대 사례.'],
        why: '', notes: [] },
      { weight: 'low', time: '11:00', source: 'Morgan Stanley / KraneShares',
        headline: 'Morgan Stanley, 로봇 시장 전망 — 2030년 4만대, 2050년 6,300만대',
        url: 'https://www.seekingalpha.com/article/4903621-humanoid-robotics-in-2026-race-from-pilot-to-platform',
        bullets: ['Morgan Stanley: 2030년 휴머노이드 4만대 배치 → 2050년 6,300만대로 폭발적 성장 전망.', '중국 내수 시장만 2029년 $102.6억 규모. 피지컬 AI 투자 급증 배경.'],
        why: '', notes: [] },
      { weight: 'low', time: '08:30', source: 'Agility Robotics / NVIDIA Blog',
        headline: 'Agility Digit, Toyota Canada RAV4 자재 처리 7대 가동 — 공장 자동화 확산',
        url: 'https://blogs.nvidia.com/blog/national-robotics-week-2026/',
        bullets: ['Agility Digit 7+대, Toyota Canada에서 RAV4 자재 처리 작업 수행 중.', 'NVIDIA Physical AI 모델 기반. 자동차 부품 물류 자동화 실용화 단계 확인.'],
        why: '', notes: [] },
      { weight: 'low', time: '06:30', source: 'NVIDIA Newsroom',
        headline: 'NVIDIA, 차세대 피지컬 AI 모델 공개 — 글로벌 파트너 신규 로봇 발표',
        url: 'https://nvidianews.nvidia.com/news/nvidia-releases-new-physical-ai-models-as-global-partners-unveil-next-generation-robots',
        bullets: ['NVIDIA, 새로운 피지컬 AI 모델 패키지 공개. 로봇 동작 계획·환경 인식·언어-행동 통합 개선.', '글로벌 로봇 파트너사들, NVIDIA 기반 차세대 로봇 동시 발표. 피지컬 AI 생태계 확장.'],
        why: '', notes: [] },
    ],
  },
  quantum: {
    label: '양자 뉴스',
    summary: '미국 정부가 IBM·D-Wave·Rigetti 등 9개 양자컴퓨팅 기업에 $20억을 투자하며 지분까지 취득하는 사상 첫 양자 국가 산업 정책을 시행했고, IBM은 Cleveland Clinic·RIKEN과 함께 12,635원자 단백질 시뮬레이션으로 세계 최대 양자-고전 하이브리드 계산을 달성했습니다. CNN은 양자 컴퓨터가 현재의 암호화를 깰 Q-Day 위협이 2029년 이전에 올 수 있다고 경고하며 사이버보안 업계의 긴장감이 고조되고 있습니다.',
    items: [
      { weight: 'high', time: '09:00', source: 'CNBC / CNN Business',
        headline: '미 정부, 양자컴퓨팅 9개사에 $20억 투자·지분 취득 — IBM $10억, D-Wave +33%',
        url: 'https://www.cnbc.com/2026/05/21/quantum-stocks--us-taking-equity-stakes.html',
        bullets: ['5/21 발표: 미 상무부, 9개 양자컴퓨팅 기업에 Chips & Science Act 재원 $20억 배분 + 지분 취득. 미국 역사상 첫 양자 국가 산업 정책.', 'IBM $10억, GlobalFoundries $3.75억, D-Wave·Rigetti·PsiQuantum·Infleqtion 각 $1억, Diraq $3,800만. 9개사 망라.', 'D-Wave +33%, Rigetti +30%, Infleqtion +31%, IonQ +12%, 비수혜 Arqit +25% 동반 급등.'],
        why: '정부가 양자컴퓨팅 기업에 지분을 취득하며 투자한 것은 양자 기술을 반도체처럼 전략 산업으로 지정한 신호입니다. 미중 기술 패권 경쟁이 양자 영역으로 확대됩니다.',
        notes: [{ term: 'Chips & Science Act', def: '2022년 미 의회가 통과시킨 반도체·과학 육성법. $527억 반도체 보조금 외 양자·AI 연구 재원 포함.' }, { term: '양자 우위(Quantum Advantage)', def: '양자컴퓨터가 특정 문제에서 최강 슈퍼컴을 앞서는 시점. 현재는 특정 과학 계산에서 부분 달성.' }] },
      { weight: 'high', time: '08:00', source: 'IBM Quantum / PR Newswire',
        headline: 'IBM+Cleveland Clinic+RIKEN, 12,635원자 단백질 시뮬레이션 — 세계 최대 양자 계산',
        url: 'https://newsroom.ibm.com/2026-05-05-cleveland-clinic,-riken,-and-ibm-model-a-12,635-atom-protein-the-largest-known-to-be-simulated-with-quantum-computers',
        bullets: ['5/5 발표: IBM 156큐비트 Heron 프로세서 2기(Cleveland Clinic·RIKEN 거점), 94큐비트 활용 ~6,000 양자 연산으로 트립신(12,635원자) 양자역학 시뮬레이션 성공. 생명과학 양자 시뮬레이션 세계 최대.', '6개월 내 시뮬레이션 크기 40배↑, 정확도 210배↑. 슈퍼컴 Fugaku(RIKEN)·Miyabi-G(도쿄대) 하이브리드 활용.', '약물-단백질 결합 예측에 직접 응용 가능. 신약 개발 기간 단축 가능성.'],
        why: '12,635원자는 현재 고전 컴퓨터로는 정확히 계산 불가한 규모입니다. 양자 컴퓨터가 의약·화학 분야에서 실용적 우위를 보이기 시작했음을 의미합니다.',
        notes: [{ term: 'Heron 프로세서', def: 'IBM의 최신 세대 양자 프로세서. 156큐비트, 낮은 오류율이 특징. Eagle·Osprey를 잇는 4세대.' }, { term: '양자-고전 하이브리드', def: '양자컴퓨터와 슈퍼컴퓨터를 병렬 결합해 서로의 강점을 활용하는 계산 방식.' }] },
      { weight: 'low', time: '10:30', source: 'CNN / MIT News',
        headline: 'CNN, Q-Day 양자 사이버위협 특집 — 2029년 전 암호화 붕괴 가능 경고',
        url: 'https://www.cnn.com/2026/05/17/science/quantum-computing-cybersecurity-q-day',
        bullets: ['"Harvest Now, Decrypt Later" 공격 현실화 우려. 적대 세력이 지금 암호 데이터를 수집해 미래 양자컴으로 해독 전략.', 'Quantum Threat Timeline Report: Q-Day "10년 내 가능, 15년 내 유력". Google 2029년 post-quantum 암호화 목표 발표.'],
        why: '', notes: [] },
      { weight: 'low', time: '08:30', source: 'phys.org',
        headline: '양자 오류의 지속적 원인 규명 — 퀀텀 노이즈 메커니즘 최초 설명',
        url: 'https://phys.org/news/2026-05-persistent-quantum-error.html',
        bullets: ['연구진, 양자 게이트 오류의 지속적 발생 원인을 최초로 규명. 오류 억제 설계 개선 가능성 열림.', '내결함성 양자컴퓨터 실현의 핵심 장벽 제거 가능성. 큐비트 신뢰성 향상 로드맵 구체화.'],
        why: '', notes: [] },
      { weight: 'low', time: '07:00', source: 'The Quantum Insider',
        headline: 'Q-Day, 3개월 내 논문 3편으로 위협 타임라인 앞당겨져',
        url: 'https://thequantuminsider.com/2026/03/31/q-day-just-got-closer-three-papers-in-three-months-are-rewriting-the-quantum-threat-timeline/',
        bullets: ['2026년 Q1: 양자 우위 가속 논문 3편 발표로 Q-Day 도래 시점 앞당겨질 수 있다는 분석 확산.', 'RSA·ECC 암호화 취약 기간이 기존 예상보다 단축될 가능성. 금융·의료 데이터 시급 대응 필요.'],
        why: '', notes: [] },
      { weight: 'low', time: '11:00', source: 'IndexBox / McKinsey',
        headline: 'McKinsey, 2035년 양자 시장 $720억 전망 — IonQ·Alphabet·NVIDIA 성장주 주목',
        url: 'https://www.indexbox.io/blog/3-quantum-computing-stocks-to-watch-in-2026/',
        bullets: ['McKinsey: 2035년 글로벌 양자컴퓨팅 시장 $720억 규모 전망.', 'IonQ·Alphabet·NVIDIA, 양자 포트폴리오 보유 성장주로 투자자 주목.'],
        why: '', notes: [] },
      { weight: 'low', time: '09:00', source: 'IEEE Spectrum',
        headline: 'Neutral Atom 양자컴퓨팅 2026년 대도약 — 새로운 큐비트 아키텍처 부상',
        url: 'https://spectrum.ieee.org/neutral-atom-quantum-computing',
        bullets: ['중성 원자 기반 양자컴퓨팅, 2026년 오류율 개선으로 초전도 방식 대비 경쟁력 강화.', '큐에라·패서큰텀 등 스타트업 급부상. 다양한 큐비트 기술 경쟁으로 업계 혁신 가속.'],
        why: '', notes: [] },
      { weight: 'low', time: '06:30', source: 'The Quantum Insider',
        headline: 'PsiQuantum, 미 정부 $1억 지원 확정 — 광자 기반 100만 큐비트 로드맵',
        url: 'https://thequantuminsider.com/2026/05/21/reports-us-to-award-2-billion-to-quantum-companies-take-equity-stakes/',
        bullets: ['PsiQuantum, 미 정부 $1억 지원 확정. 광자(포토닉) 기반 100만 큐비트 양자컴퓨터 개발 목표.', 'GlobalFoundries와 협력해 반도체 공정으로 양자 칩 양산 전략.'],
        why: '', notes: [] },
    ],
  },
  econ: {
    label: '경제 뉴스',
    summary: '호르무즈 해협 개방 기대감에 WTI가 5% 급락하며 인플레이션 압력 완화 신호를 보낸 가운데, KOSPI는 반도체·전기전자 중심 매수로 8,048까지 치솟으며 52주 신고가를 경신했습니다. G7 재무장관회의는 글로벌 채권 매도세에 공동 대응을 거부했고, 미국은 Memorial Day 이후 5/26 시장 재개와 함께 1Q GDP·고용 데이터에 다시 시선이 모입니다.',
    items: [
      { weight: 'high', time: '09:10', source: '서울신문',
        headline: 'KOSPI 8,048 (+2.55%) 52주 신고가 — 반도체·전기전자 중심 외국인·기관 동반 매수',
        url: 'https://www.seoul.co.kr/news/economy/securities/2026/05/26/20260526500051',
        bullets: ['5/26 오전 KOSPI 8,047.77에 개장 (+2.55%), 장중 8,094.90으로 52주 신고가 경신. 외국인·기관 프로그램 매수 동반.', '반도체(SK하이닉스·삼성전자)·전기전자 섹터 집중 매수 유입. AI 수요 기대감과 호르무즈 개방 기대가 복합 작용.', '5/20 외국인·프로그램 매도에 7,208.95로 마감한 이후 4거래일 만에 약 840포인트 회복.'],
        why: '호르무즈 개방 기대가 에너지 비용 인하로 이어질 경우 제조·반도체 기업의 수익성이 개선됩니다. KOSPI 신고가는 국내 증시가 글로벌 불확실성을 소화하고 있음을 의미합니다.',
        notes: [{ term: '프로그램 매수', def: '컴퓨터 알고리즘이 자동으로 실행하는 주식 매매. 대량 매수·매도로 지수 변동성 증폭 효과.' }] },
      { weight: 'high', time: '08:00', source: '오건영 페이스북 / 다수 언론',
        headline: '호르무즈 개방 기대 — WTI $87 급락, 이란 협상 진전 보도',
        url: 'https://www.facebook.com/ohrang79',
        bullets: ['이란-미국 협상 진전 보도에 호르무즈 해협 개방 기대감 확산. WTI 전일 대비 5% 급락, $87.30까지 하락.', 'WTI는 전쟁 전 대비 고점에서 약 22% 하락. 에너지 비용 인하로 인플레 압력 완화 기대.', '오건영 단장(신한은행): "호르무즈가 이제 풀리는 건가? 6월 긴장감 해소 가능성" 언급. 채권금리 안정 기대도 병행.'],
        why: '호르무즈 봉쇄는 글로벌 원유 수송의 약 20%를 차단했습니다. 개방이 현실화되면 WTI 하락→인플레 완화→연준 금리 인하 기대→채권·주식 동반 랠리라는 시나리오가 가능해집니다.',
        notes: [{ term: '호르무즈 해협', def: '이란·오만 사이 폭 33km 해협. 중동 원유의 약 20%가 통과. 봉쇄 시 글로벌 에너지 대란.' }] },
      { weight: 'high', time: '10:00', source: 'Reuters / Bloomberg',
        headline: 'G7 재무장관회의, 채권 매도세 공동 대응 거부 — 각국 자국 책임 입장 확인',
        url: 'https://koreatownnews.com/%EA%B2%BD%EC%A0%9C%EC%A0%84%EB%A7%9D-2026%EB%85%84-5%EC%9B%94-%EA%B2%BD%EC%A0%9C-%ED%98%84%ED%99%A9-%EB%B6%84%EC%84%9D%EA%B3%BC-%EC%A0%84%EB%A7%9D/',
        bullets: ['가타야마 日재무상: G7 채권 매도세 공동 대응 "고려 안 한다". 각국이 자국 상황 책임져야 하는 입장.', '"글로벌 채권 매도세는 유가 상승+호르무즈 봉쇄가 원인" G7 공감대 형성. 근본 원인 진단은 일치.', '공동 행동 부재로 채권 금리 불안 지속 우려. 각국 재정·통화 정책 부담 가중.'],
        why: '2022년 글로벌 금리 발작 당시와 달리 이번에는 공조 없음을 공식 확인했습니다. 에너지 위기가 근본 원인이므로 호르무즈 개방 없이는 채권 안정이 어렵다는 분석이 힘을 얻습니다.',
        notes: [{ term: 'G7 재무장관회의', def: '미·영·독·불·일·이·캐 7개국 재무장관+중앙은행 총재 회의. 글로벌 금융 공조 논의하는 최고 협의체.' }] },
      { weight: 'low', time: '07:00', source: 'AP / CNBC',
        headline: '미국 Memorial Day 연휴 5/25 — 뉴욕 증시 5/26 재개',
        url: 'https://www.washingtonpost.com/business/2026/05/22/wall-street-stocks-dow-nasdaq/a4391d0a-561b-11f1-9c40-7a0a12d9e745_story.html',
        bullets: ['5/25(月) 미국 현충일(Memorial Day)로 뉴욕 증시·채권 시장 휴장. 5/26(화) 재개.', '마지막 거래일 5/22: S&P 500 7,473 (+0.37%), NASDAQ 26,344 (+0.19%). 호르무즈 뉴스 및 WTI 급락이 재개 장에 반영될 전망.'],
        why: '', notes: [] },
      { weight: 'low', time: '09:30', source: 'Trading Economics / FRED',
        headline: '연준 기준금리 3.50~3.75% 동결 — 2026년 1회 인하 최대, 하반기 예상',
        url: 'https://ko.tradingeconomics.com/united-states/gdp-growth',
        bullets: ['3월 FOMC: 기준금리 3.50~3.75% 동결. 시장 중론 2026년 내 1회 25bp 인하, 빨라야 하반기.', '호르무즈 개방 시 에너지 인플레 완화 → 금리 인하 가능성 상향 조정 기대.'],
        why: '', notes: [] },
      { weight: 'low', time: '08:30', source: 'BEA / Reuters',
        headline: '미국 1Q 2026 GDP 2.0% 성장 — 예상치 2.3% 하회, 전쟁·에너지 비용 영향',
        url: 'https://www.kcif.or.kr/economy/economyView?rpt_no=36508&mn=003002',
        bullets: ['미국 1Q 2026 GDP 성장률 연율 2.0%. 전 분기 0.5%에서 개선됐으나 시장 예상치 2.3% 하회.', '이란 전쟁 촉발 에너지 비용 상승이 기업 투자 위축. 소비는 견조, 투자·순수출 부진.'],
        why: '', notes: [] },
      { weight: 'low', time: '11:00', source: 'Naver Finance / Reuters',
        headline: 'USD/KRW 1,514원 — 호르무즈 기대에 원화 강세 진입',
        url: 'https://kr.investing.com/currencies/usd-krw',
        bullets: ['USD/KRW 1,514원. 전주 1,520원 대비 원화 강세. 호르무즈 개방 기대+WTI 하락이 한국 경상수지 개선 기대 반영.', '1,500원 하향 돌파 시 수출주 영향 주목 필요.'],
        why: '', notes: [] },
      { weight: 'low', time: '06:30', source: 'PwC Korea / 기재부',
        headline: '한국 상반기 소비 중심 내수 회복 견조 — 하반기 둔화 가능성 유의',
        url: 'https://www.pwc.com/kr/ko/insights/samil-insight/samilpwc_economic-outlook2026.pdf',
        bullets: ['2026년 한국 경제: 상반기 소비 내수 중심 성장세 강화. 정부 재정 확대가 하방 완충.', '하반기 에너지 불확실성 해소 여부에 따라 성장 경로 변수. 이란 전쟁 종료 시 하반기 모멘텀 재확보 가능.'],
        why: '', notes: [] },
    ],
  },
  columns: {
    label: '컬럼 피드',
    summary: '오건영 단장이 호르무즈 해협 개방 가능성을 타진하며 "벙커 안 1개월 식량"이라는 비유로 시장의 에너지 긴장감이 6월이 되면 임계점에 달할 수 있다고 경고했습니다. 전쟁 종료 시 시나리오와 채권·주식의 디커플링 해소 가능성에 대한 심층 분석을 이어가고 있습니다.',
    items: [
      {
        name: '오건영',
        title: '신한은행 · 디지털 크리에이터',
        avatar: 'OG',
        color: '#D97757',
        time: '어제 23:00',
        likes: 557,
        comments: 10,
        post: '호르무즈 해협이 이제 풀리는 건가요. 전쟁으로 인한 호르무즈 봉쇄가 더 이어지게 되면.. 특히 6월이 되었을 때 시장이 느끼는 긴장감은 매우 클 겁니다. 이런 얘기를 해보죠. 밖에 거대한 태풍이 몰려와서 지하 벙커에 숨었다구요... 벙커 안에는 답답하지만 그래도 1개월치 식량이 가득 준비되어 있죠. 거기서 리더가 말합니다. "우리 지금 남은 식량이 1개월치인데, 태풍이 언제 끝날지 모르겠습니다. 당장 걱정하지 않아도 되지만... 태풍이 한 달을 넘어가면 매우 불안한 상황이 올 수 있습니다." — 지금 시장의 상황이 이와 비슷합니다. 호르무즈 봉쇄가 풀릴 기미가 보이면서 시장이 안도하고 있지만, 6월까지 봉쇄가 이어질 경우 채권 금리 발작 재발 가능성을 배제할 수 없습니다.',
        summary: '호르무즈 해협 개방 기대 속 6월 지속 봉쇄 시 채권 금리 발작 재발 위험 경고'
      }
    ],
  },
  invest: {
    title: '호르무즈 완화·AI 반도체 랠리',
    subtitle: `Claude가 작성한 오늘의 메모 · 5월 26일 06:30 · 4분 읽기`,
    sections: [
      { h: '한 줄 요약', body: '호르무즈 개방 기대로 WTI가 5% 급락하며 인플레 완화 신호를 보내는 동시에, AI 반도체 수요 강세가 KOSPI를 52주 신고가로 밀어 올렸습니다. 채권-주식 디커플링 해소 국면의 초입에 진입 중입니다.' },
      { h: '오늘의 변수', body: '①호르무즈 해협: 협상 진전 확인 시 WTI 추가 하락·채권 안정·주식 랠리 연장. 협상 결렬 시 6월 에너지 위기 재부각. ②5/26 뉴욕 증시 재개: Memorial Day 이후 호르무즈 뉴스+WTI 급락이 반영되는 첫 거래일. 선물 갭 주의. ③Amazon AI칩 $200억·Microsoft-OpenAI 재편: AI 인프라 수혜주 재편성.' },
      { h: '포지셔닝', body: '단기(1-3개월): 호르무즈 개방 확인 시 에너지 비용 인하 수혜 반도체·전기전자 비중 확대. WTI 하락 지속 시 TLT 채권 비중 점진적 확대. 중기(6-12개월): AI 인프라 투자 사이클(Amazon Trainium·Microsoft Azure·SK하이닉스 HBM) 핵심 보유. 호르무즈 완전 개방 시 인플레 정상화→연준 금리 인하 가능성 상승, 성장주+채권 동반 수혜 시나리오.' },
      { h: '리스크', body: '①호르무즈 협상 역전: 개방 기대가 꺾이면 WTI 재급등·채권금리 발작 재발. ②G7 공조 거부 확인: 각국 재정·통화 정책 독자 대응으로 달러 변동성 확대. ③AI 밸류에이션: Amazon·Microsoft 커스텀칩 기대가 주가에 과잉 선반영될 경우 조정 위험. ④미국 GDP 예상 하회: 소비 외 투자·수출 부진 지속 시 성장 둔화 우려 재부각.' },
    ],
    watchlist: [
      { sym: '000660', name: 'SK하이닉스', val: '300,000', pct: '+3.20%', up: true,  note: 'KOSPI 신고가 견인 1등 공신, AI HBM 수요 지속' },
      { sym: '005930', name: '삼성전자',   val: '93,000',  pct: '+2.10%', up: true,  note: 'HBM4 양산+파운드리 수주 기대, KOSPI 동반 상승' },
      { sym: 'AMZN',   name: 'Amazon',    val: '$265',    pct: '+2.80%', up: true,  note: '커스텀 칩 $200억 run-rate 달성, Trainium 수주잔고 $2,250억' },
      { sym: 'MSFT',   name: 'Microsoft', val: '$488',    pct: '+1.50%', up: true,  note: 'OpenAI 비독점 재편으로 멀티클라우드 수혜, Agent 365 GA' },
      { sym: 'TLT',    name: 'iShares 20Y ETF', val: '$88.50', pct: '+1.20%', up: true, note: '호르무즈 완화 기대에 금리 하락 기대 선반영' },
      { sym: 'GLD',    name: 'SPDR Gold ETF',   val: '$242',   pct: '+0.80%', up: true, note: '지정학 리스크 헤지 수요 유지, 달러 약세 보조' },
      { sym: 'VYM',    name: 'Vanguard High Div.', val: '$132', pct: '+0.40%', up: true, note: '금리 안정 기대에 배당주 수요 점진적 회복' },
      { sym: 'BTC',    name: 'Bitcoin',    val: '$76,600', pct: '-0.39%', up: false, note: '전반적 위험 선호 속 소폭 차익 실현' },
    ],
    portfolio: [
      { asset: '국내주식', pct: 20, color: '#3DDC97',
        tickers: [{ sym: '000660', name: 'SK하이닉스' }, { sym: '005930', name: '삼성전자' }],
        note: 'KOSPI 신고가·AI HBM 수요·호르무즈 에너지 비용 완화 수혜 핵심' },
      { asset: '미국주식', pct: 30, color: '#5B9BD5',
        tickers: [{ sym: 'AMZN', name: 'Amazon' }, { sym: 'MSFT', name: 'Microsoft' }],
        note: 'AI 인프라 커스텀칩 $200억·비독점 파트너십 재편 수혜' },
      { asset: '채권', pct: 20, color: '#9B8EC4',
        tickers: [{ sym: 'TLT', name: 'iShares 20Y ETF' }],
        note: '호르무즈 완화 시 금리 하락 기대, 리스크 헤지 겸용' },
      { asset: '금', pct: 10, color: '#F5C518',
        tickers: [{ sym: 'GLD', name: 'SPDR Gold ETF' }],
        note: '지정학 리스크 잔존 구간 안전 자산 보유' },
      { asset: '배당주', pct: 10, color: '#E08A6E',
        tickers: [{ sym: 'VYM', name: 'Vanguard High Div.' }],
        note: '금리 안정 기대 진입 구간, 배당 수익 방어' },
      { asset: '비트코인', pct: 10, color: '#F7931A',
        tickers: [{ sym: 'BTC', name: 'Bitcoin' }],
        note: '위험 선호 회복 시 상승 옵션, 변동성 관리 필요' },
    ],
  },
};


window.BRIEF_ARCHIVE = { '2026-05-26': TODAY, '2026-05-25': D_0525, '2026-05-24': D_0524 };
window.BRIEF_DATES   = ['2026-05-26', '2026-05-25', '2026-05-24'];
window.BRIEF_TODAY   = '2026-05-26';
window.BRIEF_USER    = '재현';
window.BRIEF_DATA    = TODAY;
