// Daily briefing — multi-day archive.
// BRIEF_ARCHIVE is keyed by ISO date. BRIEF_DATES is newest-first.
// Past days carry slimmer content than today (the showcase day).

// ── Past days (compact)
function pastDay(data) { return data; }

// 아카이브: 2026-05-17
const D_0517 = pastDay({
  iso: '2026-05-17', label: '2026년 5월 17일 일요일', shortLabel: '5월 17일 (일)',
  market: [
    { sym: 'KOSPI',   val: '7,493',   pct: '-6.12%', up: false },
    { sym: 'S&P 500', val: '7,409',   pct: '-1.24%', up: false },
    { sym: 'NASDAQ',  val: '26,225',  pct: '-1.54%', up: false },
    { sym: 'BTC',     val: '$78,200', pct: '-0.90%', up: false },
    { sym: '$/₩',    val: '1,497',   pct: '+0.87%', up: true  },
    { sym: '10Y UST', val: '4.60%',  pct: '+10bp',  up: true  },
    { sym: 'WTI',     val: '$106.50', pct: '+4.97%', up: true  },
  ],
  ai: {
    label: 'AI 뉴스',
    summary: 'Anthropic이 Claude Code 6주 품질 저하의 3가지 원인을 사후 분석으로 공개했고, Stainless 개발 도구 스타트업 $3억 인수를 협상 중입니다. OpenAI는 ChatGPT에 셀프서브 광고 플랫폼을 도입하며 AI 수익화 전략을 전환했고, Meta는 2026년 AI 설비 투자를 전년 대비 2배인 $1,350억으로 확대합니다.',
    items: [
      { weight: 'high', time: '09:00', source: 'Anthropic / InfoQ',
        headline: 'Anthropic, Claude Code 6주 품질 저하 3가지 원인 사후 분석 공개',
        url: 'https://www.infoq.com/news/2026/05/anthropic-claude-code-postmortem/',
        bullets: ['Anthropic, Claude Code 6주간 품질 저하 원인 3가지: 추론 다운그레이드·캐싱 버그·프롬프트 길이 제한.', '3가지 제품 레이어 변경 동시 겹침으로 디버깅 지연. 해당 이슈 수정 완료.', 'Claude Code $14B ARR 핵심 동력 — 투명성 공개로 개발자 신뢰 회복 시도.'],
        why: 'Claude Code는 Anthropic 연간 반복 매출 $140억의 핵심 동력입니다.',
        notes: [{ term: 'Claude Code', def: 'Anthropic의 터미널 기반 AI 코딩 에이전트.' }, { term: '캐싱 버그', def: '이전 대화 내용을 저장해 빠르게 불러오는 캐싱 시스템 오류.' }] },
      { weight: 'high', time: '10:00', source: 'The Information',
        headline: 'Anthropic, 개발 도구 스타트업 Stainless $3억+ 인수 협상 — OpenAI·Google도 사용',
        url: 'https://www.theinformation.com/articles/anthropic-talks-buy-developer-tools-startup-used-openai-google',
        bullets: ['Anthropic, Stainless 인수 협상 중. Stainless는 API SDK 자동 생성 도구. OpenAI·Google도 현재 사용 중.', '인수가 최소 $3억. Claude API 개발자 온보딩 속도 대폭 향상 목적.', 'API 생태계 선점 전략. SDK 표준화로 Claude API 점유율 확대 노림수.'],
        why: 'Anthropic이 OpenAI·Google도 사용하는 도구 회사를 인수하면 API 생태계 주도권을 확보합니다.',
        notes: [{ term: 'API SDK', def: 'AI API를 사용하기 쉽게 감싸주는 코드 라이브러리.' }, { term: 'Stainless', def: 'API SDK 자동 생성 스타트업. OpenAI API SDK도 Stainless로 제작.' }] },
      { weight: 'low', time: '07:00', source: 'OpenAI / The Verge',
        headline: 'OpenAI, ChatGPT 셀프서브 광고 플랫폼 도입 — AI 어시스턴트 수익화 새 전략',
        url: 'https://llm-stats.com/ai-news',
        bullets: ['OpenAI, ChatGPT에 자체 광고 플랫폼(셀프서브 방식) 도입. 광고주가 직접 구매·관리 가능.', 'Anthropic·Google의 구독 중심 모델과 차별화. AI 어시스턴트 광고 수익화 업계 첫 대규모 시도.'],
        why: '', notes: [] },
      { weight: 'low', time: '08:00', source: 'Meta / Bloomberg',
        headline: 'Meta, 2026년 AI 설비 투자 $1,350억 확정 — 전년 대비 2배',
        url: 'https://techdg.in/latest-ai-updates-may-2026-global-ai-news-trends/',
        bullets: ['Meta, 2026년 AI 자본 지출 $1,150~$1,350억 확정. 전년 $720억 대비 최대 2배 확대.', 'Meta AI Muse Spark 모델이 Voice Mode·Meta Glasses 미국·캐나다 구동.'],
        why: '', notes: [] },
      { weight: 'low', time: '06:00', source: 'Anthropic / Bloomberg Law',
        headline: 'Anthropic, 법률 분야 20+ MCP 커넥터·12개 실무 플러그인 공개',
        url: 'https://news.bloomberglaw.com/legal-ops-and-tech/anthropic-pushes-deeper-into-legal-work-with-claude-updates',
        bullets: ['Anthropic, 법률 전용 MCP 커넥터 20개+ 및 실무 플러그인 12종 공개.', '대형 로펌·사내 법무팀 Claude 채택 가속. 법률 AI 시장 Harvey·Westlaw AI와 3파전.'],
        why: '', notes: [] },
      { weight: 'low', time: '11:00', source: 'xAI / SpaceX',
        headline: 'xAI 법인 5월 6일 공식 해체 — SpaceX AI 부문으로 편입',
        url: 'https://medium.com/@mrudulgole/the-week-ai-stopped-pretending-may-11-15-2026-5604151b9153',
        bullets: ['xAI LLC, 5월 6일 공식 해체. SpaceX 산하 SpaceXAI 부문으로 편입 완료.', '조직 통합 후에도 Grok Build·Custom Voices 출시 등 제품 개발 유지.'],
        why: '', notes: [] },
      { weight: 'low', time: '09:30', source: 'Anthropic / InfoWorld',
        headline: 'Anthropic, 에이전트 SDK 6월 15일부터 크레딧 제도 도입',
        url: 'https://www.infoworld.com/article/4171274/anthropic-puts-claude-agents-on-a-meter-across-its-subscriptions.html',
        bullets: ['6월 15일부터 Agent SDK·GitHub Actions·서드파티 프레임워크 사용량 월별 크레딧으로 구독 분리.', 'Pro $20, Max 5x $100, Max 20x $200. 크레딧 소진 시 API 요금 적용.'],
        why: '', notes: [] },
      { weight: 'low', time: '08:30', source: 'Google / Android Authority',
        headline: 'Google I/O 2026 D-2 — Gemini 4.0·Omni 비디오·Android XR 글라스 발표 기대',
        url: 'https://www.androidauthority.com/what-to-expect-from-google-io-2026-3664979/',
        bullets: ['Google I/O 2026 메인 키노트 내일(5/19) 10AM PT. Gemini 4.0 또는 Gemini Omni 비디오 생성 모델 공개 기대.', 'Android XR 글라스·Android 17·Gemini Intelligence 통합 동시 발표 유력.'],
        why: '', notes: [] },
    ],
  },
  physical: {
    label: '피지컬 AI 뉴스',
    summary: 'Figure AI가 생산 속도를 4개월 만에 하루 1대에서 시간당 1대로 60배 향상했습니다. JAL이 하네다공항에 3년 계약으로 휴머노이드를 배치했고, Tesla는 프리몬트 공장 어셈블리 라인을 Optimus 생산용으로 전환 중입니다.',
    items: [
      { weight: 'high', time: '09:00', source: 'Figure AI / The AI Insider',
        headline: 'Figure AI, 생산 속도 하루 1대→시간당 1대 — 4개월 만에 60배 향상',
        url: 'https://theaiinsider.tech/2026/05/01/figure-ai-ramps-up-production-to-one-humanoid-robot-per-hour/',
        bullets: ['Figure AI, Figure 03 휴머노이드 생산 속도 하루 1대→시간당 1대로 4개월 만에 60배 향상.', '전용 어셈블리 라인 + 150개 워크스테이션 맞춤 제조 소프트웨어로 달성.', '연간 생산 가능 대수 8,760대+. 기업 고객 대규모 납품 준비 완료.'],
        why: '생산 속도 60배 향상은 Figure AI가 R&D 기업에서 제조 기업으로 전환됐음을 의미합니다.',
        notes: [{ term: 'Figure 03', def: 'Figure AI의 3세대 휴머노이드 로봇. 물류·제조·상업 환경 배치 최적화.' }] },
      { weight: 'high', time: '10:00', source: 'JAL / CNBC',
        headline: 'JAL, 하네다공항 휴머노이드 로봇 3년 운영 계약 — 항공 최초 장기 상업 배치',
        url: 'https://kraneshares.com/humanoid-robotics-in-2026-the-race-from-pilot-to-platform/',
        bullets: ['Japan Airlines(JAL), 도쿄 하네다공항에 휴머노이드 로봇 3년 운영 계약 공식 체결.', '수하물 처리·지상 조업 보조 역할. 세계 최고 수준 안전 규정 환경의 레거시 항공사 첫 장기 약정.', '3년 계약은 파일럿 단계 졸업 공식 선언. 국제 항공사 벤치마크로 활용 가능성.'],
        why: '레거시 항공사의 3년 계약은 "데모에서 실제 운영"으로의 전환을 확인합니다.',
        notes: [{ term: '지상 조업', def: '항공기 정비·수하물 처리·연료 공급·기내 청소 등 탑승교 아래 모든 작업.' }] },
      { weight: 'low', time: '07:00', source: 'Tesla / Bloomberg',
        headline: 'Tesla, 프리몬트 공장 어셈블리 라인 Optimus 생산용 전환 — Model S·X 생산 종료',
        url: 'https://standardbots.com/blog/tesla-robot',
        bullets: ['Tesla, 캘리포니아 프리몬트 공장 어셈블리 라인을 Optimus Gen 3 생산용으로 전환.', 'Optimus Gen 3 여름 2026 저량 생산 목표. 공장 생산 라인이 Optimus의 첫 실제 고객이 되는 역설.'],
        why: '', notes: [] },
      { weight: 'low', time: '08:00', source: 'Boston Dynamics / Hyundai',
        headline: 'Boston Dynamics Atlas, 현대차 RMAC 전량 납품·Google DeepMind 배치 확정',
        url: 'https://vfuturemedia.com/future-tech/humanoid-robots-enter-the-workforce-figure-boston-dynamics-and-tesla-optimus-2026/',
        bullets: ['Boston Dynamics Atlas 2026 생산 물량 전량 확정: 현대차 로보틱스 메타플랜트(RMAC)·Google DeepMind 배치.', 'VR 텔레오퍼레이션·태블릿 제어·자율 운영 3가지 모드 소프트웨어 완성.'],
        why: '', notes: [] },
      { weight: 'low', time: '06:00', source: 'Meta / PYMNTS',
        headline: 'Meta, ARI 인수 완료 — 가정용 로봇 OS 2027년 라이선스 목표',
        url: 'https://www.pymnts.com/meta/2026/meta-acquires-ari-to-fuel-humanoid-robot-push/',
        bullets: ['Meta, Assured Robot Intelligence(ARI) 인수 완료. 범용 휴머노이드 AI 모델 개발 스타트업.', 'Llama 기반 온디바이스 추론 특화 가정용 로봇 OS 2027년 파트너 라이선스 목표.'],
        why: '', notes: [] },
      { weight: 'low', time: '09:30', source: 'Qualcomm',
        headline: 'Qualcomm, 휴머노이드 전용 프로세서 Dragonwing IQ10 출시',
        url: 'https://humanoid.press/',
        bullets: ['Qualcomm, 휴머노이드 전용 프로세서 Dragonwing IQ10 출시. Figure AI·Neura Robotics와 협력.', '온디바이스 AI 추론 최적화. 배터리 효율 45% 향상. 실시간 센서 퓨전 지원.'],
        why: '', notes: [] },
      { weight: 'low', time: '11:00', source: 'Bessemer Venture Partners',
        headline: 'BVP "휴머노이드는 GPT-2.5 단계" — 99.9% 신뢰성 달성이 폭발 조건',
        url: 'https://kraneshares.com/humanoid-robotics-in-2026-the-race-from-pilot-to-platform/',
        bullets: ['BVP, 2026 피지컬 AI 보고서: "GPT-2.5 단계 — 능력 실재, 확장 법칙 시작, 생산 신뢰성 갭 잔존."', '현재 94~97% 신뢰성 → 99.9% 달성 시 시장 폭발. 3~6개월 연속 무중단 운영 입증이 기준.'],
        why: '', notes: [] },
      { weight: 'low', time: '10:30', source: 'Merics',
        headline: '중국 Embodied AI 2030년 100만 대 — Unitree $15,400 vs 미국 $30,000',
        url: 'https://merics.org/en/report/embodied-ai-chinas-ambitious-path-transform-its-robotics-industry',
        bullets: ['중국, 정부 주도 Embodied AI 2030년 100만 대 목표. UBTECH·Unitree·Xiaomi 국가 보조 수혜.', 'Unitree G1 $15,400 vs 미국 $25,000~$30,000. 가격 경쟁이 글로벌 휴머노이드 시장 최대 변수.'],
        why: '', notes: [] },
    ],
  },
  quantum: {
    label: '양자 뉴스',
    summary: 'Google이 $1,000만 REPLIQA 양자 생물학 연구 이니셔티브를 출범했고, IonQ가 Q1 매출 $64.7M(+755% YoY)을 발표했습니다. 유럽 JUPITER 슈퍼컴퓨터가 50큐비트 양자 시뮬레이션 세계 기록을 경신했습니다.',
    items: [
      { weight: 'high', time: '10:00', source: 'Google Quantum AI',
        headline: 'Google, $1,000만 REPLIQA 양자 생물학 이니셔티브 출범',
        url: 'https://thequantuminsider.com/2026/05/14/google-launches-10-million-quantum-biology-research-initiative/',
        bullets: ['Google, REPLIQA 프로그램 출범. 5개 대학에 $1,000만 지원. 양자 컴퓨팅·센싱·AI 통합으로 생물학·의학 연구.', '단백질 접힘 분자 시뮬레이션·양자 강화 AI 알고리즘 등 기초 연구 초점.', '2026년 7월 Quantum Computing Report Summit에서 세부 연구 계획 발표 예정.'],
        why: '생물학 분야 양자 우위 실현은 신약 개발 파이프라인 혁신으로 직결됩니다.',
        notes: [{ term: 'REPLIQA', def: 'Google Quantum AI의 생물학 연구 이니셔티브. 양자 기술로 생물 시스템 모델링 목표.' }] },
      { weight: 'high', time: '08:00', source: 'IonQ',
        headline: 'IonQ Q1 매출 $64.7M +755% — 2026년 가이던스 $260~270M 상향',
        url: 'https://thequantuminsider.com/2026/05/06/ionq-reports-64-7-million-q1-2026-revenue-fueled-by-quantum-contracts-and-system-sales/',
        bullets: ['IonQ, Q1 2026 매출 $64.7M(전년 동기 $7.6M, +755% YoY). 2026 연간 가이던스 $260~270M 상향.', '케임브리지대 256큐비트 시스템 판매. 폴란드·플로리다 양자 네트워킹 프로젝트.', '볼더 $1억 R&D 연구소 개소(5/12). 이온트랩 반도체 칩 설계·테스트 집중.'],
        why: '연간 매출 755% 성장과 가이던스 상향은 양자 컴퓨팅이 상업 단계에 진입했음을 증명합니다.',
        notes: [{ term: 'RPO(수주잔고)', def: '아직 인식되지 않은 계약 매출. IonQ RPO $470M = 미래 매출 예측 가시성.' }] },
      { weight: 'low', time: '07:00', source: 'ScienceDaily',
        headline: 'JUPITER 슈퍼컴퓨터, 50큐비트 양자 시뮬레이션 세계 기록',
        url: 'https://www.sciencedaily.com/releases/2026/05/260510234715.htm',
        bullets: ['유럽 엑사스케일 슈퍼컴퓨터 JUPITER, 50큐비트 양자컴퓨터 완전 시뮬레이션 세계 기록. 이전 기록 48큐비트 경신.', 'IBM·Google 양자컴퓨터 성능 벤치마크 기준점 상향.'],
        why: '', notes: [] },
      { weight: 'low', time: '06:00', source: 'ScienceDaily / Japan',
        headline: '일본 연구팀, 120km 해킹 불가 양자 키 전송 성공',
        url: 'https://www.sciencedaily.com/releases/2026/05/260508003129.htm',
        bullets: ['일본 연구팀, 기존 광섬유 케이블로 120km 양자 암호 키 전송 성공.', '도시 간 양자 암호 통신 인프라 현실화 가능성. 금융·정부 기관 관심 집중.'],
        why: '', notes: [] },
      { weight: 'low', time: '09:00', source: 'IonQ / Q-CTRL',
        headline: 'IonQ·Q-CTRL, Fire Opal 통합 — IonQ 클라우드 오류 억제 자동화',
        url: 'https://www.ionq.com/news',
        bullets: ['IonQ와 Q-CTRL, Fire Opal 소프트웨어를 IonQ Quantum Cloud에 통합 발표.', '오류 억제·문제 매핑 자동화. AWS·Azure·Google Cloud 전 채널 적용.'],
        why: '', notes: [] },
      { weight: 'low', time: '08:30', source: 'Quantinuum',
        headline: 'Quantinuum, IPO S-1 공개 — 2025년 순매출 $30.9M',
        url: 'https://quantumcomputingreport.com/news/',
        bullets: ['Quantinuum, IPO를 위한 예비 S-1 공개. 2025년 순매출 $30.9M, 순손실 $192.6M.', 'BMW그룹과 다년 파트너십 확대: 연료전지·배터리 재료 양자 시뮬레이션 협력.'],
        why: '', notes: [] },
      { weight: 'low', time: '11:00', source: 'NYU / IBM',
        headline: 'NYU·IBM, 양자 컴퓨팅 공동 박사후 연구 프로그램 설립',
        url: 'https://quantumcomputingreport.com/news/',
        bullets: ['NYU와 IBM, 양자 컴퓨팅 응용 공동 박사후 연구 프로그램 설립.', '양자-클래식 하이브리드 알고리즘 개발·최적화 집중. 학계-산업 인재 파이프라인 구축.'],
        why: '', notes: [] },
      { weight: 'low', time: '10:30', source: 'Microsoft / Atom Computing',
        headline: 'Microsoft·Atom Computing, 50 논리 큐비트 Magne 시스템 납품 계약',
        url: 'https://quantumcomputingreport.com/news/',
        bullets: ['Microsoft와 Atom Computing, 덴마크에 Magne(50 논리 큐비트, 물리 큐비트 1,200개) 납품 계약.', '오류수정 양자컴퓨터 최초 상업 납품 사례. 2027년 초 인도 예정.'],
        why: '', notes: [] },
    ],
  },
  econ: {
    label: '경제 뉴스',
    summary: 'KOSPI 8,000 돌파 후 -6.12% 급락 충격이 주말을 거치며 분석되고 있습니다. 케빈 워시 연준 의장 취임 첫 주를 마치며 금리 인하 기대가 완전히 소멸됐고, WTI가 $106대를 유지하며 에너지 인플레가 지속되고 있습니다.',
    items: [
      { weight: 'high', time: '15:00', source: 'Bloomberg / CNBC',
        headline: '주말 시장 총결산: KOSPI -6.12%·S&P -1.24%·WTI $106 — 스태그플레이션 공포',
        url: 'https://sundayguardianlive.com/business/us-stock-market-today-15-may-2026-dow-falls-nasdaq-sp-500-crash-after-trump-china-visit-oil-surges-109-on-us-iran-deal-gold-silver-hit-bitcoin-retreats-82k-what-investors-should-watch-192641/',
        bullets: ['KOSPI 8,000 돌파 당일 -6.12% 급락(7,493). S&P -1.24%, NASDAQ -1.54%. WTI +4.97% $106대 유지.', '삼중 충격: 트럼프-시 회담 성과 미미·이란 협상 결렬·케빈 워시 연준 고금리 장기화.', '분석가 컨센서스: 5월 19일 Google I/O 결과가 기술주 단기 방향 결정 키.'],
        why: '스태그플레이션 시나리오 현실화 시 연준은 경기 둔화와 물가 상승 딜레마에 직면합니다.',
        notes: [{ term: '스태그플레이션', def: '경기침체(Stagnation)+인플레이션(Inflation) 동시 발생. 연준 최악 시나리오.' }] },
      { weight: 'high', time: '10:00', source: '뉴스핌 / Bloomberg',
        headline: '케빈 워시 연준 취임 첫 주 — "금리 인하 물 건너갔다" 시장 반응',
        url: 'https://www.newspim.com/news/view/20260515000026',
        bullets: ['워시 연준 의장 취임 첫 주 마감. 10Y UST 4.60%·WTI $106 동반 상승에 연내 금리 인하 가능성 사실상 소멸.', '"물가 2% 달성 전 인하 불가" 워시 원칙 재확인. 6월 16-17일 첫 FOMC까지 3주 주목.', 'CME FedWatch 6월 동결 94%. 연내 인상 가능성 12%로 상승. 2027년 첫 인하 컨센서스.'],
        why: '워시 취임 + 에너지 쇼크의 조합은 연내 금리 인하 기대를 완전히 소멸시킵니다.',
        notes: [{ term: '케빈 워시', def: '제17대 연준 의장. 트럼프 지명. 파월보다 매파적으로 평가.' }] },
      { weight: 'low', time: '08:00', source: 'Reuters / CNBC',
        headline: 'WTI $106대 유지 — 이란 호르무즈 재긴장, 에너지 인플레 장기화',
        url: '',
        bullets: ['WTI $106.50. 트럼프-시 회담 이란 의제 미해결로 호르무즈 해협 긴장 지속. 브렌트유 $110 근접.', '에너지 인플레 장기화 시 미 CPI 3.5%+ 유지 → 워시 연준 금리 인상 강제 시나리오.'],
        why: '', notes: [] },
      { weight: 'low', time: '07:00', source: 'CoinDesk',
        headline: 'BTC $78,200 주말 유지 — $75K 지지선·리스크오프 환경',
        url: 'https://www.coindesk.com/markets/2026/05/15/bitcoin-tumbles-below-usd79-000-as-rising-bond-yields-inflation-worries-rattle-markets',
        bullets: ['BTC $78,200(-0.90%) 주말 소폭 하락 유지.', '$75,000 지지선 돌파 여부 주목.'],
        why: '', notes: [] },
      { weight: 'low', time: '09:00', source: '연합뉴스',
        headline: '삼성전자 반도체 파업 D-4 — 5월 21일 HBM 공급망 위기',
        url: '',
        bullets: ['삼성전자 최대 노조, 5월 21일 18일 총파업. 반도체 부문 45,000명 참여 예정.', 'HBM4 생산 라인 포함 시 NVIDIA·AMD 납품 일정 차질. SK하이닉스 반사이익.'],
        why: '', notes: [] },
      { weight: 'low', time: '06:00', source: '한국은행',
        headline: '원/달러 1,497원 — 1,500원 심리적 저항선 근접',
        url: '',
        bullets: ['원달러 1,497원(+0.87%). 이란 불확실성 달러 강세·KOSPI 급락 외국인 매도 복합 영향.', '1,500원 심리적 저항선 근접. 한국은행 환율 개입 경계심 고조.'],
        why: '', notes: [] },
      { weight: 'low', time: '11:00', source: 'KDI / 한국은행',
        headline: '한국 경제 5월 주간 점검 — 반도체 AI 수출 견조, 내수 제한적',
        url: '',
        bullets: ['KDI 5월 주간 경제 점검. 반도체·AI 수출은 견조하나 KOSPI -6.12% 충격·파업 변수 내수 심리 위축 우려.', '2026년 성장률 2.5% 전망 유지 조건: 삼성 파업 조기 종결·이란 리스크 완화 필수.'],
        why: '', notes: [] },
      { weight: 'low', time: '14:00', source: 'CNBC / TheStreet',
        headline: 'Google I/O·NVIDIA 실적 이번 주 핵심 이벤트 — 기술주 반등 트리거 가능성',
        url: 'https://www.cnbc.com/2026/05/14/stock-market-today-live-updates.html',
        bullets: ['이번 주 최대 이벤트: Google I/O 2026(5/19)·NVIDIA 실적(5/20). Gemini 4.0·데이터센터 가이던스 핵심.', '두 이벤트 동반 서프라이즈 시 KOSPI 반등 트리거. 실망 시 KOSPI 7,000선 붕괴 위험.'],
        why: '', notes: [] },
    ],
  },
  columns: {
    label: '컬럼 피드',
    summary: '오건영 단장은 지난 금요일 KOSPI 급락의 배경으로 주식-채권 디커플링을 분석했습니다. 에너지주 같은 인플레이션 헤지 자산의 역할을 설명하며 Google I/O·NVIDIA 실적이 이번 주 핵심 이벤트라고 강조했습니다.',
    items: [
      { name: '오건영', title: '신한은행 · 디지털 크리에이터', avatar: 'OG', color: '#D97757',
        time: '5월 17일 08:00', likes: 717, comments: 33,
        post: '주말 에세이 바로 시작합니다. 지난 금요일 주식 시장이 긴장하는 모습을 보였죠. 상승세가 가팔랐던 코스피 지수의 하락세가 전세계적으로 두드러졌구요... 그 중심에는 금리 급등이라는 이슈가 있었죠. 주식과 채권의 디커플링이라는 관점에서 생각해보면 어떨까 합니다. 전쟁이 끝나지도 않았는데 주식 시장이 강세를 이어가고 있죠. 에너지 주식들처럼 인플레이션을 헤지할 수 있는 자산들도 있을 겁니다. 다음 주 Google I/O와 NVIDIA 실적이 기술주 방향을 결정할 핵심 이벤트입니다.',
        summary: '주식-채권 디커플링 관점에서 KOSPI 급락 분석. 에너지주 등 인플레이션 헤지 자산 역할 강조.',
      },
    ],
  },
  invest: {
    title: '트리플 약세 속 방어 전략',
    subtitle: 'Claude가 작성한 오늘의 메모 · 5월 17일 09:00 · 5분 읽기',
    sections: [
      { h: '한 줄 요약', body: 'KOSPI 8,000 돌파 당일 -6.12% 급락 충격이 주말을 거치며 스태그플레이션 시나리오로 굳어지고 있습니다.' },
      { h: '오늘의 변수', body: 'Google I/O 2026(5/19)·NVIDIA 실적(5/20)·삼성전자 파업(5/21)·이란 협상 동향.' },
      { h: '포지셔닝', body: '단기: 국내 반도체주 비중 축소. 금(GLD) 30% 최대화. 배당주(VYM) 20% 확대. 중기: Google I/O 서프라이즈 확인 후 Alphabet 편입.' },
      { h: '리스크', body: 'WTI $115+ 에너지 인플레 재점화. 삼성 파업 장기화. Google I/O 기대 미충족. BTC $75K 지지선 붕괴.' },
    ],
    watchlist: [
      { sym: '000660', name: 'SK하이닉스',  val: '1,942,910', pct: '-3.00%', up: false, note: 'H200 수출 수혜 but 삼성 파업 D-4' },
      { sym: '005930', name: '삼성전자',    val: '282,500',   pct: '-4.39%', up: false, note: '파업 D-4 + AI 집중 리스크' },
      { sym: 'NVDA',   name: 'NVIDIA',      val: '$220.90',   pct: '-4.45%', up: false, note: '5/20 실적 발표 — 데이터센터 가이던스 핵심' },
      { sym: 'GOOGL',  name: 'Alphabet',    val: '$196.30',   pct: '-1.23%', up: false, note: 'I/O 2026(5/19) Gemini 4.0 기대' },
      { sym: 'TLT',    name: 'iShares 20Y', val: '$88.15',    pct: '-1.51%', up: false, note: '10Y 4.60% 추세 — 채권 추가 조정' },
      { sym: 'GLD',    name: 'SPDR Gold',   val: '$252.80',   pct: '+0.40%', up: true,  note: '트리플 약세 속 유일한 방어 자산' },
      { sym: 'VYM',    name: 'Vanguard HY', val: '$131.34',   pct: '-0.80%', up: false, note: '고금리 장기화 — 배당주 상대 강세 유지' },
      { sym: 'BTC',    name: 'Bitcoin',     val: '$78,200',   pct: '-0.90%', up: false, note: '주말 소폭 하락 — $75K 지지선 모니터링' },
    ],
    portfolio: [
      { asset: '국내주식', pct: 15, color: '#3DDC97', tickers: [{ sym: '000660', name: 'SK하이닉스' }, { sym: '005930', name: '삼성전자' }], note: '파업 리스크 반영 비중 축소' },
      { asset: '미국주식', pct: 20, color: '#5B9BD5', tickers: [{ sym: 'NVDA', name: 'NVIDIA' }, { sym: 'GOOGL', name: 'Alphabet' }], note: 'I/O·실적 확인 후 판단, 관망' },
      { asset: '채권',    pct: 5,  color: '#9B8EC4', tickers: [{ sym: 'TLT', name: 'iShares 20Y ETF' }], note: '워시 매파 기조 — 최소화' },
      { asset: '금',      pct: 30, color: '#F5C518', tickers: [{ sym: 'GLD', name: 'SPDR Gold ETF' }], note: '이란·인플레·고금리 3중 헤지 핵심' },
      { asset: '배당주',  pct: 20, color: '#E08A6E', tickers: [{ sym: 'VYM', name: 'Vanguard High Div.' }], note: '리스크오프 + 고금리 — 안정 수익' },
      { asset: '비트코인', pct: 10, color: '#F7931A', tickers: [{ sym: 'BTC', name: 'Bitcoin' }], note: '$75K 지지선 모니터링' },
    ],
  },
});


const TODAY = {
  date: { iso: '2026-05-18', label: '2026년 5월 18일 월요일', shortLabel: '5월 18일 (월)', isToday: true },
  marketStrip: [
    { sym: 'KOSPI',   val: '7,493',   pct: '-6.12%', up: false },
    { sym: 'S&P 500', val: '7,409',   pct: '-1.24%', up: false },
    { sym: 'NASDAQ',  val: '26,225',  pct: '-1.54%', up: false },
    { sym: 'BTC',     val: '$78,028', pct: '-0.22%', up: false },
    { sym: '$/₩',    val: '1,497',   pct: '+0.87%', up: true  },
    { sym: '10Y UST', val: '4.60%',  pct: '+10bp',  up: true  },
    { sym: 'WTI',     val: '$106.50', pct: '+4.97%', up: true  },
  ],
  ai: {
    label: 'AI 뉴스',
    summary: 'Google I/O 2026이 내일 개막하며 Gemini 4.0·Android XR·Aluminum OS 발표가 예상됩니다. OpenAI는 ChatGPT·Codex·API를 통합한 슈퍼앱 전략으로 ARR $250억을 돌파했고, Anthropic은 Claude Opus 4.7을 출시해 수학 벤치마크 1위를 기록했습니다.',
    items: [
      { weight: 'high', time: '08:00', source: 'Google / Android Authority',
        headline: 'Google I/O 2026 D-1 — 내일 키노트, Gemini 4.0·Android XR 글라스·Aluminum OS 기대',
        url: 'https://www.androidauthority.com/what-to-expect-from-google-io-2026-3664979/',
        bullets: [
          'Google I/O 2026 메인 키노트 내일(5/19) 10AM PT. Gemini 4.0 또는 Gemini 3.2 Flash 발표 유력.',
          '통합 멀티모달 Gemini Omni 비디오 생성 모델 첫 공개 기대. Android XR 글라스·Android 17·Aluminum OS 동시 발표.',
          '삼성·Warby Parker·Gentle Monster 공동 개발 XR 글라스 사전 공개 예정. AI 업계 최대 이벤트 D-1.',
        ],
        why: 'Google I/O는 AI 업계 연간 최대 이벤트입니다. Gemini 발표 내용에 따라 Alphabet 주가와 AI 경쟁 구도 전체가 재편될 수 있습니다.',
        notes: [
          { term: 'Gemini Omni', def: '구글이 개발 중인 통합 멀티모달 AI 모델. 텍스트·이미지·음성·영상을 하나의 모델에서 처리. Gemini 인터페이스 내에서 직접 비디오 생성 가능.' },
          { term: 'Aluminum OS', def: 'Android와 ChromeOS를 통합한 구글의 새 운영체제. 데스크탑·모바일·XR 환경 통합 지원.' },
        ] },
      { weight: 'high', time: '07:00', source: 'OpenAI / TechCrunch',
        headline: 'OpenAI, ChatGPT·Codex·API "슈퍼앱" 통합 — ARR $250억 돌파, IPO 준비 가속',
        url: 'https://techcrunch.com/2026/05/05/openai-releases-gpt-5-5-instant-a-new-default-model-for-chatgpt/',
        bullets: [
          'OpenAI, ChatGPT·Codex·개발자 API를 단일 팀으로 통합. Codex 총괄 Thibault Sottiaux 리더십. Atlas 브라우저 통합 슈퍼앱 목표.',
          'OpenAI ARR(연간 반복 매출) $250억 돌파 공식 확인. 2026년 말 IPO 검토 가속화.',
          'GPT-5.5 Instant을 ChatGPT 기본 모델로 교체. 법률·의학·금융 환각 감소 특화.',
        ],
        why: 'OpenAI ARR $250억 돌파와 IPO 준비는 AI 산업의 수익화 단계 진입을 확인합니다. Anthropic의 $950억 밸류에이션과 경쟁 구도가 더욱 선명해집니다.',
        notes: [
          { term: 'ARR', def: 'Annual Recurring Revenue(연간 반복 매출). 구독·API 과금 기반 예측 가능 매출. AI 기업 성장 지표.' },
          { term: '슈퍼앱', def: '하나의 앱에서 메시지·결제·AI·브라우저 등 다수 기능 제공. 카카오·위챗 모델을 AI로 재구현하는 전략.' },
        ] },
      { weight: 'high', time: '09:00', source: 'Anthropic',
        headline: 'Anthropic, Claude Opus 4.7 출시 — 수학 벤치마크 1위, Microsoft·NVIDIA 전략 파트너십',
        url: 'https://www.anthropic.com/news/claude-opus-4-7',
        bullets: [
          'Anthropic, Claude Opus 4.7 공개. LLM Stats 수학 벤치마크 1위(61.7점). Claude Sonnet 4.6은 코딩 리더보드 2위(1190점).',
          'Microsoft와 $300억 Azure 컴퓨팅 파트너십·NVIDIA와 공동 로드맵 체결. SpaceX Colossus 1 딜(300MW·22만 GPU)로 사용 한도 2배 확대.',
          'PwC 36만 명 전사 배포·게이츠재단 $2억 파트너십 동시 발표. Anthropic 기업 생태계 확장 가속.',
        ],
        why: 'Claude Opus 4.7의 수학 벤치마크 1위는 Anthropic이 과학·금융 분야 AI 리더십을 노린다는 신호입니다. Microsoft·NVIDIA 파트너십은 기업 시장 점유율 확대 전략.',
        notes: [
          { term: 'Claude Opus 4.7', def: 'Anthropic의 최신 플래그십 모델. Claude Mythos(보안 특화) 이후 범용 모델. 수학·추론·코딩 균형 강점.' },
          { term: 'LLM Stats', def: 'AI 모델 성능을 다양한 벤치마크로 순위화하는 독립 평가 플랫폼. 코딩·수학·이미지 분야별 리더보드 운영.' },
        ] },
      { weight: 'low', time: '06:00', source: 'Anthropic / Fortune',
        headline: 'Anthropic, PwC 36만 명 전사 Claude 배포 — Claude Code 3만 명 인증 프로그램',
        url: 'https://www.anthropic.com/news/pwc-expanded-partnership',
        bullets: [
          'PwC, 미국 직원 3만 명 Claude Code 인증 후 글로벌 36만 4,000명 전사 배포 계획.',
          '기술 구축·M&A 실행·기업 기능 혁신에 Claude 활용. 기업 AI 채택 최대 규모 사례.',
        ], why: '', notes: [] },
      { weight: 'low', time: '10:00', source: 'Anthropic / Gates Foundation',
        headline: 'Anthropic, 게이츠재단 $2억 파트너십 — 글로벌 헬스·교육 AI 지원',
        url: 'https://www.anthropic.com/news/gates-foundation-partnership',
        bullets: [
          'Anthropic, 게이츠재단과 4년간 $2억 규모 파트너십. 보조금·Claude 이용권·기술 지원 포함.',
          '글로벌 헬스·생명과학·교육·경제 이동성 분야. AI의 사회적 임팩트 확대.',
        ], why: '', notes: [] },
      { weight: 'low', time: '08:30', source: 'CNN / Pentagon',
        headline: 'Anthropic, 국방부 AI 딜 제외 — 군사 안전가드 거부 vs 8개사 Pentagon 계약',
        url: 'https://www.cnn.com/2026/05/01/tech/pentagon-ai-anthropic',
        bullets: [
          '국방부, SpaceX·OpenAI·Google·Microsoft·NVIDIA·AWS·Oracle·Reflection 8개사 군 기밀망 AI 계약 체결.',
          'Anthropic 제외 — 군사 AI 안전가드 포함 요구로 트럼프 행정부와 갈등.',
        ], why: '', notes: [] },
      { weight: 'low', time: '11:00', source: 'OpenAI',
        headline: 'OpenAI, GPT-5.5-Cyber 제한 preview 출시 — 취약점 분석·레드팀 전문',
        url: 'https://openai.com/news/',
        bullets: [
          'OpenAI, 사이버보안 전문 GPT-5.5-Cyber 제한 preview 공개. 취약점 분류·악성코드 분석·패치 검증 특화.',
          'Anthropic Mythos 대항마. 정부·보안기관 Trusted Access 프로그램 확대.',
        ], why: '', notes: [] },
      { weight: 'low', time: '07:30', source: 'Meta / Bloomberg',
        headline: 'Meta, Superintelligence Labs 첫 모델 Muse Spark 출시 — 멀티모달·에이전트 특화',
        url: 'https://techdg.in/latest-ai-updates-may-2026-global-ai-news-trends/',
        bullets: [
          'Meta Superintelligence Labs(수석 AI 책임자 Alexandr Wang), 첫 LLM Muse Spark 공개.',
          '멀티모달 인식·추론·헬스·에이전틱 작업 특화. GPT-5.5 대비 낮은 컴퓨팅으로 경쟁 성능.',
        ], why: '', notes: [] },
    ],
  },
  physical: {
    label: '피지컬 AI 뉴스',
    summary: 'NVIDIA가 GR00T N1.6 오픈소스 휴머노이드 VLA 모델을 출시해 로봇 AI 개발 진입 장벽을 낮췄고, Unitree Robotics가 상하이 STAR 시장 IPO를 신청해 휴머노이드 업계 첫 상장을 노립니다. 중국 UBTECH는 기업 고객 200개사를 돌파했습니다.',
    items: [
      { weight: 'high', time: '09:00', source: 'NVIDIA',
        headline: 'NVIDIA, GR00T N1.6 오픈소스 VLA 모델 출시 — 휴머노이드 전신 제어 개방',
        url: 'https://nvidianews.nvidia.com/news/nvidia-releases-new-physical-ai-models-as-global-partners-unveil-next-generation-robots',
        bullets: [
          'NVIDIA, Isaac GR00T N1.6 공개. 오픈소스 추론 비전-언어-행동(VLA) 모델. 휴머노이드 로봇 전신 제어 지원.',
          '글로벌 파트너(Figure·1X·Agility·Boston Dynamics) 동시 차세대 로봇 발표. 개발 진입 장벽 대폭 낮춤.',
          '제조·물류·연구 환경 범용 배포 가능. CUDA 생태계 전략의 피지컬 AI 재현.',
        ],
        why: 'NVIDIA의 오픈소스 VLA 공개는 로봇 소프트웨어 인프라를 표준화해 "GPU가 곧 로봇 두뇌"라는 생태계를 구축합니다.',
        notes: [
          { term: 'VLA(Vision-Language-Action)', def: '시각·언어·행동을 통합 처리하는 AI 모델. 로봇이 자연어 명령을 직접 실행 가능하게 함.' },
          { term: 'GR00T N1.6', def: 'NVIDIA의 휴머노이드 로봇용 기반 모델. 다양한 로봇 하드웨어에 공통 적용 가능한 범용 AI 뇌.' },
        ] },
      { weight: 'high', time: '08:00', source: 'Unitree / Reuters',
        headline: 'Unitree Robotics, 상하이 STAR 시장 IPO 신청 — $6.1억 조달·$70억 기업가치 목표',
        url: 'https://kraneshares.com/humanoid-robotics-in-2026-the-race-from-pilot-to-platform/',
        bullets: [
          'Unitree Robotics, 상하이 STAR 시장 IPO 신청. 42억 위안($6.1억) 조달·기업가치 $70억 목표.',
          '휴머노이드 업계 첫 흑자 실증. G1 모델 $15,400 — 미국 경쟁사($25~30K) 대비 절반 가격.',
          'STAR 시장 승인 후 6개월 내 상장 예정. 중국 정부 보조금 수혜 기업 상장 첫 사례.',
        ],
        why: '휴머노이드 업계 첫 IPO는 로봇 섹터 밸류에이션 기준점을 설정합니다. Unitree 상장가가 Figure AI·1X 등 비상장 기업의 암묵적 평가 척도가 됩니다.',
        notes: [
          { term: 'STAR 시장', def: '중국 상하이 증권거래소 하이테크 기업 전용 시장. 미국 NASDAQ 유사. AI·반도체·바이오 기업 상장 선호 코스.' },
        ] },
      { weight: 'low', time: '07:00', source: 'Agility Robotics / Amazon',
        headline: 'Agility Digit, Amazon 물류 10개 센터 추가 배치 — 누적 40개 이상',
        url: 'https://www.artificialintelligence-news.com/news/physical-ai-humanoid-robots-factories/',
        bullets: [
          'Agility Robotics Digit 휴머노이드, Amazon 물류센터 추가 10개 확대. 누적 40개+ 센터 배치.',
          '창고 정리·상자 이동·분류 작업 자율 수행. 야간 무인 운영 확대.',
        ], why: '', notes: [] },
      { weight: 'low', time: '06:00', source: 'Tesla / CNBC',
        headline: 'Tesla Optimus Gen 3, 프리몬트 라인 전환 완료 — 여름 저량 생산 본격화',
        url: 'https://standardbots.com/blog/tesla-robot',
        bullets: [
          'Tesla 프리몬트 공장 Optimus Gen 3 생산 라인 전환 최종 단계. Model S·X 단종 확정.',
          '2026년 여름 저량 생산 목표. 공장 자체가 첫 고객이 되는 역설적 배치.',
        ], why: '', notes: [] },
      { weight: 'low', time: '10:00', source: '1X Technologies',
        headline: '1X Technologies NEO, 가정용 소비자 프리오더 개시 — 유럽·미국 대상',
        url: 'https://humanoid.press/',
        bullets: [
          '노르웨이 1X Technologies, 가정용 NEO 휴머노이드 프리오더 유럽·미국 개시.',
          '기업 전용에서 소비자 시장으로 첫 확장. 가격 미공개, 출하 2027년 예정.',
        ], why: '', notes: [] },
      { weight: 'low', time: '11:00', source: 'IEEE / KraneShares',
        headline: '2026 IEEE 휴머노이드 콘퍼런스 11월 개최 — "GPT 모멘트" 논의 예정',
        url: 'https://www.aiexpertmagazine.com/2026-ieee-ras-25th-international-conference-on-humanoid-robots-humanoids-2026-everything-you-need-to-know/',
        bullets: [
          '2026 IEEE-RAS 25회 국제 휴머노이드 로봇 콘퍼런스 11월 개최 확정.',
          '주요 의제: 피지컬 AI 구현 조건, 생산 신뢰성 99.9% 달성 경로.',
        ], why: '', notes: [] },
      { weight: 'low', time: '08:30', source: 'Automate.org',
        headline: '휴머노이드 대중 채택 3대 장벽 — 신뢰성·안전·가격 분석',
        url: 'https://www.automate.org/blogs/what-hurdles-remain-for-widespread-humanoid-adoption',
        bullets: [
          '산업 자동화 협회, 휴머노이드 대중화 3대 장벽: ①99.9% 신뢰성 미달 ②공장 외 안전 인증 부재 ③$15K 이하 가격 임계치.',
          '현재 94-97% 신뢰성 → 목표 99.9%까지 약 12-18개월 필요.',
        ], why: '', notes: [] },
      { weight: 'low', time: '09:30', source: 'Merics / UBTECH',
        headline: '중국 UBTECH, 기업 고객 200개사 돌파 — Embodied AI 투자 최고조',
        url: 'https://merics.org/en/report/embodied-ai-chinas-ambitious-path-transform-its-robotics-industry',
        bullets: [
          '중국 UBTECH Robotics, 기업 고객 200개사 돌파. Anta Sports·BYD·CNOOC 등 대기업 포함.',
          '중국 정부 "2030년 100만 대" 목표 추진 중. 국가 보조금 수혜 기업 올해 생산 가속.',
        ], why: '', notes: [] },
    ],
  },
  quantum: {
    label: '양자 뉴스',
    summary: 'CNN이 구글의 양자 컴퓨터 암호화 해킹 경고(2029년 Q-Day)를 심층 보도했고, Equal1이 표준 데이터센터 랙에 설치 가능한 양자컴퓨터 RacQ를 출시했습니다. IonQ는 플로리다 100마일 양자 통신망 구축을 시작했습니다.',
    items: [
      { weight: 'high', time: '10:00', source: 'CNN',
        headline: 'CNN: 양자 컴퓨터, 2029년 암호화 해킹 가능 — 구글 "Q-Day" 경고, 기업 준비 촉구',
        url: 'https://us.cnn.com/2026/05/17/science/quantum-computing-cybersecurity-q-day',
        bullets: [
          'CNN 심층 보도: 구글, 양자컴퓨터가 2029년까지 일부 암호화 시스템 해킹 가능 경고. Q-Day 대비 창이 좁아지는 중.',
          'RSA·ECC 등 현재 표준 암호화 프로토콜이 양자 공격에 취약. 금융·정부·의료 데이터 위험.',
          'NIST 양자 내성 암호 표준화 완료됐지만 기업 전환율 12%에 불과. 준비 격차 심각.',
        ],
        why: 'Q-Day는 현재 인터넷 보안 인프라 전체를 재구축해야 하는 사건입니다. 2029년까지 3년의 준비 기간 — 사이버 보안 ETF·양자 암호 기업 투자 기회.',
        notes: [
          { term: 'Q-Day', def: '양자컴퓨터가 현재 암호화 표준(RSA·ECC)을 실질적으로 해독할 수 있는 날. 도달 시 인터넷 보안 인프라 전면 교체 필요.' },
          { term: 'NIST 양자 내성 암호', def: '양자공격을 견딜 수 있도록 표준화한 새 암호 알고리즘. CRYSTALS-Kyber 등. 기업은 지금부터 전환 준비 필요.' },
        ] },
      { weight: 'high', time: '08:00', source: 'Equal1',
        headline: 'Equal1, RacQ 랙 마운트 양자컴퓨터 출시 — 데이터센터 표준 랙 통합',
        url: 'https://thequantuminsider.com/',
        bullets: [
          'Equal1, RacQ 출시. UnityQ SoC 기반 실리콘-스핀 양자컴퓨터. 표준 데이터센터 랙에 설치 가능.',
          '클래식 하드웨어와 나란히 운영. 별도 극저온 실험실 불필요 — 운영 비용 혁신.',
          'AWS·Azure·Google Cloud 데이터센터 직접 배치 가능. 양자 클라우드 인프라 민주화.',
        ],
        why: '기존 데이터센터 인프라에 통합 가능한 양자컴퓨터는 기업 채택 장벽을 획기적으로 낮춥니다.',
        notes: [
          { term: '실리콘-스핀 큐비트', def: '반도체 제조 공정으로 만드는 양자비트 방식. CMOS 공정과 호환 가능해 대량 생산·소형화 유리.' },
        ] },
      { weight: 'low', time: '07:00', source: 'IonQ / Florida LambdaRail',
        headline: 'IonQ·Florida LambdaRail, 팜비치~마이애미 100마일 양자 통신망 착공',
        url: 'https://www.ionq.com/news',
        bullets: [
          'IonQ와 Florida LambdaRail, 팜비치~마이애미 100마일 QKD(양자 키 분배) 통신망 구축 착공.',
          '해킹 불가 통신 인프라. 금융·의료·정부 기관 대상 상업 서비스 2027년 예정.',
        ], why: '', notes: [] },
      { weight: 'low', time: '06:00', source: 'IBM',
        headline: 'IBM, 차세대 Starling 양자 시스템 공장 확장 — 포킵시 51만 sq ft, 200개 일자리',
        url: 'https://quantumcomputingreport.com/news/',
        bullets: [
          'IBM, 뉴욕 포킵시 캠퍼스 51만 1천 sq ft 확장. 차세대 Starling 양자 시스템 제조·조립.',
          'Starling 2029년 출시 예정. 200개 일자리 창출.',
        ], why: '', notes: [] },
      { weight: 'low', time: '09:00', source: 'ScienceDaily',
        headline: '신 양자 알고리즘, "불가능" 준결정체 시뮬레이션 해결',
        url: 'https://www.sciencedaily.com/releases/2026/05/260512202355.htm',
        bullets: [
          '새 양자 영감 알고리즘, 기존 슈퍼컴퓨터가 접근 불가했던 준결정체 복잡 양자 재료 시뮬레이션 성공.',
          '신약 개발·배터리·촉매 소재 연구에 직접 응용 가능.',
        ], why: '', notes: [] },
      { weight: 'low', time: '08:30', source: 'Quantinuum / BMW',
        headline: 'Quantinuum·BMW, 다년 파트너십 확장 — 배터리·연료전지 재료 양자 시뮬레이션',
        url: 'https://quantumcomputingreport.com/news/',
        bullets: [
          'Quantinuum, BMW그룹과 다년 파트너십 확장. 차세대 배터리·연료전지 재료 양자 시뮬레이션.',
          'Quantinuum IPO S-1 공개 이후 첫 대형 신규 계약.',
        ], why: '', notes: [] },
      { weight: 'low', time: '11:00', source: 'Japan / ScienceDaily',
        headline: '일본, W-state 양자 상태 순간 감지 성공 — 양자 네트워크 핵심 기술',
        url: 'https://www.sciencedaily.com/releases/2026/05/260508003129.htm',
        bullets: [
          '일본 연구팀, 양자 W-state 얽힘 상태 순간 감지 방법 개발. 양자 네트워크 라우팅 핵심 기술.',
          '기존 방법 대비 감지 시간 1/1000 단축. 양자 인터넷 실용화 가속.',
        ], why: '', notes: [] },
      { weight: 'low', time: '10:30', source: 'Harvard / The Quantum Insider',
        headline: '하버드 연구진 "양자컴퓨팅, 예상보다 빠르게 진화" — 2028년 실용 우위 가능성',
        url: 'https://thequantuminsider.com/2026/05/04/harvard-researchers-quantum-computing-advancing-faster-than-expected/',
        bullets: [
          '하버드 연구팀, 양자 오류 수정 속도가 업계 예측보다 18개월 앞서 진행 중 발표.',
          '현재 큐비트 품질 향상 속도 유지 시 2028년 실용적 양자 우위 달성 가능성 제기.',
        ], why: '', notes: [] },
    ],
  },
  econ: {
    label: '경제 뉴스',
    summary: '삼성전자 파업 5/18 2차 사후조정에서 정부와 이재용이 나서며 협상이 재개됐습니다. 이번 주 Google I/O(5/19)와 NVIDIA 실적(5/20)이 기술주 방향을 결정할 핵심 이벤트입니다. WTI $106대·원달러 1,497원이 지속되며 인플레·환율 부담이 이어지고 있습니다.',
    items: [
      { weight: 'high', time: '09:00', source: '세계일보 / 머니투데이',
        headline: '삼성전자 파업 5/18 2차 사후조정 — 이재용·정부 개입, 5/21 파업 기로',
        url: 'https://www.segye.com/newsView/20260517508759?OutUrl=google',
        bullets: [
          '삼성전자 노사, 5월 18일 2차 사후조정 재개. 김민석 총리·이재용 회장 중재 나서.',
          '노조 요구: 성과급 투명화·OPI 상한 폐지·영업이익 15% 성과급. 합의 실패 시 5/21 18일 총파업.',
          '파업 현실화 시 반도체 수출 30조원 손실 추산, GDP -0.78% 충격. SK하이닉스 반사이익.',
        ],
        why: '삼성전자 파업은 HBM4 공급망과 NVIDIA·AMD 납품 일정에 직결됩니다. 2차 조정 결과가 오늘 오후 발표될 예정으로 반도체 섹터 투자자 이목이 집중됩니다.',
        notes: [
          { term: 'OPI(초과이익성과급)', def: '삼성전자의 이익 공유 제도. 연간 목표 초과 이익의 일정 비율을 직원에게 지급. 노조는 상한 폐지·투명 산정 요구.' },
          { term: '사후조정', def: '파업 전 마지막 노사 중재 절차. 고용부 중재 하에 양측이 합의 시도. 실패 시 파업 합법화.' },
        ] },
      { weight: 'high', time: '07:00', source: 'CNBC / TheStreet',
        headline: '이번 주 최대 이벤트: Google I/O(5/19)·NVIDIA 실적(5/20) — 기술주 방향 결정',
        url: 'https://www.cnbc.com/2026/05/15/whats-ahead-wall-street-and-main-street-face-off-with-nvidia-consumer-earnings.html',
        bullets: [
          'Google I/O 2026(5/19) 키노트: Gemini 4.0 서프라이즈 시 Alphabet·반도체 섹터 급반등 기대.',
          'NVIDIA 실적(5/20 장마감후): EPS $1.78·매출 $792억 컨센서스. 데이터센터 가이던스가 AI 인프라 수요 신호.',
          '두 이벤트 동반 서프라이즈 시 KOSPI 7,900 목표. 실망 시 7,000선 붕괴 위험.',
        ],
        why: 'NVIDIA 실적은 AI 인프라 투자 사이클의 지속 여부를 판가름합니다. 삼성 HBM 납품 가이던스가 포함될 경우 파업 리스크 상쇄 가능.',
        notes: [
          { term: 'EPS(주당순이익)', def: '기업 순이익을 발행 주식 수로 나눈 값. 실적 서프라이즈 여부 판단 기준. 컨센서스 상회 시 주가 상승 트리거.' },
        ] },
      { weight: 'low', time: '06:00', source: 'Reuters',
        headline: 'WTI $106대 유지, 브렌트 $110.60 — 호르무즈 긴장·에너지 인플레 지속',
        url: '',
        bullets: [
          'WTI $106.50·브렌트 $110.60 유지. 이란 협상 미해결로 호르무즈 긴장 지속.',
          'WTI $110+ 고착화 시 미 CPI 3.8%→4%+ 돌파 가능 → 워시 연준 금리 인상 시나리오.',
        ], why: '', notes: [] },
      { weight: 'low', time: '08:00', source: 'CoinDesk',
        headline: 'BTC $78,028 주말 추가 하락 — VIX 18.43, 리스크오프 유지',
        url: 'https://www.coindesk.com/markets/2026/05/15/bitcoin-tumbles-below-usd79-000-as-rising-bond-yields-inflation-worries-rattle-markets',
        bullets: [
          'BTC $78,028(-0.22%) 주말 지속 하락. VIX 18.43(+6.78%) 상승, 리스크오프 심리 유지.',
          '$75,000 지지선 테스트 접근. Google I/O 결과에 따라 리스크온 전환 가능성.',
        ], why: '', notes: [] },
      { weight: 'low', time: '10:00', source: '한국은행',
        headline: '원달러 1,497원 — 1,500원 저항선 근접, 외환당국 구두 개입 경계',
        url: '',
        bullets: [
          '원달러 1,497원 장중 1,500원 근접. 이란 불확실성·KOSPI 외국인 매도 복합 작용.',
          '한국은행 구두 개입 가능성 고조. 1,500원 돌파 시 직접 개입 현실화 전망.',
        ], why: '', notes: [] },
      { weight: 'low', time: '11:00', source: '미국 노동부',
        headline: '미국 CPI 3.8% 헤드라인·근원 2.8% — 주거비 재상승, 워시 매파 기조 강화',
        url: '',
        bullets: [
          '5월 CPI 헤드라인 3.8%, 근원 2.8% — 모두 컨센서스 상회. 주거비 재반등이 변수.',
          '6월 FOMC 동결 확률 94%, 인상 12%. 2027년 첫 인하 컨센서스 유지.',
        ], why: '', notes: [] },
      { weight: 'low', time: '06:30', source: 'JP모간',
        headline: 'JP모간 "삼성 파업 손실 하향 조정, 조정 시 매수" — 목표가 35만원 유지',
        url: 'https://www.mt.co.kr/stock/2026/05/14/2026051413562014285',
        bullets: [
          'JP모간, 삼성전자 파업 예상 손실 추정치 하향. 협상 타결 시 매수 기회로 평가.',
          '목표주가 35만원 유지. HBM4 납품 차질 없으면 연간 실적 영향 제한적.',
        ], why: '', notes: [] },
      { weight: 'low', time: '09:30', source: 'KDI',
        headline: 'KDI 주간 점검 — 반도체 AI 수출 견조, 파업·이란이 유일한 성장 리스크',
        url: '',
        bullets: [
          'KDI 주간 경기 점검: 반도체·AI 수출 양호 유지. 2026년 성장률 2.5% 달성 가능성 유지.',
          '핵심 리스크 2가지 — ①삼성 파업 장기화 ②이란 에너지 쇼크 고착화.',
        ], why: '', notes: [] },
    ],
  },
  columns: {
    label: '컬럼 피드',
    summary: '오건영 단장은 어제 주말 에세이에서 지난 금요일 KOSPI 급락을 주식-채권 디커플링 관점으로 분석했습니다. 오늘 아침 새 게시물은 아직 없으며, Google I/O·NVIDIA 실적이 이번 주 핵심 이벤트라는 맥락을 제시한 바 있습니다.',
    items: [
      {
        name: '오건영', title: '신한은행 · 디지털 크리에이터', avatar: 'OG', color: '#D97757',
        time: '5월 17일 08:00', likes: 717, comments: 33,
        post: '주말 에세이 바로 시작합니다. 지난 금요일 주식 시장이 긴장하는 모습을 보였죠. 상승세가 가팔랐던 코스피 지수의 하락세가 전세계적으로 두드러졌구요... 그 중심에는 금리 급등이라는 이슈가 있었죠. 주식과 채권의 디커플링이라는 관점에서 생각해보면 어떨까 합니다. 전쟁이 끝나지도 않았는데 주식 시장이 강세를 이어가고 있죠. 에너지 주식들처럼 인플레이션을 헤지할 수 있는 자산들도 있을 겁니다. 다음 주 Google I/O와 NVIDIA 실적이 기술주 방향을 결정할 핵심 이벤트입니다.',
        summary: '주식-채권 디커플링으로 KOSPI 급락 분석. 에너지·인플레 헤지 자산 강조. 이번 주 Google I/O·NVIDIA 실적 주목.',
      },
    ],
  },
  invest: {
    title: 'I/O·NVIDIA 실적 주간 전략',
    subtitle: 'Claude가 작성한 오늘의 메모 · 5월 18일 07:00 · 5분 읽기',
    sections: [
      { h: '한 줄 요약', body: 'Google I/O(5/19)·NVIDIA 실적(5/20)·삼성 파업 조정(오늘 오후)이 이번 주 3대 이벤트입니다. 세 가지 결과에 따라 KOSPI 7,000~7,900 폭의 방향이 결정되며, 오늘 오후까지 방어적 포지션을 유지해야 합니다.' },
      { h: '오늘의 변수', body: '①삼성전자 2차 사후조정(오늘 오후) — 타결 시 삼성 반등·SK하이닉스 소폭 하락, 결렬 시 SK하이닉스 급등. ②Google I/O(내일 10AM PT) — Gemini 4.0 실망 시 Alphabet -5%, 서프라이즈 시 +7%. ③NVIDIA 실적(모레 장마감후) — EPS $1.78·매출 $792억 컨센서스. ④WTI $107+ 고착 시 CPI 4%대 돌파 위험.' },
      { h: '포지셔닝', body: '단기(1-3개월): 오늘 오후 삼성 파업 결과 확인 전 국내주식 관망. 금(GLD) 30% 유지 — 이란·인플레이션 이중 헤지 최우선. 배당주(VYM) 20% — 고금리 상대 강세. 채권(TLT) 5% 최소화 유지. 중기(6-12개월): Google I/O 서프라이즈 확인 후 Alphabet 편입. NVIDIA 가이던스 서프라이즈 시 AI 인프라 섹터 비중 확대. SK하이닉스 파업 영향 없는 독립 수혜 포지션 유지.' },
      { h: '리스크', body: 'Google I/O 기대 미충족 → Alphabet·NVIDIA 동반 급락 → KOSPI 7,000선 붕괴. 삼성 파업 장기화 → HBM4 공급 차질 → AI 인프라 투자 지연 → NVIDIA 실적 미스로 연결. WTI $115+ → CPI 4%+ → 워시 연준 인상 → 성장주·채권 동반 급락. BTC $75K 지지선 붕괴 → 암호화폐 패닉 매도.' },
    ],
    watchlist: [
      { sym: '000660', name: 'SK하이닉스',  val: '1,942,910', pct: '-3.00%', up: false, note: '삼성 파업 반사이익 — 타결 시 소폭 하락, 결렬 시 급등' },
      { sym: '005930', name: '삼성전자',    val: '282,500',   pct: '-4.39%', up: false, note: '2차 사후조정 오늘 오후 — 타결 여부가 반도체 방향 결정' },
      { sym: 'NVDA',   name: 'NVIDIA',      val: '$224.41',   pct: '+0.10%', up: true,  note: '5/20 실적 — EPS $1.78·매출 $792억 컨센서스 상회 여부 핵심' },
      { sym: 'GOOGL',  name: 'Alphabet',    val: '$196.30',   pct: '-1.07%', up: false, note: 'I/O 2026(5/19) 내일 키노트 — Gemini 4.0 기대' },
      { sym: 'TLT',    name: 'iShares 20Y', val: '$88.15',    pct: '-1.51%', up: false, note: '10Y 4.60% — 워시 매파 기조, 채권 추가 하락 가능' },
      { sym: 'GLD',    name: 'SPDR Gold',   val: '$252.80',   pct: '+0.40%', up: true,  note: '이란·인플레·고금리 3중 헤지 — 포트폴리오 핵심' },
      { sym: 'VYM',    name: 'Vanguard HY', val: '$131.34',   pct: '-0.80%', up: false, note: '고금리 장기화 환경 — 배당주 상대 강점 유지' },
      { sym: 'BTC',    name: 'Bitcoin',     val: '$78,028',   pct: '-0.22%', up: false, note: '주말 지속 하락 — $75K 지지선 테스트 접근' },
    ],
    portfolio: [
      { asset: '국내주식', pct: 15, color: '#3DDC97',
        tickers: [{ sym: '000660', name: 'SK하이닉스' }, { sym: '005930', name: '삼성전자' }],
        note: '파업 타결 확인 전 관망, SK하이닉스 집중' },
      { asset: '미국주식', pct: 20, color: '#5B9BD5',
        tickers: [{ sym: 'NVDA', name: 'NVIDIA' }, { sym: 'GOOGL', name: 'Alphabet' }],
        note: 'I/O·실적 확인 후 비중 재조정 예정' },
      { asset: '채권',    pct: 5,  color: '#9B8EC4',
        tickers: [{ sym: 'TLT', name: 'iShares 20Y ETF' }],
        note: '워시 매파 — 최소화, 현금 전환 대기' },
      { asset: '금',      pct: 30, color: '#F5C518',
        tickers: [{ sym: 'GLD', name: 'SPDR Gold ETF' }],
        note: '이란·인플레·고금리 3중 헤지 — 최대화 유지' },
      { asset: '배당주',  pct: 20, color: '#E08A6E',
        tickers: [{ sym: 'VYM', name: 'Vanguard High Div.' }],
        note: '리스크오프 + 고금리 — 안정 수익 강점' },
      { asset: '비트코인', pct: 10, color: '#F7931A',
        tickers: [{ sym: 'BTC', name: 'Bitcoin' }],
        note: '$75K 지지선 모니터링, 소폭 유지' },
    ],
  },
};

window.BRIEF_ARCHIVE = { '2026-05-18': TODAY, '2026-05-17': D_0517 };
window.BRIEF_DATES   = ['2026-05-18', '2026-05-17'];
window.BRIEF_TODAY   = '2026-05-18';
window.BRIEF_USER    = '재현';
window.BRIEF_DATA    = TODAY;
