// Daily briefing — multi-day archive.
// BRIEF_ARCHIVE is keyed by ISO date. BRIEF_DATES is newest-first.
// Past days carry slimmer content than today (the showcase day).

// ── Past days (compact)
function pastDay({ iso, label, shortLabel, market, ai, physical, quantum, econ, columns, invest }) {
  const obj = { date: { iso, label, shortLabel, isToday: false }, marketStrip: market, ai, econ, columns, invest };
  if (physical) obj.physical = physical;
  if (quantum)  obj.quantum  = quantum;
  return obj;
}


// 아카이브: 2026-05-21
const D_0521 = pastDay({
  iso: '2026-05-21', label: '2026년 5월 21일 목요일', shortLabel: '5월 21일 (목)',
  market: [
    { sym: 'KOSPI',   val: '7,580',   pct: '+0.80%', up: true  },
    { sym: 'S&P 500', val: '7,423',   pct: '+0.94%', up: true  },
    { sym: 'NASDAQ',  val: '26,217',  pct: '+1.34%', up: true  },
    { sym: 'BTC',     val: '$77,687', pct: '+0.38%', up: true  },
    { sym: '$/₩',    val: '1,497',   pct: '+0.33%', up: true  },
    { sym: '10Y UST', val: '4.67%',  pct: '-2bp',   up: false },
    { sym: 'WTI',     val: '$97.33',  pct: '-6.55%', up: false },
  ],
  ai: {
    label: 'AI 뉴스',
    summary: 'Andrej Karpathy가 Anthropic에 합류하며 AI 인재 생태계를 뒤흔들었습니다. Google I/O 2026 결과로 Gemini 3.5 Flash가 전 세계 기본 모델로 배포됐고, KPMG 27만 6천 명 전사 Claude 배포 등 기업 AI 채택이 전사 운영 수준으로 확대되고 있습니다.',
    items: [
      { weight: 'high', time: '09:00', source: 'Anthropic / X',
        headline: 'Andrej Karpathy, Anthropic 합류 확인 — OpenAI 공동창업자 이번 주 근무 시작',
        url: 'https://simonwillison.net/2026/May/6/code-w-claude-2026/',
        bullets: [
          'AI 스타 개발자 안드레이 카르파티, X에서 Anthropic 합류 공식 발표. 이번 주부터 근무.',
          'OpenAI 공동창업자(2015) → Tesla AI 총괄 → Eureka Labs 창업 → Anthropic. AI 최고 인재 이동 사례.',
          '$900억+ 밸류에이션 라운드 클로징 앞두고 역대급 인재 확보. OpenAI 대비 경쟁력 강화.',
        ],
        why: '카르파티는 AI 업계에서 가장 영향력 있는 개발자 중 한 명입니다. Anthropic 합류는 인재 경쟁에서 Anthropic이 우위를 점했음을 보여줍니다.',
        notes: [{ term: 'Andrej Karpathy', def: 'OpenAI 공동창업자. Tesla AI 총괄 역임. PyTorch·LLM 교육 콘텐츠로 전 세계 AI 커뮤니티에 큰 영향력을 가진 스타 연구자.' }] },
      { weight: 'high', time: '08:00', source: 'Google / 구글 공식 블로그',
        headline: 'Google I/O 2026 — Gemini 3.5 Flash 전 세계 기본 배포, 검색 에이전트 시대 개막',
        url: 'https://blog.google/intl/ko-kr/company-news/technology/search-io-2026/',
        bullets: [
          'Gemini 3.5 Flash, AI 모드 기본 모델로 98개 언어·200개국 전면 배포. 별도 구독 없이 무료.',
          '검색 에이전트(Search Agent) 공식 출시. 검색창에서 AI 에이전트 생성·설정·관리 가능.',
          'Gemini Spark 에이전트 AI Ultra($100/월) 우선 배포. 개인 인텔리전스 무료 확대.',
        ],
        why: 'Gemini 3.5 Flash 전 세계 기본 배포는 구글 검색이 AI 에이전트로 전환됐음을 공식화합니다.',
        notes: [
          { term: '검색 에이전트', def: '구글 검색창 내에서 실행되는 AI 에이전트. 복잡한 리서치 작업 자율 수행.' },
          { term: 'Gemini 3.5 Flash', def: '구글 최신 경량 AI 모델. 에이전트·코딩 강점, 프론티어 모델 대비 절반 가격.' },
        ] },
      { weight: 'high', time: '10:00', source: 'Anthropic / KPMG',
        headline: 'KPMG 전 세계 27만 6천 명 Claude 전사 배포 — 역대 최대 기업 AI 배포',
        url: 'https://www.anthropic.com/news/pwc-expanded-partnership',
        bullets: [
          'KPMG, Anthropic과 전략적 제휴. 전 세계 27만 6,000명 전 직원에 Claude 배포.',
          '회계·감사·컨설팅·세무 핵심 업무 전반에 Claude 통합. 역대 최대 규모 기업 AI 배포.',
          'Anthropic API 사용량 전년 대비 17배 성장 배경. PwC 36만 명 이어 연속 대형 계약.',
        ],
        why: 'KPMG 27만 6천 명 배포는 기업 AI가 특정 팀 도구에서 전사 운영 인프라로 전환됐음을 보여주는 이정표입니다.',
        notes: [{ term: 'KPMG', def: '딜로이트·PwC·EY와 함께 세계 4대 회계법인. 글로벌 27만 6천 명 직원.' }] },
      { weight: 'low', time: '07:00', source: 'Anthropic / InfoWorld',
        headline: 'Anthropic, 6월 15일부터 Claude 에이전트 별도 미터제 과금',
        url: 'https://www.infoworld.com/article/4171274/anthropic-puts-claude-agents-on-a-meter-across-its-subscriptions.html',
        bullets: [
          'Anthropic, 6/15부터 Agent SDK·GitHub Actions·서드파티 프레임워크 에이전트 사용량 별도 청구.',
          '기존 구독 한도와 분리, API 방식 요금 적용. 에이전트 AI 수익화 모델 전환.',
        ], why: '', notes: [] },
      { weight: 'low', time: '06:00', source: 'Anthropic',
        headline: 'Anthropic, Stainless SDK 인수 — Claude API 통합 개발자 경험 강화',
        url: 'https://www.anthropic.com/news',
        bullets: [
          'Anthropic, API 래퍼 자동생성 스타트업 Stainless 인수. SDK 자동화 기술 확보.',
          'Claude API 통합 개발자 경험 강화. 다양한 언어 SDK 자동 유지보수 가능.',
        ], why: '', notes: [] },
      { weight: 'low', time: '09:30', source: 'Microsoft / Google / CNN',
        headline: 'Microsoft·Google·xAI, 미 정부에 AI 모델 사전 테스트 허용',
        url: 'https://www.cnn.com/2026/05/05/tech/microsoft-google-xai-government-test-ai-models',
        bullets: [
          'Microsoft·Google·xAI 3사, 미 정부 기관에 새 AI 모델 출시 전 사전 테스트 접근 허용.',
          'AI 안전·보안 검증 협력. 국가 AI 인프라 신뢰성 확보 목적.',
        ], why: '', notes: [] },
      { weight: 'low', time: '08:30', source: 'Anthropic',
        headline: 'Anthropic, SpaceX Colossus 데이터센터 전용량 파트너십 — API 17배 성장 대응',
        url: 'https://www.anthropic.com/news',
        bullets: [
          'Anthropic, SpaceX Colossus 데이터센터 전체 용량 활용 파트너십. Claude 수요 급증 대응.',
          'Claude API 사용량 전년 대비 17배 성장. 컴퓨팅 병목 해소 위해 데이터센터 다각화.',
        ], why: '', notes: [] },
      { weight: 'low', time: '11:00', source: 'Anthropic',
        headline: 'Claude for Small Business 출시 — QuickBooks·HubSpot·Canva 등 7개 앱 통합',
        url: 'https://blog.mean.ceo/anthropic-claude-news-may-2026/',
        bullets: [
          'Anthropic, Claude for Small Business 패키지 출시. QuickBooks·PayPal·HubSpot·Canva·DocuSign·Google Workspace·Microsoft 365 통합.',
          '중소기업 AI 워크플로 자동화. 별도 IT 인력 없이 즉시 사용.',
        ], why: '', notes: [] },
    ],
  },
  physical: {
    label: '피지컬 AI 뉴스',
    summary: 'Boston Dynamics가 Atlas 휴머노이드 로봇의 100파운드급 가전제품 처리 영상을 공개했고, 일본항공(JAL)이 하네다 공항에 Unitree 기반 휴머노이드를 배치해 공항 최초 실용 사례를 만들었습니다. SoftBank의 ABB 로봇사업부 $54억 인수와 AgiBot의 1만 번째 휴머노이드 생산으로 피지컬 AI 산업화가 가속됩니다.',
    items: [
      { weight: 'high', time: '09:00', source: 'Boston Dynamics / Robotics & Automation News',
        headline: 'Boston Dynamics, Atlas가 100파운드+ 냉장고·세탁기 이동 — 강화학습 전신 제어',
        url: 'https://roboticsandautomationnews.com/2026/05/20/boston-dynamics-trains-atlas-humanoid-robot-to-pick-up-and-place-washing-machine/101759/',
        bullets: [
          'Boston Dynamics, Atlas 휴머노이드가 냉장고(100파운드+)·세탁기를 집어 이동하는 영상 공개.',
          '강화학습(RL)·전신 제어(whole-body control) 기술 적용. 가전 설치·이동 자율 수행.',
          'Atlas 2026년 전량 생산이 현대·Google DeepMind에 납품 확정. 상업 배포 가속.',
        ],
        why: '100파운드 이상 가전 처리는 Atlas가 단순 시범을 넘어 실제 가정·산업 작업을 수행할 수 있는 단계에 도달했음을 보여줍니다.',
        notes: [
          { term: '강화학습(RL)', def: '로봇이 시행착오로 최적 동작을 학습하는 AI 기법.' },
          { term: '전신 제어', def: '팔·다리·몸통을 동시에 협조 제어해 무거운 물체를 안정적으로 처리하는 기술.' },
        ] },
      { weight: 'high', time: '08:00', source: 'Robotics & Automation News',
        headline: '일본항공(JAL), 하네다 공항 Unitree 휴머노이드 배치 — 공항 최초 실용 사례',
        url: 'https://roboticsandautomationnews.com/',
        bullets: [
          'Japan Airlines, 도쿄 하네다 공항에 Unitree Robotics 기반 휴머노이드 2대 공식 배치.',
          '수하물 적재·컨테이너 운반·기내 청소 자율 수행. 공항 최초 휴머노이드 실용 배치 사례.',
          '항공업계 인력난 해소 목적. 2026년 하반기 나리타 공항 확대 예정.',
        ],
        why: '공항은 고반복·고위험 작업이 혼재해 휴머노이드 실용성 검증에 최적입니다.',
        notes: [{ term: 'Unitree Robotics', def: '중국 휴머노이드 로봇 기업. G1 모델($15,400)로 가격 혁신 선도.' }] },
      { weight: 'low', time: '07:00', source: 'SoftBank / The Robot Report',
        headline: 'SoftBank, ABB 로봇사업부 $54억 인수 — "피지컬 AI 다음 프론티어" 선언',
        url: 'https://www.therobotreport.com/from-evs-to-robotics-tesla-targets-10m-optimus-units-with-new-texas-plant/',
        bullets: [
          'SoftBank, ABB 로봇사업부 54억 달러에 인수. 피지컬 AI를 "다음 프론티어"로 공식 선언.',
          'ABB 산업 로봇 기술 + SoftBank AI 통합. 제조·물류 자동화 시장 본격 진입.',
        ], why: '', notes: [] },
      { weight: 'low', time: '06:00', source: 'AgiBot',
        headline: 'AgiBot, 누적 1만 번째 휴머노이드 생산 — 2025년 1,000대 대비 10배',
        url: 'https://www.prnewswire.com/apac/news-releases/the-first-hong-kong-embodied-ai-industry-summit-and-agibot-partner-conference-2026-hong-kong-opens-302770944.html',
        bullets: [
          'AgiBot, 2026년 3월 기준 누적 1만 번째 휴머노이드 생산 완료. 2025년 1,000대에서 10배.',
          '중국 피지컬 AI 기업 최초 대량 양산 달성.',
        ], why: '', notes: [] },
      { weight: 'low', time: '10:00', source: 'NVIDIA Newsroom',
        headline: 'NVIDIA Isaac GR00T 오픈 모델 업데이트 — 자연어로 로봇 멀티스텝 작업',
        url: 'https://nvidianews.nvidia.com/news/nvidia-and-global-robotics-leaders-take-physical-ai-to-the-real-world',
        bullets: [
          'NVIDIA Isaac GR00T 오픈 모델 업데이트. 자연어 명령 이해·복잡한 멀티스텝 VLA 추론.',
          'Figure·1X·Agility·Boston Dynamics 등 글로벌 파트너 즉시 적용.',
        ], why: '', notes: [] },
      { weight: 'low', time: '11:00', source: 'Tesla / Electrek',
        headline: 'Tesla Optimus V3 공개 7-8월로 재연기 — 프리몬트 라인 전환 최종 단계',
        url: 'https://electrek.co/2026/04/22/tesla-optimus-production-fremont-model-sx-line/',
        bullets: [
          'Tesla Optimus V3 공개 7월 말~8월로 재연기. Model S·X 단종 후 생산 라인 전환 최종 단계.',
          '머스크 "초기 생산 속도 예측 불가". 1만 개 고유 부품 신규 조립 라인.',
        ], why: '', notes: [] },
      { weight: 'low', time: '08:30', source: 'Figure AI',
        headline: 'Figure AI-BMW, 30,000대 X3 생산 지원 완료 — 1,250시간·90,000+ 부품',
        url: 'https://humanoid.press/',
        bullets: [
          'Figure AI Figure 02, BMW 스파르탄버그 공장 11개월 배치. BMW X3 30,000대 이상 생산 기여.',
          '1,250시간 자율 운영·90,000+ 부품 처리 달성.',
        ], why: '', notes: [] },
      { weight: 'low', time: '09:30', source: 'KraneShares',
        headline: '2026 휴머노이드 — "파일럿에서 플랫폼으로", 세계 모델 $60억 집중 투자',
        url: 'https://kraneshares.com/humanoid-robotics-in-2026-the-race-from-pilot-to-platform/',
        bullets: [
          'KraneShares 보고서: 휴머노이드 시장 2026년 "파일럿→플랫폼" 전환 공식 진입.',
          'Q1 2026 세계 모델 기업 6~7개사에 $60억 집중 투자.',
        ], why: '', notes: [] },
    ],
  },
  quantum: {
    label: '양자 뉴스',
    summary: 'IonQ가 Q1 2026 매출 755% YoY 성장을 기록하며 연간 가이던스를 $2억 6,500만으로 대폭 상향했고, 콜로라도 볼더에 22,000 sq ft R&D 연구소를 개소했습니다. Xanadu는 Nasdaq 상장 후 Q1 매출 304% 성장을 기록하며 정부 $2.85억 자금 지원 협상 중입니다.',
    items: [
      { weight: 'high', time: '09:00', source: 'IonQ',
        headline: 'IonQ Q1 2026 매출 +755% YoY — 연간 가이던스 $2.65억으로 대폭 상향',
        url: 'https://finance.yahoo.com/quote/IONQ/',
        bullets: [
          'IonQ, Q1 2026 매출 전년 대비 755% 폭증. 양자컴퓨팅 기업 역대 최대 성장률.',
          '연간 매출 가이던스 $2억 6,500만으로 대폭 상향. 정부·기업 고객 계약 확대가 견인.',
          '양자컴퓨팅 상업화 본격화 확인. 이온트랩 방식 리더십 강화.',
        ],
        why: 'IonQ의 755% 매출 성장은 양자컴퓨팅이 실험실을 넘어 실제 매출이 발생하는 산업으로 전환됐음을 보여주는 이정표입니다.',
        notes: [{ term: 'IonQ', def: '미국 이온트랩 방식 양자컴퓨팅 기업. NYSE 상장.' }] },
      { weight: 'high', time: '08:00', source: 'IonQ / TipRanks',
        headline: 'IonQ, 콜로라도 볼더 22,000 sq ft R&D 연구소 개소 — 반도체 이온트랩 칩 개발',
        url: 'https://www.tipranks.com/news/quantum-computing-news-ibm-ionq-and-xanadu-signal-the-next-phase-of-quantum-infrastructure-and-security',
        bullets: [
          'IonQ, 콜로라도 볼더 22,000 sq ft 전용 양자 R&D 연구소 개소(5/15). 반도체 이온트랩 칩 설계·테스트.',
          '차세대 양자 시스템 2026년 말 출시 목표. NIST·콜로라도대 등 인근 연구기관과 협력.',
          '볼더 지역 양자 기업 클러스터 허브 역할. 하드웨어 내재화 전략 가속.',
        ],
        why: 'IonQ의 전용 R&D 시설 확보는 차세대 양자 하드웨어를 자체 개발해 경쟁사와 차별화하는 전략적 투자입니다.',
        notes: [{ term: '이온트랩(Ion Trap)', def: '전자기장으로 이온을 가두어 큐비트로 활용하는 양자컴퓨팅 방식.' }] },
      { weight: 'low', time: '07:00', source: 'IonQ / Florida LambdaRail',
        headline: 'IonQ, 플로리다 100마일 양자 암호 통신망 구축 — 팜비치~마이애미',
        url: 'https://www.ionq.com/news',
        bullets: [
          'IonQ·Florida LambdaRail, 팜비치~마이애미 100마일 QKD(양자키분배) 통신망 착공.',
          '2027년 금융·의료·정부 기관 대상 상업 서비스 예정.',
        ], why: '', notes: [] },
      { weight: 'low', time: '06:00', source: 'Xanadu / TipRanks',
        headline: 'Xanadu, Nasdaq·TSX 상장 후 Q1 매출 +304% — AMD 협력 양자 CFD 돌파',
        url: 'https://www.tipranks.com/news/quantum-computing-news-ibm-ionq-and-xanadu-signal-the-next-phase-of-quantum-infrastructure-and-security',
        bullets: [
          'Xanadu, Nasdaq·TSX 동시 상장 후 Q1 2026 매출 +304.3%. 정부 $2.85억 자금 협상 중.',
          'AMD와 양자 전산유체역학(CFD) 시뮬레이션 돌파 달성.',
        ], why: '', notes: [] },
      { weight: 'low', time: '10:00', source: 'IBM / NYU',
        headline: 'IBM·NYU, 양자컴퓨팅 공동 박사후 프로그램 출범 — 하이브리드 알고리즘',
        url: 'https://www.tipranks.com/news/quantum-computing-news-ibm-ionq-and-xanadu-signal-the-next-phase-of-quantum-infrastructure-and-security',
        bullets: [
          'IBM·뉴욕대(NYU), 양자컴퓨팅 응용 공동 박사후 연구 프로그램 출범(5/11).',
          'IBM Watson 연구소·NYU 양자연구소 협력. 하이브리드 양자-클래식 알고리즘 개발.',
        ], why: '', notes: [] },
      { weight: 'low', time: '11:00', source: 'Harvard / The Quantum Insider',
        headline: '하버드 "양자컴퓨팅, 예상보다 18개월 앞서 진화" — 2028년 실용 우위 전망',
        url: 'https://thequantuminsider.com/2026/05/04/harvard-researchers-quantum-computing-advancing-faster-than-expected/',
        bullets: [
          '하버드 연구팀, 양자 오류 수정 속도가 업계 예측보다 18개월 빠르게 진행 중.',
          '현재 속도 유지 시 2028년 실용적 양자 우위 달성 가능성 제기.',
        ], why: '', notes: [] },
      { weight: 'low', time: '08:30', source: 'CNN',
        headline: 'CNN: 구글 "양자컴퓨터, 2029년 암호화 해킹 가능" — Q-Day 준비 창 좁아져',
        url: 'https://us.cnn.com/2026/05/17/science/quantum-computing-cybersecurity-q-day',
        bullets: [
          'CNN 보도: 구글, 양자컴퓨터가 2029년까지 RSA 암호화 해독 가능 경고.',
          '기업 양자 내성 암호 전환율 12% 불과. NSA 2027년 의무화 기한 압박.',
        ], why: '', notes: [] },
      { weight: 'low', time: '09:30', source: 'IEEE Spectrum',
        headline: '중성 원자 양자컴퓨팅 2026 대약진 — 게이트 충실도 99.9% 돌파',
        url: 'https://spectrum.ieee.org/neutral-atom-quantum-computing',
        bullets: [
          '중성 원자 양자컴퓨팅 게이트 충실도 99.9% 달성 연구 잇따라. QuEra·Pasqal 주목.',
          '이온트랩과 경쟁에서 규모 확장성 강점으로 재부상.',
        ], why: '', notes: [] },
    ],
  },
  econ: {
    label: '경제 뉴스',
    summary: '삼성전자 노사가 총파업 90분 전 극적으로 잠정 합의해 HBM4 공급망 리스크를 단기 해소했습니다. WTI 유가가 $97.33으로 6.55% 급락해 이란 협상 진전 기대가 높아졌고, 미중 정상회담은 $300억 비민감 품목 관세 인하 합의 외에 실질 성과 없이 종료됐습니다.',
    items: [
      { weight: 'high', time: '06:00', source: '뉴스핌 / 머니투데이',
        headline: '삼성전자 파업 90분 전 극적 잠정합의 — 파업 유보, 5/23~28 찬반투표',
        url: 'https://www.newspim.com/news/view/20260520001194',
        bullets: [
          '삼성전자 노사, 총파업 돌입 90분 전 2026년 임금·성과급 협상 잠정 합의. 파업 유보.',
          '5/23~28 조합원 찬반투표 실시 예정. 부결 시 파업 재개 가능성 잔존.',
          'HBM4 공급망 단기 정상화. 반도체 수출 30조 원 손실 위험 일단 해소.',
        ],
        why: '파업 잠정합의로 삼성 반도체 생산·HBM4 납품이 단기 안정화됩니다.',
        notes: [{ term: '잠정합의', def: '노사가 협상안에 잠정 동의. 조합원 찬반투표(5/23~28) 통과 시 최종 타결.' }] },
      { weight: 'high', time: '09:00', source: 'Reuters / Bloomberg',
        headline: 'WTI $97.33 급락(-6.55%) — 이란 협상 진전 기대, 호르무즈 우려 완화',
        url: '',
        bullets: [
          'WTI 유가 $97.33(-6.55%). 이란 핵 협상 진전 기대로 호르무즈 해협 공급 우려 완화.',
          '브렌트 $100선 붕괴. 에너지발 CPI 하방 압력으로 연준 금리 인상 확률 소폭 하락 기대.',
          'WTI $100 이하 고착화 시 글로벌 인플레이션 완화 시나리오 강화.',
        ],
        why: 'WTI 급락은 에너지 인플레이션 완화 신호로, 연준 금리 경로·채권시장 안정에 가장 중요한 변수 중 하나입니다.',
        notes: [{ term: '호르무즈 해협', def: '이란-아랍에미리트 사이 해협. 전 세계 석유 수송 20%가 통과하는 에너지 요충지.' }] },
      { weight: 'low', time: '10:00', source: '법률신문 / Bloomberg',
        headline: '미중 정상회담 공동성명 없이 종료 — $300억 비민감 품목 관세 인하만 합의',
        url: 'https://www.lawtimes.co.kr/news/articleView.html?idxno=220864',
        bullets: [
          '트럼프-시진핑 정상회담 공동성명·공동기자회견 없이 종료. 실질 성과 제한적.',
          '$300억 비민감 품목 관세 인하·무역협의체 신설만 합의.',
        ], why: '', notes: [] },
      { weight: 'low', time: '08:00', source: 'MBC 뉴스',
        headline: 'G7 재무장관 — 채권 매도세 공동 대응 거부, 각국 자체 해결 확인',
        url: 'https://imnews.imbc.com/replay/2026/nwtoday/article/6823243_37012.html',
        bullets: [
          'G7 재무장관·중앙은행 총재 회의: 채권 매도세 공동 행동 없음.',
          '가타야마 일본 재무상 "유가 상승·호르무즈 폐쇄가 원인" 공감대. 실질 대응 부재.',
        ], why: '', notes: [] },
      { weight: 'low', time: '07:00', source: 'CME FedWatch',
        headline: '연준 기준금리 3.5~3.75% 동결 — WTI 급락으로 인상 확률 소폭 하락',
        url: 'https://ko.tradingeconomics.com/united-states/interest-rate',
        bullets: [
          '연준 기준금리 3.5~3.75% 3회 연속 동결. WTI 급락으로 에너지 인플레 완화 기대.',
          'CME FedWatch 연내 금리 인상 확률 소폭 하락. 6/16-17 워시 첫 FOMC 주목.',
        ], why: '', notes: [] },
      { weight: 'low', time: '11:00', source: '한국거래소',
        headline: '한국거래소, 6/3·7/17 증권시장 휴장 — 지방선거·제헌절 공휴일',
        url: '',
        bullets: [
          '한국거래소, 6월 3일(지방선거일)·7월 17일(제헌절) 증권·파생·일반상품시장 전체 휴장.',
          '투자자 포지션 조정 일정 참고 필요.',
        ], why: '', notes: [] },
      { weight: 'low', time: '06:30', source: 'KDI',
        headline: 'KDI — 삼성 파업 유보로 반도체 수출 우려 해소, 성장률 2.5% 유지',
        url: '',
        bullets: [
          'KDI: 삼성 파업 잠정합의로 반도체 수출 정상화 기대. 2026년 GDP 성장률 2.5% 목표 유지.',
          'WTI 급락 추가 호재. 리스크: 조합원 투표 부결·이란 불확실성 잔존.',
        ], why: '', notes: [] },
      { weight: 'low', time: '09:30', source: 'CNBC / Bloomberg',
        headline: 'NVIDIA 실적 낙수 — SK하이닉스·삼성전자 HBM 수혜, 한국 반도체 수출 호조',
        url: '',
        bullets: [
          'NVIDIA Q2 가이던스 $450억. SK하이닉스·삼성전자 HBM4 납품 물량 확대 전망.',
          '한국 5월 반도체·AI 수출 견조 유지. NVIDIA 수혜 직결.',
        ], why: '', notes: [] },
    ],
  },
  columns: {
    label: '컬럼 피드',
    summary: '오건영 단장은 G7 재무장관 회의에서 채권 매도세 공동 대응이 없다는 결과를 전하며, 글로벌 채권 발작의 원인(유가 상승·호르무즈 폐쇄)과 각국 자체 해결 입장을 분석했습니다.',
    items: [
      { name: '오건영', title: '신한은행 · 디지털 크리에이터', avatar: 'OG', color: '#D97757',
        time: '어제 08:00', likes: 486, comments: 17,
        post: '뉴스가 많이 쏟아져나오네요. 우선 G7 정상회담 얘기를 해봅니다. 최근 국채 금리 급등에 대해서 G7 차원의 논의를 해보겠다는 얘기였는데요. 별 다른 소득은 없어 보입니다. "글로벌 채권시장의 채권 매도세와 관련해 주요 7개국(G7) 차원의 공동 행동은 고려하지 않고 있으며 각국이 자국 상황을 책임져야 한다는 입장이라고 가타야마 사츠키 일본 재무상이 말했다."',
        summary: 'G7, 채권 매도세 공동 대응 없음 확인. 유가 상승·호르무즈 폐쇄 원인 공감만 이룬 채 각국 자체 해결.',
      },
    ],
  },
  invest: {
    title: '삼성 합의·WTI 급락 전략',
    subtitle: 'Claude가 작성한 오늘의 메모 · 5월 21일 09:00 · 5분 읽기',
    sections: [
      { h: '한 줄 요약', body: '삼성전자 파업 잠정합의(90분 전 극적 타결)로 HBM4 공급망 리스크 단기 해소. WTI $97.33(-6.55%) 급락으로 이란 협상 진전 기대. Andrej Karpathy Anthropic 합류로 AI 인재 경쟁 재편.' },
      { h: '오늘의 변수', body: '①삼성전자 조합원 찬반투표(5/23~28) — 부결 시 파업 재개. ②WTI $97 수준 유지 여부 — 이란 협상 진전 지속. ③G7 채권 공동 대응 없음 — 30년 국채 5.5%+ 재돌파 가능성. ④Karpathy Anthropic 합류 — 기술 방향 변화 주목.' },
      { h: '포지셔닝', body: '단기(1-3개월): 삼성 파업 유보로 국내주식 비중 소폭 확대. WTI 급락으로 금(GLD) 헤지 필요성 소폭 감소. SK하이닉스 집중 유지. 중기(6-12개월): 이란 협상 타결 시 WTI $80대 → 연준 인하 시나리오.' },
      { h: '리스크', body: '삼성 조합원 투표 부결 시 파업 재개 → HBM4 공급 차질. 이란 협상 재교착 → WTI 반등. 워시 6/17 FOMC 금리 인상 선언 시 글로벌 자산 동반 급락.' },
    ],
    watchlist: [
      { sym: '005930', name: '삼성전자',    val: '288,000',   pct: '+0.17%', up: true,  note: '파업 잠정합의 — 찬반투표 5/23~28이 최종 변수' },
      { sym: '000660', name: 'SK하이닉스',  val: '1,992,000', pct: '+0.20%', up: true,  note: 'NVIDIA Q2 $450억 가이던스 낙수 — HBM 공급 정상화' },
      { sym: 'NVDA',   name: 'NVIDIA',      val: '$245.50',   pct: '+1.53%', up: true,  note: '어닝 서프라이즈 후 추가 상승 — AI 인프라 신뢰 지속' },
      { sym: 'GOOGL',  name: 'Alphabet',    val: '$198.40',   pct: '+0.61%', up: true,  note: 'Gemini 3.5 Flash 전 세계 배포 — 검색 AI 전환 가속' },
      { sym: 'TLT',    name: 'iShares 20Y', val: '$87.20',    pct: '+0.81%', up: true,  note: 'WTI 급락 → 인플레 완화 기대 → 채권 소폭 회복' },
      { sym: 'GLD',    name: 'SPDR Gold',   val: '$252.80',   pct: '-0.83%', up: false, note: 'WTI 급락 에너지 헤지 완화 → 금 소폭 조정' },
      { sym: 'VYM',    name: 'Vanguard HY', val: '$132.10',   pct: '+0.46%', up: true,  note: '리스크오프 완화·WTI 하락 긍정적 — 소폭 반등' },
      { sym: 'BTC',    name: 'Bitcoin',     val: '$77,687',   pct: '+0.38%', up: true,  note: 'WTI 급락 리스크온 소폭 수혜 — $78K 저항선 주목' },
    ],
    portfolio: [
      { asset: '국내주식', pct: 22, color: '#3DDC97',
        tickers: [{ sym: '005930', name: '삼성전자' }, { sym: '000660', name: 'SK하이닉스' }],
        note: '파업 유보·NVIDIA 낙수 — 비중 소폭 확대' },
      { asset: '미국주식', pct: 23, color: '#5B9BD5',
        tickers: [{ sym: 'NVDA', name: 'NVIDIA' }, { sym: 'GOOGL', name: 'Alphabet' }],
        note: 'NVIDIA 서프라이즈 지속·Gemini 배포 — AI 중심 비중 확대' },
      { asset: '채권', pct: 7, color: '#9B8EC4',
        tickers: [{ sym: 'TLT', name: 'iShares 20Y ETF' }],
        note: 'WTI 급락 인플레 완화 기대 — 소폭 비중 복구' },
      { asset: '금', pct: 23, color: '#F5C518',
        tickers: [{ sym: 'GLD', name: 'SPDR Gold ETF' }],
        note: 'WTI 급락으로 에너지 헤지 완화 — 소폭 축소' },
      { asset: '배당주', pct: 18, color: '#E08A6E',
        tickers: [{ sym: 'VYM', name: 'Vanguard High Div.' }],
        note: '리스크오프 완화 환경 — 소폭 비중 조정' },
      { asset: '비트코인', pct: 7, color: '#F7931A',
        tickers: [{ sym: 'BTC', name: 'Bitcoin' }],
        note: '$78K 저항선 — 소폭 비중 유지' },
    ],
  },
});

// 아카이브: 2026-05-20
const D_0520 = pastDay({
  iso: '2026-05-20', label: '2026년 5월 20일 수요일', shortLabel: '5월 20일 (수)',
  market: [
    { sym: 'KOSPI',   val: '7,520',   pct: '+1.27%', up: true  },
    { sym: 'S&P 500', val: '7,420',   pct: '+0.50%', up: true  },
    { sym: 'NASDAQ',  val: '26,120',  pct: '+0.37%', up: true  },
    { sym: 'BTC',     val: '$76,984', pct: '+0.23%', up: true  },
    { sym: '$/₩',    val: '1,492',   pct: '-0.60%', up: false },
    { sym: '10Y UST', val: '4.69%',  pct: '+6bp',   up: true  },
    { sym: 'WTI',     val: '$104.10', pct: '+0.87%', up: true  },
  ],
  ai: {
    label: 'AI 뉴스',
    summary: 'Google I/O 2026 2일차 개발자 키노트에서 Gemini Spark 에이전트·Samsung XR 글라스·Antigravity 플랫폼이 공개됐습니다. NVIDIA가 Q1 FY2027 매출 $391억(+73% YoY)으로 어닝 서프라이즈를 기록했고, Anthropic은 $900억+ 밸류에이션 투자 라운드 월말 클로징을 앞두고 있습니다.',
    items: [
      { weight: 'high', time: '10:00', source: 'Google / TechRadar',
        headline: 'Google I/O 2026 개발자 키노트 — Gemini Spark·Samsung XR 글라스·Antigravity 공식 공개',
        url: 'https://www.techradar.com/news/live/google-io-2026-live',
        bullets: [
          'Gemini Spark 베타: Gemini 앱에서 앱 간 정보 추론·자율 태스크 수행 에이전트. AI Ultra 구독자($100/월) 우선 출시.',
          'Samsung XR 글라스 공식 프리뷰: Gemini 구동·올가을 출시. Warby Parker·Gentle Monster 협력 디자인.',
          'Antigravity 에이전트 개발 플랫폼 업그레이드: 복합 AI 에이전트 오케스트레이션·멀티스텝 빌드 지원 강화.',
        ],
        why: 'Gemini Spark는 구글이 AI를 "앱 내 기능"에서 "앱을 가로지르는 에이전트"로 격상시킨 제품입니다.',
        notes: [
          { term: 'Gemini Spark', def: 'Google의 범용 AI 에이전트. 연결된 앱 간 정보를 추론해 멀티스텝 작업 자율 수행.' },
          { term: 'Antigravity', def: 'Google의 에이전트 우선 개발 플랫폼. 복잡한 AI 에이전트를 빌드·오케스트레이션.' },
        ] },
      { weight: 'high', time: '22:00', source: 'NVIDIA Newsroom',
        headline: 'NVIDIA Q1 FY2027 어닝 서프라이즈 — 매출 $391억(+73% YoY)·EPS $0.81(컨센서스 8% 상회)',
        url: 'https://nvidianews.nvidia.com/news/nvidia-announces-financial-results-for-first-quarter-fiscal-2026',
        bullets: [
          'NVIDIA Q1 FY2027 매출 $391억(+73% YoY, +10% QoQ). EPS $0.81(컨센서스 $0.75 대비 8% 상회).',
          'H20 중국 수출 제재로 $45억 재고 손실 반영. 제재 제외 조정 EPS $0.96.',
          'Q2 가이던스 $450억(H20 손실 $80억 흡수). 비GAAP 매출총이익률 72% 회복 전망. Jensen Huang "AI 인프라 수요 매우 강력".',
        ],
        why: 'NVIDIA 어닝 서프라이즈는 AI 인프라 투자 사이클이 꺾이지 않았음을 확인하며 한국 반도체 수출에도 호재입니다.',
        notes: [
          { term: 'H20', def: 'NVIDIA의 중국 수출 허용 AI 칩. 2026년 4월 미국 정부가 새 수출 라이선스 요건 부과.' },
          { term: 'FY2027', def: 'NVIDIA 회계연도 2027. 캘린더상 2026년 2월~2027년 1월.' },
        ] },
      { weight: 'low', time: '08:00', source: 'Bloomberg / Sequoia',
        headline: 'Anthropic $900억+ 밸류에이션 $300억 라운드 월말 클로징 — OpenAI 밸류에이션 추월',
        url: 'https://fortune.com/2026/05/13/behold-the-googlebook/',
        bullets: [
          'Anthropic $300억 투자 라운드 5월 말 클로징 예정. Sequoia·Dragoneer·Greenoaks·Altimeter 공동 리드.',
          '밸류에이션 $900억+ — OpenAI 3월 $852억 첫 추월. Q1 매출 전년 대비 80배 성장, ARR $440억 돌파.',
        ], why: '', notes: [] },
      { weight: 'low', time: '09:00', source: 'Google',
        headline: 'Google, Gemini 3.5 Flash 출시 — 경쟁 모델 대비 절반 가격·즉시 사용 가능',
        url: 'https://www.cnbc.com/2026/05/19/google-ai-ultra-gemini-spark-omni.html',
        bullets: [
          'Google, Gemini 3.5 Flash 공개. 프론티어 모델 대비 절반~1/3 가격으로 경량화 강점.',
          'I/O 2026 발표 모델 중 가장 즉시 사용 가능. API 개발자·기업 채택 타겟.',
        ], why: '', notes: [] },
      { weight: 'low', time: '07:00', source: 'OpenAI / TechCrunch',
        headline: 'GPT-5.5 Instant 메모리 통합 업데이트 — 법률·의학 환각 52.5% 감소',
        url: 'https://techcrunch.com/2026/05/05/openai-releases-gpt-5-5-instant-a-new-default-model-for-chatgpt/',
        bullets: [
          'GPT-5.5 Instant, 메모리 통합·멀티모달 추론 강화 업데이트. 고위험 프롬프트 환각 52.5% 감소.',
          'AIME 2025 수학 81.2점·MMMU-Pro 76점. ChatGPT 기본 모델 유지.',
        ], why: '', notes: [] },
      { weight: 'low', time: '11:00', source: 'RD World Online',
        headline: '필즈상 수상 수학자 "GPT-5.5 Pro, 박사급 수학 1시간 내 해결" 공개 인증',
        url: 'https://www.rdworldonline.com/this-week-in-ai-research-fields-medalist-says-gpt-5-5-pro-did-phd-level-math-in-an-hour-anthropic-teaches-claude-to-dream/',
        bullets: [
          '필즈상 수상 수학자, GPT-5.5 Pro가 박사급 수학 문제 1시간 내 해결했다고 공개 인증.',
          'Anthropic도 Claude "Dreaming" 기능(이전 세션 누적 기억) 연구 공개.',
        ], why: '', notes: [] },
      { weight: 'low', time: '08:30', source: 'VTNetzwelt',
        headline: 'Claude Opus 4.7·GPT-5.5, 정가 인상 없이 기업 실질 비용 상승 — AI 비용 역설',
        url: 'https://www.vtnetzwelt.com/ai-development/latest-ai-technology-news-roundup-may-2026/',
        bullets: [
          'Claude Opus 4.7·GPT-5.5, 정가 유지에도 캐싱 요건·최소 컨텍스트 변경으로 기업 실질 비용 상승.',
          '대형 모델 비용 최적화가 기업 AI 도입 최대 과제로 부상.',
        ], why: '', notes: [] },
      { weight: 'low', time: '06:30', source: 'Creati AI',
        headline: 'OpenAI GPT-5.5 Cyber, 사이버보안 팀 공개 테스트 — Anthropic Mythos급 접근',
        url: 'https://creati.ai/ai-news/2026-05-01/gpt-5-5-cyber-tests-put-openai-near-anthropic-mythos/',
        bullets: [
          'OpenAI, 심층 사이버보안 팀에 GPT-5.5 Cyber 공개 배포. 취약점 분석·침투 테스트 보조.',
          '평가 결과 Anthropic Mythos급 사이버 역량에 근접. 보안 AI 경쟁 본격화.',
        ], why: '', notes: [] },
    ],
  },
  physical: {
    label: '피지컬 AI 뉴스',
    summary: 'AGIBOT이 홍콩에서 첫 피지컬 AI 서밋을 개최해 A·X·G·D·C 풀 포트폴리오를 공개했습니다. 2026 피지컬 AI 대형 모델 보고서에 따르면 세계 모델이 로봇 학습 표준으로 자리잡고 OEM 완성차 업체가 직접 양산에 진입하고 있습니다.',
    items: [
      { weight: 'high', time: '10:00', source: 'AGIBOT / PRNewswire',
        headline: 'AGIBOT, 홍콩 피지컬 AI 서밋 개최 — A·X·G·D·C 시리즈 풀 포트폴리오 공개',
        url: 'https://www.prnewswire.com/apac/news-releases/the-first-hong-kong-embodied-ai-industry-summit-and-agibot-partner-conference-2026-hong-kong-opens-302770944.html',
        bullets: [
          'AGIBOT 홍콩 첫 피지컬 AI 서밋·파트너 컨퍼런스. 풀사이즈 A시리즈·반사이즈 X시리즈·휠드 G시리즈·4족 D시리즈·청소 C시리즈 공개.',
          '물류 분류·소매 안내·생산 라인 적재 등 다중 산업 데모.',
          '홍콩을 중국 피지컬 AI 기업의 글로벌 파트너십 허브로 선언.',
        ],
        why: 'AGIBOT의 풀 포트폴리오 공개는 중국 피지컬 AI 기업이 산업별 특화 제품 라인업을 완성했음을 의미합니다.',
        notes: [
          { term: 'AGIBOT', def: '중국 피지컬 AI 스타트업. 화웨이 전 임원 창업. 다양한 형태의 로봇 포트폴리오 보유.' },
          { term: '휠드 휴머노이드', def: '다리 대신 바퀴를 사용하는 휴머노이드 타입. 이동 효율성·안정성 높음.' },
        ] },
      { weight: 'high', time: '09:00', source: 'GlobeNewswire',
        headline: '2026 피지컬 AI 대형 모델 보고서 — 세계 모델 표준화·OEM 양산 진입 가속',
        url: 'https://www.globenewswire.com/news-release/2026/05/13/3293694/28124/en/Embodied-AI-Robot-Large-Model-Including-VLA-Research-Report-2026-World-Models-Are-About-to-Become-Standard-and-OEMs-Enter-and-Accelerate-Mass-Production-and-Application.html',
        bullets: [
          '2026 피지컬 AI·로봇 VLA 모델 보고서. 세계 모델이 로봇 학습 표준화 임박, OEM 완성차 업체 양산 직접 진입.',
          'Q1 2026 세계 모델 6~7개사에 $60억 집중 투자. 합성 데이터로 훈련 비용 혁신.',
          '자율주행·산업 자동화·가정용 로봇 수렴 가속. 2027년 본격 양산 시대 전망.',
        ],
        why: '세계 모델 표준화는 로봇 AI의 ChatGPT 모멘트를 예고합니다.',
        notes: [
          { term: 'VLA (Vision-Language-Action)', def: '시각·언어·행동을 통합하는 로봇 AI 모델.' },
          { term: '세계 모델(World Model)', def: '물리 환경을 시뮬레이션해 로봇 훈련 데이터를 합성 생성하는 AI 모델.' },
        ] },
      { weight: 'low', time: '07:00', source: 'Figure AI',
        headline: 'Figure AI, Helix 02·24/7 자율 운영 2026 목표 이정표 공개',
        url: 'https://vfuturemedia.com/future-tech/humanoid-robots-enter-the-workforce-figure-boston-dynamics-and-tesla-optimus-2026/',
        bullets: [
          'Figure AI 2026 핵심 목표: Helix 02 전신 AI·24시간 7일 자율 운영 데모·가정용 장기 태스크 파일럿.',
          'Figure 03, BMW 공장 30,000대 이상 지원. 1,250시간·90,000+ 부품 처리 달성.',
        ], why: '', notes: [] },
      { weight: 'low', time: '08:00', source: "People's Daily",
        headline: '중국 피지컬 AI 로봇, 고위험 산업 현장 진입 — 핵발전소·광산 배치',
        url: 'https://en.people.cn/n3/2026/0506/c90000-20453012.html',
        bullets: [
          '중국 피지컬 AI 로봇, 핵발전소·광산·화학 공장 등 고위험 현장 투입 확대.',
          '정부 주도 5개년 계획 로봇 안전 규정 정비 동시 진행.',
        ], why: '', notes: [] },
      { weight: 'low', time: '11:00', source: 'arxiv / SAE',
        headline: 'SAE World Congress 2026 — 피지컬 AI 안전·신뢰·거버넌스 논의',
        url: 'https://arxiv.org/html/2605.10653v1',
        bullets: [
          'SAE World Congress 2026, 피지컬 AI 안전·신뢰·거버넌스 전용 트랙 신설.',
          '자율주행·산업 로봇·드론의 시스템 도전으로 통합 접근 필요성 합의.',
        ], why: '', notes: [] },
      { weight: 'low', time: '06:00', source: 'RobotToday',
        headline: 'Boston Dynamics IPO $1,000억 밸류에이션 추진 — Tesla·Figure AI와 3파전',
        url: 'https://robottoday.com/article/boston-dynamics-ipo-and-100-b-valuation-how-it-compares-to-tesla-optimus-figure-ai-and-humanoid-rivals',
        bullets: [
          'Boston Dynamics IPO $1,000억 밸류에이션 추진. Atlas 2026 전량 납품 확정이 상장 기반.',
          'Tesla Optimus·Figure AI와 밸류에이션 3파전 구도.',
        ], why: '', notes: [] },
      { weight: 'low', time: '09:30', source: 'Neware / Tesla',
        headline: 'Tesla Optimus Gen 3 스펙 확정 — 관절 37개·1.2m/s·AI5 온보드',
        url: 'https://www.neware.net/news/tesla-optimus-gen-3-the-new-era-of-humanoid-robots/230/191.html',
        bullets: [
          'Tesla Optimus Gen 3 스펙: 관절 37개(+9), 보행 속도 1.2m/s, AI5 온보드 컴퓨팅.',
          '2026년 여름 프리몬트 저량 생산. 공장 자체가 첫 고객.',
        ], why: '', notes: [] },
      { weight: 'low', time: '10:30', source: 'KraneShares',
        headline: '피지컬 AI 투자: 세계 모델 $60억·생산 확장·소프트웨어 플랫폼 3단계 전략',
        url: 'https://kraneshares.com/humanoid-robotics-in-2026-the-race-from-pilot-to-platform/',
        bullets: [
          'Q1 2026 세계 모델 기업 6~7개사에 $60억 투자. Figure AI·PI·1X 포함.',
          '투자 3단계: ①세계 모델(합성 데이터) ②생산 확장 ③소프트웨어 플랫폼(SaaS화).',
        ], why: '', notes: [] },
    ],
  },
  quantum: {
    label: '양자 뉴스',
    summary: 'Q-Day 경고가 이어지는 가운데 기업 양자 내성 암호 전환율은 여전히 12%에 불과합니다. IBM·Q-CTRL이 120큐비트에서 페르미-후버드 모델 3,000배 가속을 달성했고, Microsoft·Quantinuum이 환경 변화 없이 큐비트 오류를 감지하는 새 기술을 공개했습니다.',
    items: [
      { weight: 'high', time: '09:00', source: 'CNN / Cybersecurity Roundup',
        headline: 'Q-Day 위협 가속 — 기업 전환율 12%, NSA 2027년 강제 기한',
        url: 'https://hipther.com/latest-news/2026/05/18/111874/cybersecurity-roundup-partnerships-funding-and-emerging-threats-may-18-2026-quantum-q-day-email-identity-risk-wef-cybersecurity-dragos-uae-cyber-security-council-and-n2k-cyberwire/',
        bullets: [
          '기업 양자 내성 암호 전환율 12%. NIST 표준화 완료에도 이행 극히 부진.',
          'NSA CNSA 2.0: 신규 국가안보 시스템 2027년 1월까지 양자 안전 의무화.',
          '국가 행위자·해커 HNDL(지금 탈취, 나중에 복호화) 캠페인 광범위 진행 중.',
        ],
        why: 'NSA 2027년 기한과 HNDL 위협은 기업과 정부의 즉각적 전환을 강제합니다.',
        notes: [
          { term: 'HNDL', def: '지금 암호화 데이터를 탈취해 미래 양자컴퓨터로 복호화하는 공격 전략.' },
          { term: 'CNSA 2.0', def: 'NSA의 양자 내성 암호 표준 스위트 2.0.' },
        ] },
      { weight: 'high', time: '08:00', source: 'IBM / Q-CTRL',
        headline: 'IBM·Q-CTRL, Fire Opal로 페르미-후버드 3,000배 가속 — 실용적 양자 우위',
        url: 'https://quantumcomputingreport.com/news/',
        bullets: [
          'IBM·Q-CTRL, Fire Opal 오류 억제로 120큐비트 페르미-후버드 모델 시뮬레이션 3,000배 가속.',
          '기존 클래식 대비 실용적 양자 우위 첫 입증. 재료과학·신약 연구 응용 직결.',
          'AWS·Azure·Google Cloud 전 채널 Fire Opal 통합 예정.',
        ],
        why: '3,000배 가속은 실제 산업 문제에서의 양자 우위 첫 입증으로 상용화 타임라인을 앞당깁니다.',
        notes: [
          { term: '페르미-후버드 모델', def: '강상관 전자 시스템 물리 모델. 고온 초전도체·신소재 이해에 핵심.' },
          { term: 'Fire Opal', def: 'Q-CTRL의 양자 오류 억제 소프트웨어.' },
        ] },
      { weight: 'low', time: '07:00', source: 'Microsoft / Quantinuum',
        headline: 'Microsoft·Quantinuum, 큐비트 오류 확인 혁신 — 환경 변화 없이 감지',
        url: 'https://quantumcomputingreport.com/news/',
        bullets: [
          'Microsoft·Quantinuum, 큐비트 환경 변화 없이 오류 확인하는 새 방법 개발.',
          '양자 오류 수정 실용화의 핵심 장벽 제거.',
        ], why: '', notes: [] },
      { weight: 'low', time: '06:00', source: 'Microsoft / Atom Computing',
        headline: 'Microsoft·Atom Computing, Magne 50 논리 큐비트 — 2027년 상업 납품',
        url: 'https://quantumcomputingreport.com/news/',
        bullets: [
          'Microsoft·Atom Computing, Magne(50 논리 큐비트·물리 큐비트 1,200개) 덴마크 납품 계약.',
          '오류수정 양자컴퓨터 최초 상업 납품 사례. 2027년 초 인도.',
        ], why: '', notes: [] },
      { weight: 'low', time: '10:00', source: 'IEEE Spectrum',
        headline: '중성 원자 양자컴퓨팅 2026 대약진 — 게이트 충실도 99.9% 돌파',
        url: 'https://spectrum.ieee.org/neutral-atom-quantum-computing',
        bullets: [
          '중성 원자 양자컴퓨팅 게이트 충실도 99.9% 달성 연구 잇따라.',
          '이온트랩과 경쟁에서 규모 확장성 강점으로 재부상.',
        ], why: '', notes: [] },
      { weight: 'low', time: '11:00', source: 'Google Quantum AI',
        headline: 'Google Quantum Echoes — Willow 칩, 클래식 슈퍼컴퓨터 대비 13,000배 속도',
        url: 'https://quantumcomputingreport.com/news/',
        bullets: [
          'Google, Quantum Echoes 알고리즘으로 Willow에서 클래식 슈퍼컴퓨터 13,000배 속도 검증.',
          '검증 가능한 양자 우위 첫 공식 발표.',
        ], why: '', notes: [] },
      { weight: 'low', time: '08:30', source: 'Quantinuum / BMW',
        headline: 'Quantinuum IPO S-1 후 BMW 다년 파트너십 확장 — 배터리·연료전지 시뮬레이션',
        url: 'https://www.quantinuum.com/press-releases/quantinuum-and-bmw-group-expand-landmark-quantum-computing-collaboration-with-new-multi-year-partnership',
        bullets: [
          'Quantinuum, BMW와 다년 배터리·연료전지 재료 양자 시뮬레이션 파트너십 확장.',
          'IPO S-1 공개 후 첫 대형 계약. 양자 기업 상장 추진 신뢰 확인.',
        ], why: '', notes: [] },
      { weight: 'low', time: '09:30', source: 'SecurityWeek',
        headline: '양자·AI 시너지 보안 위협 2026 — 패치 속도보다 빠른 양자 공격 가능성',
        url: 'https://www.securityweek.com/cyber-insights-2026-quantum-computing-and-the-potential-synergy-with-advanced-ai/',
        bullets: [
          '2026 사이버 인사이트: 양자+고급 AI 시너지로 기존 보안 패치 속도보다 빠른 공격 현실화 가능성.',
          '기업 SOC에 양자 위협 대응 레이어 추가 권고.',
        ], why: '', notes: [] },
    ],
  },
  econ: {
    label: '경제 뉴스',
    summary: 'NVIDIA 어닝 서프라이즈가 AI 인프라 투자 사이클 지속을 확인했으나, 미국 30년 국채가 5.197%로 2007년 이후 최고치를 기록하며 채권시장 발작이 계속됩니다. KOSPI는 NVIDIA 기대감과 삼성 파업 협상 진전에 힘입어 반등했고, 달러-원 환율은 1,492원으로 소폭 안정됐습니다.',
    items: [
      { weight: 'high', time: '22:00', source: 'NVIDIA / CNBC',
        headline: 'NVIDIA Q1 FY2027 어닝 서프라이즈 — 매출 $391억, Q2 가이던스 $450억',
        url: 'https://www.indexbox.io/blog/nvidia-q1-2026-earnings-preview-strong-ai-demand-points-to-upside/',
        bullets: [
          'NVIDIA Q1 FY2027 매출 $391억(컨센서스 상회). EPS $0.81(컨센서스 $0.75 대비 8% 상회).',
          'H20 수출 제재 $45억 손실 반영에도 어닝 서프라이즈. Q2 가이던스 $450억.',
          '시간외 NVDA +8%. SK하이닉스·삼성전자 동반 강세 전망. AI 인프라 수요 건재 확인.',
        ],
        why: 'NVIDIA 어닝 서프라이즈는 AI 인프라 투자 사이클이 꺾이지 않았음을 확인하며 한국 반도체 수출에 호재입니다.',
        notes: [{ term: 'FY2027', def: 'NVIDIA 회계연도 2027. 캘린더상 2026년 2월~2027년 1월.' }] },
      { weight: 'high', time: '09:00', source: 'CNBC / Bloomberg',
        headline: '미국 30년 국채 5.197% — 2007년 이후 최고치, 채권시장 발작 지속',
        url: 'https://www.cnbc.com/2026/05/19/treasurys-yields-inflation-traders-fed-interest-rates.html',
        bullets: [
          '미국 30년 국채 금리 5.197%(5/19 기록). 2007년 금융위기 이전 이후 최고. 10년물 4.67%.',
          '4월 PPI +6%(전년 대비). CPI 3.8%·근원 2.8%. 인플레 재점화 우려.',
          'S&P 500 3거래일 연속 하락. 채권 금리 상승이 성장주 할인율 압박.',
        ],
        why: '30년물 5.197%는 채권시장이 워시 연준의 고금리 장기화를 가격에 반영하고 있음을 의미합니다.',
        notes: [{ term: 'PPI', def: '생산자물가지수. 기업이 받는 평균 가격 변화. CPI의 선행 지표.' }] },
      { weight: 'low', time: '10:00', source: '한국거래소',
        headline: 'KOSPI 7,520 반등 — NVIDIA 어닝 기대·삼성 파업 협상 진전 호재',
        url: '',
        bullets: [
          'KOSPI 7,520(+1.27%). NVIDIA 실적 기대감에 SK하이닉스·삼성전자 동반 강세.',
          '삼성전자 노사 추가 협상 진행. 파업 제한 가처분 효력 유지.',
        ], why: '', notes: [] },
      { weight: 'low', time: '08:00', source: '한국은행',
        headline: '달러-원 1,492원 — 1,501원 피크 후 소폭 안정, 1,500원 저항선 주목',
        url: '',
        bullets: [
          '달러-원 1,492원(-0.60%). 1,501원 고점 이후 소폭 하락 안정.',
          'KOSPI 반등·외국인 순매수가 원화 강세 지지. 한국은행 구두 개입 경계 지속.',
        ], why: '', notes: [] },
      { weight: 'low', time: '07:00', source: 'Reuters',
        headline: 'WTI $104.10 소폭 반등 — 이란 협상 교착·글로벌 경기 우려 상충',
        url: '',
        bullets: [
          'WTI $104.10(+0.87%). 이란 호르무즈 협상 교착 지속으로 공급 우려 반등.',
          '글로벌 경기 둔화 우려가 상방 제한. $100~$110 박스권 유지 전망.',
        ], why: '', notes: [] },
      { weight: 'low', time: '06:00', source: 'CME FedWatch / TheStreet',
        headline: '연내 연준 금리 인상 확률 40%+ — 케빈 워시 첫 FOMC 6월 16-17일',
        url: 'https://www.thestreet.com/fed/major-bank-drops-bombshell-on-fed-interest-rate-bets-despite-bond-market-warnings-of-upcoming-hikes',
        bullets: [
          'CME FedWatch 연내 연준 금리 인상 확률 40%+. 6월 16-17일 워시 취임 후 첫 FOMC.',
          'BNP파리바, 연준 금리 인하 전망 전면 리셋. 2027년 이후 첫 인하 컨센서스 강화.',
        ], why: '', notes: [] },
      { weight: 'low', time: '09:30', source: 'Citi / JP Morgan',
        headline: '삼성전자 파업 손실 추정 하향 — Citi·JP모간 목표가 유지',
        url: 'https://www.tradingkey.com/analysis/stocks/us-stocks/261894303-samsung-strike-micron-sk-hynix-south-korea-memory-chip-memory-tradingkey',
        bullets: [
          'Citi, 삼성 파업 손실 추정 하향. 법원 파업 제한 가처분 효력 지속 반영.',
          'JP모간 목표가 35만원 유지. NVIDIA 어닝 수혜로 HBM4 납품 전망 개선.',
        ], why: '', notes: [] },
      { weight: 'low', time: '11:00', source: 'KDI',
        headline: '한국 반도체·AI 수출 5월 견조 — 성장률 2.5% 조건 충족 중',
        url: '',
        bullets: [
          'KDI 5월 주간 점검: 반도체·AI 수출 견조. NVIDIA 실적 수혜로 HBM 수출 호조 유지.',
          '리스크: 이란 에너지 장기화·워시 연준 고금리·USD/KRW 1,500원 재돌파 여부.',
        ], why: '', notes: [] },
    ],
  },
  columns: {
    label: '컬럼 피드',
    summary: '오건영 단장은 NVIDIA 실적 서프라이즈를 단기 반등 계기로 보면서도, 미국 30년 국채 5.197% 채권발작과 워시 연준 매파 기조가 주식시장 구조적 상방을 제한한다고 분석했습니다.',
    items: [
      { name: '오건영', title: '신한은행 · 디지털 크리에이터', avatar: 'OG', color: '#D97757',
        time: '오늘 08:00', likes: 0, comments: 0,
        post: '오늘 오후 NVIDIA 실적 발표가 예정되어 있습니다. 컨센서스를 크게 상회하는 어닝 서프라이즈가 나왔습니다. 단기적으로 반도체·AI 섹터의 반등 트리거가 될 수 있습니다. 그러나 미국 30년 국채 금리가 5.197%로 2007년 이후 최고치를 기록하고 있다는 점을 잊어서는 안 됩니다. 채권시장 발작의 배경은 세 가지입니다. 첫째, 이란 호르무즈 긴장에 따른 에너지 가격 상승. 둘째, 미국 재정 적자 확대와 국채 발행 증가. 셋째, 케빈 워시 연준의 물가 2% 달성 전 인하 불가 원칙. NVIDIA 서프라이즈는 분명 긍정적 신호이지만, 채권 금리 환경이 바뀌지 않는 한 주식시장의 구조적 상방 압력은 제한됩니다.',
        summary: 'NVIDIA 어닝 서프라이즈 단기 호재이나, 미국 30년 국채 5.197% 채권발작·워시 연준 매파 기조로 주식시장 구조적 상방 제한.',
      },
    ],
  },
  invest: {
    title: 'NVIDIA 서프라이즈·채권발작 공존',
    subtitle: 'Claude가 작성한 오늘의 메모 · 5월 20일 09:00 · 5분 읽기',
    sections: [
      { h: '한 줄 요약', body: 'NVIDIA Q1 FY2027 어닝 서프라이즈(매출 $391억, +73%)로 AI 인프라 투자 사이클이 건재함을 확인했으나, 미국 30년 국채 5.197%·연내 금리 인상 확률 40%+로 채권시장 발작이 동시에 진행 중입니다.' },
      { h: '오늘의 변수', body: '①NVIDIA 실적 서프라이즈 — 장 마감 후 발표, 내일 아시아 시장 반응 주목. ②미국 30년 국채 5.197% — 채권 발작 지속, 6/16-17 FOMC 경계. ③달러-원 1,492원 — 1,500원 재돌파 여부 핵심. ④삼성전자 파업 협상 추가 진행 중. ⑤Google I/O 2일차 Gemini Spark 개발자 반응.' },
      { h: '포지셔닝', body: '단기(1-3개월): NVIDIA 어닝 서프라이즈로 SK하이닉스·삼성전자 비중 소폭 확대. 금(GLD) 25% 유지 — 이란·채권발작 헤지. 배당주(VYM) 20% — 고금리 방어. 채권(TLT) 5% 최소화. 중기(6-12개월): NVIDIA 주도 AI 인프라 섹터 점진 비중 확대. 6/17 FOMC 결과 확인 후 채권 재조정.' },
      { h: '리스크', body: 'H20 수출 제재 지속으로 중국 매출 회복 불확실. 30년 국채 5.5%+ 돌파 시 주식시장 전면 조정. 삼성전자 파업 긴급조정권 발동 실패 시 재개. 워시 6/17 FOMC 금리 인상 선언 시 글로벌 자산 동반 급락.' },
    ],
    watchlist: [
      { sym: 'NVDA',   name: 'NVIDIA',      val: '$241.80',   pct: '+6.61%', up: true,  note: 'Q1 FY2027 어닝 서프라이즈 — 시간외 급등, AI 인프라 수요 확인' },
      { sym: '000660', name: 'SK하이닉스',  val: '1,988,000', pct: '+1.17%', up: true,  note: 'NVIDIA 수혜 HBM 공급사 — 어닝 서프라이즈 낙수 효과' },
      { sym: '005930', name: '삼성전자',    val: '287,500',   pct: '+0.88%', up: true,  note: 'NVIDIA 호재·파업 협상 진전 — 반등 시도' },
      { sym: 'GOOGL',  name: 'Alphabet',    val: '$197.20',   pct: '+1.39%', up: true,  note: 'I/O 2일차 Gemini Spark 개발자 반응 주목' },
      { sym: 'GLD',    name: 'SPDR Gold',   val: '$254.90',   pct: '-0.20%', up: false, note: '이란·채권발작 헤지 — NVIDIA 리스크온으로 소폭 조정' },
      { sym: 'TLT',    name: 'iShares 20Y', val: '$85.90',    pct: '-1.15%', up: false, note: '30년 국채 5.197% — 채권 발작 계속, 최소화 유지' },
      { sym: 'VYM',    name: 'Vanguard HY', val: '$131.50',   pct: '+0.38%', up: true,  note: '고금리 방어 포지션 — 소폭 반등' },
      { sym: 'BTC',    name: 'Bitcoin',     val: '$76,984',   pct: '+0.23%', up: true,  note: '리스크온 소폭 수혜 — $78K 저항선 주목' },
    ],
    portfolio: [
      { asset: '국내주식', pct: 20, color: '#3DDC97',
        tickers: [{ sym: '000660', name: 'SK하이닉스' }, { sym: '005930', name: '삼성전자' }],
        note: 'NVIDIA 어닝 수혜 — 비중 소폭 확대, SK하이닉스 집중' },
      { asset: '미국주식', pct: 22, color: '#5B9BD5',
        tickers: [{ sym: 'NVDA', name: 'NVIDIA' }, { sym: 'GOOGL', name: 'Alphabet' }],
        note: '실적 서프라이즈 확인 — NVDA 비중 확대' },
      { asset: '채권', pct: 5, color: '#9B8EC4',
        tickers: [{ sym: 'TLT', name: 'iShares 20Y ETF' }],
        note: '30년 국채 5.197% 채권발작 — 최소화 유지' },
      { asset: '금', pct: 25, color: '#F5C518',
        tickers: [{ sym: 'GLD', name: 'SPDR Gold ETF' }],
        note: '이란·채권발작 헤지 — NVIDIA 리스크온으로 소폭 축소' },
      { asset: '배당주', pct: 20, color: '#E08A6E',
        tickers: [{ sym: 'VYM', name: 'Vanguard High Div.' }],
        note: '고금리 환경 방어 — 비중 유지' },
      { asset: '비트코인', pct: 8, color: '#F7931A',
        tickers: [{ sym: 'BTC', name: 'Bitcoin' }],
        note: '$78K 저항선 주목 — 소폭 비중 축소' },
    ],
  },
});



const TODAY = {
  date: { iso: '2026-05-22', label: '2026년 5월 22일 금요일', shortLabel: '5월 22일 (금)', isToday: true },
  marketStrip: [
    { sym: 'KOSPI',   val: '7,615',   pct: '+0.46%', up: true  },
    { sym: 'S&P 500', val: '7,445',   pct: '+0.17%', up: true  },
    { sym: 'NASDAQ',  val: '26,293',  pct: '+0.29%', up: true  },
    { sym: 'BTC',     val: '$77,630', pct: '-0.07%', up: false },
    { sym: '$/₩',    val: '1,504',   pct: '+0.47%', up: true  },
    { sym: '10Y UST', val: '4.60%',  pct: '-7bp',   up: false },
    { sym: 'WTI',     val: '$101.07', pct: '+3.85%', up: true  },
  ],
  ai: {
    label: 'AI 뉴스',
    summary: 'Google이 Genie 3 월드 모델과 Street View를 결합해 실제 장소를 탐색 가능한 AI 세계로 만드는 기능을 공개했습니다. OpenAI가 YC 배치 스타트업에 $2M 토큰 투자를 제안하며 생태계 확장에 나섰고, Gemini 3.5 Flash의 비용 문제가 수면 위로 떠오르는 등 AI 경쟁이 심화됐습니다.',
    items: [
      { weight: 'high', time: '09:00', source: 'Google DeepMind / The Decoder',
        headline: 'Google Genie 3 + Street View — 실제 장소 기반 탐색 가능 AI 세계 생성',
        url: 'https://the-decoder.com/google-pairs-its-genie-world-model-with-street-view-to-create-explorable-ai-worlds-based-on-real-places/',
        bullets: [
          'Google DeepMind, Genie 3 월드 모델과 Street View 결합. 지도 핀 하나로 실제 장소를 탐색 가능한 AI 세계로 변환.',
          'Street View 수십억 장 이미지 데이터 + Genie 3의 실시간 세계 생성 능력 통합.',
          '게임·VR·부동산·관광 업계 응용 가능성 무한. 구글의 AI 세계 구축 전략 가속.',
        ],
        why: '가상 세계가 현실 데이터를 기반으로 생성되면 지식 표현·훈련 데이터 생성·로봇 시뮬레이션 전반에 패러다임 변화를 가져옵니다.',
        notes: [
          { term: 'Genie 3', def: 'Google DeepMind의 AI 세계 모델. 단일 이미지에서 인터랙티브 3D 세계를 자동 생성.' },
          { term: '월드 모델', def: 'AI가 물리적 세계를 내부적으로 시뮬레이션하는 능력. 로봇 훈련·게임·자율주행에 핵심.' },
        ] },
      { weight: 'high', time: '10:00', source: 'OpenAI / The Information',
        headline: 'OpenAI, YC 배치 스타트업 전체에 $2M 토큰 투자 제안 — SAFE 지분 교환',
        url: 'https://llm-stats.com/ai-news',
        bullets: [
          'Sam Altman, 현 YC 배치 스타트업 전체에 $2M OpenAI 토큰 투자 제안. SAFE를 통한 지분 취득 조건.',
          'OpenAI, 스타트업 생태계 AI 스택 장악 전략. AWS·Azure 스타트업 프로그램과 직접 경쟁.',
          '일부 스타트업 "지분 조건 부담" 반발. AI 인프라 패권 경쟁의 새 전선.',
        ],
        why: 'OpenAI가 YC 생태계를 선점하면 차세대 스타트업의 AI 스택이 OpenAI 중심으로 고착화될 수 있습니다.',
        notes: [
          { term: 'SAFE', def: 'Simple Agreement for Future Equity. 스타트업 초기 투자 시 사용하는 미래 지분 취득 계약.' },
          { term: 'YC(Y Combinator)', def: '세계 최대 스타트업 액셀러레이터. Airbnb·Stripe·Dropbox 등 배출.' },
        ] },
      { weight: 'high', time: '08:00', source: 'The Decoder / Google',
        headline: 'Gemini 3.5 Flash — 전임 대비 5.5배 비용, 에이전트 작업에서 Pro보다 75% 고가',
        url: 'https://the-decoder.com/googles-gemini-3-5-flash-follows-anthropic-and-openai-in-making-newer-ai-models-significantly-pricier/',
        bullets: [
          'Gemini 3.5 Flash, 실제 에이전트 작업 비용이 전임 Gemini 2.5 Flash 대비 5.5배 증가.',
          '에이전트 작업에서 Gemini 3.1 Pro보다 75% 비싸다는 벤치마크 결과 공개.',
          'OpenAI·Anthropic도 신모델 가격 인상 추세. AI 모델 "프리미엄화"가 업계 트렌드로 정착.',
        ],
        why: 'AI 모델 가격 인상 추세는 기업 AI 예산을 직접 압박하며 저비용 대안 수요를 높이고 오픈소스 모델 경쟁을 가속시킵니다.',
        notes: [
          { term: 'token 단가', def: 'AI API 과금 기준. 입력·출력 텍스트 1,000토큰당 달러로 표시.' },
        ] },
      { weight: 'low', time: '07:00', source: 'TechXplore',
        headline: 'AI 불안감 미국 확산 — 졸업식 야유·유권자 데이터센터 반발',
        url: 'https://techxplore.com/news/2026-05-graduation-boos-voter-unease-ai.html',
        bullets: [
          'AI 홍보 연사 대학 졸업식에서 야유. 유권자들이 AI 데이터센터 지역 건설에 반발 시위.',
          'AI 친화 트럼프 행정부 관계자들도 AI 속도에 후퇴 조짐. 사회적 AI 피로감 확산.',
        ], why: '', notes: [] },
      { weight: 'low', time: '11:00', source: 'Financial Times',
        headline: '중국, Nvidia RTX 5090D V2 칩 금지 — 젠슨 황 방중 주간 발표',
        url: 'https://llm-stats.com/ai-news',
        bullets: [
          '중국 당국, 게이머·애니메이터용 Nvidia RTX 5090D V2 칩 수입 금지. 중국 AI 기업 지원 차단 의도.',
          '젠슨 황이 트럼프와 함께 중국 방문한 주간에 발표. 미중 AI 칩 갈등 심화.',
        ], why: '', notes: [] },
      { weight: 'low', time: '09:00', source: 'Reuters',
        headline: 'Russia Sberbank GigaChat, 중국 칩으로 전환 시도 — 서방 제재 우회',
        url: 'https://llm-stats.com/ai-news',
        bullets: [
          '러시아 최대 은행 Sberbank, 자체 AI 모델 GigaChat 구동을 중국 AI 칩으로 전환 희망.',
          '중국-러시아 AI 기술 협력 심화. 제재 우회 생태계 형성 우려.',
        ], why: '', notes: [] },
      { weight: 'low', time: '06:00', source: 'Techmeme / The Register',
        headline: 'Google Cloud, Railway PaaS 계정 무단 정지 논란',
        url: 'https://llm-stats.com/ai-news',
        bullets: [
          'PaaS 플랫폼 Railway, Google Cloud가 사전 통보 없이 계정 정지. 서비스 중단 위기.',
          '2024년 호주 연금 기금 계정 삭제 사건 재연. 클라우드 플랫폼 신뢰성 논란.',
        ], why: '', notes: [] },
      { weight: 'low', time: '08:00', source: 'Axios / Bloomberg',
        headline: 'Anthropic ARR $190억·OpenAI $250억 — 구글 AI 전쟁 삼파전 심화',
        url: 'https://www.axios.com/2026/05/21/google-ai-anthropic-openai-war',
        bullets: [
          'Anthropic 연간 반복매출(ARR) $190억. OpenAI $250억 ARR 달성, IPO 준비 착수.',
          'Google은 프론티어 유지보다 대중 배포 전략. AI 3강 경쟁 구도 심화.',
        ], why: '', notes: [] },
    ],
  },
  physical: {
    label: '피지컬 AI 뉴스',
    summary: 'Meta가 범용 휴머노이드 AI 개발을 위해 ARI를 인수하며 피지컬 AI 시장에 공식 진입했습니다. Boston Dynamics Atlas의 중량 가전 처리 능력이 재차 확인됐고, Unitree가 2025년 5,500대 출하로 미국 경쟁사 전체를 추월하며 가격 혁신을 이끌고 있습니다.',
    items: [
      { weight: 'high', time: '09:00', source: 'Boston Dynamics / Robotics & Automation News',
        headline: 'Boston Dynamics, Atlas 세탁기 처리 추가 공개 — AI 기반 전신 제어 정밀도 향상',
        url: 'https://roboticsandautomationnews.com/2026/05/20/boston-dynamics-trains-atlas-humanoid-robot-to-pick-up-and-place-washing-machine/101759/',
        bullets: [
          'Atlas, 50kg 세탁기 집어 정확한 위치에 안착. 강화학습·전신 협조 제어 기술 공개.',
          '테스트에서 100파운드(45kg) 이상 하중 성공적 처리. 현대·Google DeepMind 배치 일정 확정.',
          'Atlas 2026년 전량 생산분 현대차 RMAC·Google DeepMind 납품 확정. 상업 배포 가속.',
        ],
        why: '가전 설치·이동 자율 수행은 Atlas가 창고·공장에서 일반 가정까지 범위를 확장할 수 있는 핵심 역량 증명입니다.',
        notes: [
          { term: 'Atlas', def: 'Boston Dynamics의 전기구동 휴머노이드 로봇. 56자유도·50kg 적재 능력.' },
          { term: '전신 협조 제어', def: '팔·다리·몸통을 동시에 협조 제어해 무거운 물체를 안정적으로 처리하는 기술.' },
        ] },
      { weight: 'high', time: '08:00', source: 'Meta / PYMNTS',
        headline: 'Meta, ARI 인수 — 범용 휴머노이드 AI 모델 개발 추진',
        url: 'https://www.pymnts.com/meta/2026/meta-acquires-ari-to-fuel-humanoid-robot-push/',
        bullets: [
          'Meta, Assured Robot Intelligence(ARI) 스타트업 인수. 범용 휴머노이드 로봇용 AI 모델 개발 목적.',
          'Meta의 피지컬 AI 진출 신호탄. Llama 기반 로봇 AI 생태계 구축 구상.',
          'Alexandr Wang 주도로 로봇 분야 공격적 투자·인수 지속.',
        ],
        why: 'Meta가 피지컬 AI 시장에 진입하면 오픈소스 로봇 AI 생태계가 형성되며 산업 전체 비용이 낮아질 수 있습니다.',
        notes: [
          { term: 'ARI(Assured Robot Intelligence)', def: '범용 로봇 AI 모델 개발 스타트업. Meta에 인수됨.' },
          { term: '피지컬 AI', def: '로봇·드론 등 물리적 환경에서 동작하는 AI. 소프트웨어 AI 다음 성장 영역.' },
        ] },
      { weight: 'low', time: '07:00', source: 'KraneShares',
        headline: 'Unitree Robotics, 2025년 5,500대 출하 — 미국 경쟁사 합산 추월',
        url: 'https://kraneshares.com/humanoid-robotics-in-2026-the-race-from-pilot-to-platform/',
        bullets: [
          'Unitree, 2025년 5,500대 출하. Tesla·Figure AI·Agility Robotics 미국 3사 합산 추월.',
          '2026년 목표 20,000대. G1 모델 $15,400으로 글로벌 가격 기준 재설정.',
        ], why: '', notes: [] },
      { weight: 'low', time: '06:00', source: 'RobotToday',
        headline: 'Boston Dynamics IPO 검토 — $100억 밸류에이션 가능성',
        url: 'https://robottoday.com/article/boston-dynamics-ipo-and-100-b-valuation-how-it-compares-to-tesla-optimus-figure-ai-and-humanoid-rivals',
        bullets: [
          'Boston Dynamics, 현대차 산하 IPO 가능성 검토. 전문가 밸류에이션 최대 $100억 추정.',
          'Atlas 상업 배포 본격화·현대차 RMAC 수주 실적이 IPO 기반.',
        ], why: '', notes: [] },
      { weight: 'low', time: '10:00', source: 'NVIDIA / Cadence',
        headline: 'NVIDIA·Cadence, Isaac 로보틱스 + 멀티피직스 시뮬레이션 통합 확대',
        url: 'https://blogs.nvidia.com/blog/national-robotics-week-2026/',
        bullets: [
          'NVIDIA·Cadence, 고충실도 멀티피직스 시뮬레이션과 Isaac 로보틱스 통합 발표.',
          'sim-to-real 갭 해소 목표. 로봇 훈련 데이터 생성 효율 대폭 향상.',
        ], why: '', notes: [] },
      { weight: 'low', time: '08:30', source: 'Tesla / Built In',
        headline: 'Tesla Optimus Gen 3, 여름 프리몬트 생산 시작 목표 — AI5 통합',
        url: 'https://standardbots.com/blog/tesla-robot',
        bullets: [
          'Tesla, Optimus Gen 3 2026년 여름 프리몬트 공장 저량 생산 시작 목표. AI5 칩 통합 예정.',
          'Q1 2026 기준 R&D·학습 단계. 실제 공장 생산 작업 미달성.',
        ], why: '', notes: [] },
      { weight: 'low', time: '11:00', source: 'BCG',
        headline: 'BCG "피지컬 AI, 파일럿→플랫폼 전환 가속" — 2026년 핵심 키워드',
        url: 'https://www.bcg.com/publications/2026/how-physical-ai-is-reshaping-robotics-today',
        bullets: [
          'BCG 보고서: 2026년 피지컬 AI 시장이 파일럿 단계에서 플랫폼 단계로 공식 전환.',
          'Airbus·BMW·Schaeffler·Siemens 등 글로벌 제조사 파일럿 동시 진행 중.',
        ], why: '', notes: [] },
      { weight: 'low', time: '09:30', source: 'Automate 2026',
        headline: 'Automate 2026 — 이틀 휴머노이드 로봇 포럼, 피지컬 AI 총집결',
        url: 'https://www.automate.org/blogs/what-hurdles-remain-for-widespread-humanoid-adoption',
        bullets: [
          'Automate 2026 전시회, 이틀간 휴머노이드 로봇 포럼 개최. Boston Dynamics·Figure·1X 참가.',
          '피지컬 AI·생성 AI·디지털 트윈·시뮬레이션 분야 최신 트렌드 공유.',
        ], why: '', notes: [] },
    ],
  },
  quantum: {
    label: '양자 뉴스',
    summary: '미국 상무부가 IBM·D-Wave·Rigetti 등에 $20억 양자컴퓨팅 지원을 발표하며 양자 섹터 주가가 30% 이상 급등했습니다. NIST가 각 기업에 소수 지분을 취득하는 이례적 방식으로 미국의 양자 기술 주도권 확보 의지를 밝혔습니다.',
    items: [
      { weight: 'high', time: '10:00', source: 'CNN / CNBC',
        headline: '미국 $20억 양자컴퓨팅 투자 발표 — IBM $10억, D-Wave·Rigetti 각 $1억',
        url: 'https://www.cnbc.com/2026/05/21/quantum-stocks--us-taking-equity-stakes.html',
        bullets: [
          '미국 상무부, 양자컴퓨팅 기업들에 $20억 지원 발표. IBM $10억 + 자체 $10억으로 양자 웨이퍼 파운드리 Anderon 설립.',
          'D-Wave $1억, Rigetti $1억, Infleqtion 등 소형 기업도 수혜. NIST, 각 기업에 소수 비지배 지분 취득.',
          'D-Wave +33%, Rigetti +30%, Infleqtion +31% 급등. 양자컴퓨팅 섹터 최대 단일 일 상승.',
        ],
        why: '미국 정부의 $20억 직접 투자는 양자컴퓨팅을 반도체처럼 국가 전략 기술로 격상시켜 산업 성숙을 5-10년 앞당길 수 있습니다.',
        notes: [
          { term: 'NIST', def: '미국 국립표준기술연구소. 양자 내성 암호 표준화를 주도하며 기술 정책 영향력 큼.' },
          { term: 'Anderon', def: 'IBM이 정부 지원과 자체 투자로 설립하는 양자 웨이퍼 전용 파운드리.' },
        ] },
      { weight: 'high', time: '11:00', source: 'CNBC / Quantum Computing Report',
        headline: '양자 섹터 주가 폭등 — D-Wave +33%, Rigetti +30%, IonQ +22%',
        url: 'https://quantumcomputingreport.com/news/',
        bullets: [
          '미국 정부 $20억 발표 직후 양자 섹터 전체 급등. D-Wave +33%, Rigetti +30%, Infleqtion +31%, IonQ +22%.',
          'NIST 지분 취득 방식은 실질적 정부 보증 효과. 기관 투자자 유입 신호.',
          '양자컴퓨팅 ETF(QTUM) 13% 급등. 2026년 최대 섹터 단일 상승 기록.',
        ],
        why: '정부 투자가 기관 투자자의 신뢰를 높여 민간 후속 투자를 유발하고 양자 상업화 속도를 가속합니다.',
        notes: [
          { term: 'D-Wave', def: '세계 최초 상업 양자컴퓨터 기업. 어닐링 방식 특화. NYSE 상장.' },
          { term: 'Rigetti', def: '초전도 방식 양자컴퓨터 스타트업. NYSE 상장.' },
        ] },
      { weight: 'low', time: '07:00', source: 'Kipu Quantum',
        headline: 'Kipu Quantum, 오프라인 추론 하이브리드 양자ML 프레임워크 출시',
        url: 'https://quantumcomputingreport.com/news/',
        bullets: [
          'Kipu Quantum, QPU 실시간 의존성 제거하는 오프라인 양자ML 추론 프레임워크 발표.',
          '비용 절감·정확도 향상 동시 달성. 기업 애널리틱스 실용화 가속.',
        ], why: '', notes: [] },
      { weight: 'low', time: '06:00', source: 'Superpositions',
        headline: 'Superpositions, 클라우드 양자 솔루션 라이브러리 24개 사례 출시',
        url: 'https://quantumcomputingreport.com/news/',
        bullets: [
          'Superpositions, 개방형 양자 솔루션 라이브러리 론칭. 6개 산업 24개 레퍼런스 사례 포함.',
          '엔터프라이즈 양자 소프트웨어 진입 장벽 낮춰.',
        ], why: '', notes: [] },
      { weight: 'low', time: '09:00', source: 'Quantinuum / Synopsys',
        headline: 'Quantinuum·Synopsys, 양자컴퓨팅 엔지니어링 시뮬레이션 통합 협력',
        url: 'https://quantumcomputingreport.com/news/',
        bullets: [
          'Quantinuum·Synopsys, 양자컴퓨팅을 엔지니어링 시뮬레이션 워크플로에 통합.',
          'HPC 한계를 극복하는 하이브리드 양자-클래식 엔지니어링 솔루션 개발.',
        ], why: '', notes: [] },
      { weight: 'low', time: '08:00', source: 'ScienceDaily',
        headline: '신 양자 알고리즘, 준결정체 재료 시뮬레이션 성공 — 신약·배터리 응용',
        url: 'https://www.sciencedaily.com/releases/2026/05/260512202355.htm',
        bullets: [
          '새 양자 영감 알고리즘, 기존 슈퍼컴퓨터로 접근 불가 준결정체 양자 재료 시뮬레이션 성공.',
          '신약·배터리·촉매 소재 연구에 즉시 응용 가능.',
        ], why: '', notes: [] },
      { weight: 'low', time: '10:30', source: 'Harvard / The Quantum Insider',
        headline: '하버드 "양자 오류 수정, 예상보다 18개월 빠름" — 2028년 실용 우위 가능',
        url: 'https://thequantuminsider.com/2026/05/04/harvard-researchers-quantum-computing-advancing-faster-than-expected/',
        bullets: [
          '하버드 연구팀, 양자 오류 수정 속도 업계 예측 대비 18개월 앞서.',
          '현재 속도 유지 시 2028년 실용적 양자 우위 달성 가능성.',
        ], why: '', notes: [] },
      { weight: 'low', time: '09:30', source: 'IEEE Spectrum',
        headline: '중성 원자 양자컴퓨팅 2026 대약진 — 게이트 충실도 99.9%',
        url: 'https://spectrum.ieee.org/neutral-atom-quantum-computing',
        bullets: [
          '중성 원자 방식 양자컴퓨팅 게이트 충실도 99.9% 달성. QuEra·Pasqal 선두.',
          '이온트랩과 경쟁에서 규모 확장성 강점 부각.',
        ], why: '', notes: [] },
    ],
  },
  econ: {
    label: '경제 뉴스',
    summary: '한국의 5월 1~20일 수출이 전년 대비 64.8% 폭증해 역대 최대 기록을 세웠으며 반도체가 202% 급등을 이끌었습니다. 미국에서는 케빈 워시 연준 신임 의장이 취임해 금리 정책 불확실성이 고조되고, 30년 국채 금리가 2007년 이후 최고치를 기록했습니다.',
    items: [
      { weight: 'high', time: '09:00', source: '머니투데이 / 파이낸셜뉴스',
        headline: '한국 5월 1~20일 수출 64.8% 폭증 $526.5억 — 반도체 202% 역대 최대',
        url: 'https://www.mt.co.kr/economy/2026/05/21/2026052108393375556',
        bullets: [
          '관세청, 5월 1~20일 수출 $526.5억(+64.8% YoY). 5월 기준 역대 최대. 2022년 5월($386억) 이후 4년 만.',
          '반도체 수출 $219.5억(+202.1%). AI 서버·HBM 수요 폭발이 견인. 컴퓨터 주변기기 +305.5%.',
          '무역수지 흑자 $110억. 수입 $416억(+29.3%). 에너지 수입 증가에도 반도체 수출이 압도.',
        ],
        why: '반도체 202% 폭증은 AI 인프라 투자 사이클이 한국 수출에 직접 연결됐음을 보여주며 원화 가치와 코스피 상승 모멘텀으로 작용합니다.',
        notes: [
          { term: 'HBM(고대역폭메모리)', def: 'AI GPU에 탑재되는 초고속 메모리. SK하이닉스·삼성전자·Micron이 3강 구도.' },
        ] },
      { weight: 'high', time: '10:00', source: 'CNBC / 뉴데일리',
        headline: '케빈 워시 연준 신임 의장 취임 — 금리 인상 압박 강화 우려',
        url: 'https://www.newdaily.co.kr/site/data/html/2026/05/21/2026052100054.html',
        bullets: [
          '케빈 워시, 연준 제16대 의장 공식 취임. 6/16~17 첫 FOMC 주재. 금리 인상 성향 매파 평가.',
          '미국 4월 CPI 3.8%(3년 만 최고), 근원PCE 3.2% — 목표치 2% 크게 초과.',
          '금리선물 시장, 연내 25bp 인상 가능성 약 50% 반영. 장기 채권 시장 압박 지속.',
        ],
        why: '매파 성향의 워시 의장 취임은 금리 인상 가능성을 높여 채권·성장주에 단기 역풍으로 작용하고 달러 강세를 지지합니다.',
        notes: [
          { term: '매파(Hawk)', def: '물가 안정을 위해 금리 인상을 선호하는 통화정책 성향.' },
          { term: '근원PCE', def: '연준이 선호하는 물가 지표. 에너지·식품 제외 물가 변동 측정.' },
        ] },
      { weight: 'low', time: '08:00', source: 'CNBC / TradingEconomics',
        headline: '미국 30년 국채 금리 5.19% — 2007년 이후 최고치',
        url: 'https://www.cnbc.com/2026/05/19/treasurys-yields-inflation-bond-rout-oil.html',
        bullets: [
          '미국 30년 국채 5.197%. 2007년 7월 이후 약 19년 만의 최고 수준.',
          '글로벌 채권 매도세 지속. 워시 취임·인플레 우려·이란 불확실성 3중 압박.',
        ], why: '', notes: [] },
      { weight: 'low', time: '07:00', source: 'Reuters / OilPrice',
        headline: 'WTI $101 회복 — 이란 7차 협상 교착, 호르무즈 우려 재점화',
        url: 'https://oilprice.com/',
        bullets: [
          'WTI, 전일 급락(-6.55%) 이후 $101 수준으로 반등. 이란-미국 7차 핵 협상 교착.',
          '호르무즈 재봉쇄 시나리오 재부상. 에너지 인플레 하방 위험 잔존.',
        ], why: '', notes: [] },
      { weight: 'low', time: '06:00', source: '아주경제 / 파이낸셜뉴스',
        headline: '한국 무역수지 $110억 흑자 — AI·반도체 수출이 에너지 수입 압도',
        url: 'https://www.ajunews.com/view/20260521084937356',
        bullets: [
          '5월 1~20일 무역수지 $110억 흑자. 반도체·AI 장비 수출이 에너지 수입 비용 흡수.',
          '환율 안정화 요인. 원화 약세 압력에도 수출 펀더멘털 견조.',
        ], why: '', notes: [] },
      { weight: 'low', time: '09:00', source: 'CME FedWatch / CNBC',
        headline: '연준 금리 인상 확률 50% — 워시 취임·CPI 3.8% 영향',
        url: 'https://ko.tradingeconomics.com/united-states/interest-rate',
        bullets: [
          'CME FedWatch, 연내 25bp 인상 확률 50% 상향. 워시 취임·CPI 3.8% 동시 압박.',
          '6/17 FOMC 금리 경로 제시가 시장 최대 관심사로 부상.',
        ], why: '', notes: [] },
      { weight: 'low', time: '11:00', source: '블룸버그 / 한국은행',
        headline: 'USD/KRW 1,504원 — 워시 매파 취임·WTI 반등에 원화 약세',
        url: 'https://www.investing.com/currencies/usd-krw-historical-data',
        bullets: [
          '달러-원 1,504원. 워시 연준 의장 매파 기대·WTI 반등으로 원화 약세 압력.',
          '한국은행 구두 개입 경계 유지. 1,510원 돌파 시 직접 개입 가능성.',
        ], why: '', notes: [] },
      { weight: 'low', time: '10:30', source: '연방준비제도',
        headline: '미국 10Y 국채 4.60% — 워시 취임에도 WTI 반등 상쇄로 소폭 안정',
        url: 'https://www.federalreserve.gov/releases/h15/',
        bullets: [
          '미국 10년 국채 4.60%. 전일 4.67%에서 소폭 하락. WTI 반등 vs 워시 취임 상충 효과.',
          '단기 채권 시장 방향성 탐색 구간. 6/17 FOMC 전까지 변동성 지속.',
        ], why: '', notes: [] },
    ],
  },
  columns: {
    label: '컬럼 피드',
    summary: '오건영 단장은 채권 금리 우려가 계속 확대되는 상황에서 22년 10월·23년 10월·트럼프 트레이드·2025년 4월 셀아메리카 등 역사적 금리 급등 사례를 분석하며 현재 상황 해결의 실마리를 탐색했습니다.',
    items: [
      { name: '오건영', title: '신한은행 · 디지털 크리에이터', avatar: 'OG', color: '#D97757',
        time: '오늘 01:00', likes: 435, comments: 14,
        post: '오늘 새벽 소폭 안정세를 보이기는 했지만 여전히 채권 금리에 대한 우려가 계속해서 확대 일로에 있는 듯 합니다. 이렇게 금리가 높았던 시기가 언제 있었을까요.. 지난 러-우 전쟁과 연준의 자이언트 스텝 금리 인상, 그리고 영국 트러스 모멘텀이 극에 달했던 22년 10월이 있었죠. 그리고 예상했던 것보다 더 빠르게 금리를 인상하는데 대해 당혹스러운 모습을 보였던 2023년 10월도 그랬습니다. 그리고 트럼프 당선을 전후해서 트럼프 트레이드가 나타났고... 그러다 185개국에 관세를 부과한 이후 셀 아메리카가 터져나오면서 국채 금리가 재차 급등했던 기억이 있죠. 당시에는 어떻게 이런 상황들을 해결해나갔을까요..',
        summary: '채권 금리 역사적 고점 재연 — 22년 10월·23년 10월·트럼프 트레이드·셀아메리카 선례 분석. 해결 실마리 탐색.',
      },
    ],
  },
  invest: {
    title: '양자 $20억·반도체 폭등 수혜',
    subtitle: 'Claude가 작성한 오늘의 메모 · 5월 22일 09:00 · 5분 읽기',
    sections: [
      { h: '한 줄 요약', body: '미국 정부 $20억 양자컴퓨팅 투자로 D-Wave·Rigetti 30%+ 급등. 한국 5월 반도체 수출 202% 폭증으로 SK하이닉스·삼성전자 직접 수혜. 케빈 워시 연준 의장 취임으로 금리 인상 압박이 커지는 복합 환경입니다.' },
      { h: '오늘의 변수', body: '①미국 $20억 양자투자 → D-Wave·Rigetti·IonQ 추가 상승 모멘텀. ②한국 반도체 수출 202% → SK하이닉스·삼성전자 목표주가 상향 가능성. ③워시 연준 취임·CPI 3.8% → 6/17 FOMC 금리 인상 시나리오. ④WTI $101 반등 → 에너지 인플레 재점화 위험. ⑤삼성전자 파업 찬반투표 5/23~28 — 최종 변수.' },
      { h: '포지셔닝', body: '단기(1-3개월): 반도체 수출 폭증 수혜 SK하이닉스 집중. 양자컴퓨팅 정부 투자 → IonQ 관심. WTI 반등·워시 취임으로 금(GLD) 헤지 비중 복구. 채권(TLT) 최소화. 중기(6-12개월): 워시 첫 FOMC(6/17) 결과 확인 후 포지션 조정. 양자컴퓨팅 중장기 투자 구축 시작.' },
      { h: '리스크', body: '워시 6/17 FOMC 25bp 인상 선언 시 채권·성장주 동반 급락. 삼성 찬반투표 부결 → 파업 재개 → HBM4 공급 차질. WTI $105+ 재돌파 시 에너지 인플레 재점화. OpenAI YC 투자 → AI 스타트업 생태계 독점화 우려.' },
    ],
    watchlist: [
      { sym: '000660', name: 'SK하이닉스',  val: '1,995,000', pct: '+0.15%', up: true,  note: '반도체 수출 202% 폭증 직접 수혜 — HBM4 납품 확대' },
      { sym: '005930', name: '삼성전자',    val: '289,000',   pct: '+0.35%', up: true,  note: '파업 찬반투표 5/23~28 결과가 최종 변수' },
      { sym: 'IONQ',   name: 'IonQ',        val: '$36.80',    pct: '+22.1%', up: true,  note: '미국 정부 $20억 양자투자 수혜 — 볼더 R&D 연구소 가동' },
      { sym: 'NVDA',   name: 'NVIDIA',      val: '$246.20',   pct: '+0.29%', up: true,  note: 'AI 인프라 투자 지속 — 한국 HBM 수출 낙수 효과' },
      { sym: 'TLT',    name: 'iShares 20Y', val: '$86.50',    pct: '-0.80%', up: false, note: '워시 매파 취임·30년 국채 5.19% — 하락 압박 지속' },
      { sym: 'GLD',    name: 'SPDR Gold',   val: '$254.10',   pct: '+0.51%', up: true,  note: '워시 취임·WTI 반등·이란 불확실성 — 헤지 수요 복구' },
      { sym: 'VYM',    name: 'Vanguard HY', val: '$131.80',   pct: '-0.23%', up: false, note: '금리 인상 압박 — 배당주 소폭 하락 압력' },
      { sym: 'BTC',    name: 'Bitcoin',     val: '$77,630',   pct: '-0.07%', up: false, note: 'USD 강세·워시 취임 불확실성 — 횡보 구간' },
    ],
    portfolio: [
      { asset: '국내주식', pct: 20, color: '#3DDC97',
        tickers: [{ sym: '000660', name: 'SK하이닉스' }, { sym: '005930', name: '삼성전자' }],
        note: '반도체 수출 202% 폭증 — SK하이닉스 집중, 삼성 투표 주시' },
      { asset: '미국주식', pct: 20, color: '#5B9BD5',
        tickers: [{ sym: 'IONQ', name: 'IonQ' }, { sym: 'NVDA', name: 'NVIDIA' }],
        note: '양자 $20억 정부투자 IonQ + AI 인프라 NVDA' },
      { asset: '채권', pct: 8, color: '#9B8EC4',
        tickers: [{ sym: 'TLT', name: 'iShares 20Y ETF' }],
        note: '워시 취임 금리 인상 압박 — 최소화 유지' },
      { asset: '금', pct: 25, color: '#F5C518',
        tickers: [{ sym: 'GLD', name: 'SPDR Gold ETF' }],
        note: '워시·WTI 반등·이란·인플레 4중 헤지 — 비중 복구' },
      { asset: '배당주', pct: 18, color: '#E08A6E',
        tickers: [{ sym: 'VYM', name: 'Vanguard High Div.' }],
        note: '금리 인상 압박 환경 — 비중 유지' },
      { asset: '비트코인', pct: 9, color: '#F7931A',
        tickers: [{ sym: 'BTC', name: 'Bitcoin' }],
        note: '횡보 구간 — 소폭 비중 유지' },
    ],
  },
};


window.BRIEF_ARCHIVE = { '2026-05-22': TODAY, '2026-05-21': D_0521, '2026-05-20': D_0520 };
window.BRIEF_DATES   = ['2026-05-22', '2026-05-21', '2026-05-20'];
window.BRIEF_TODAY   = '2026-05-22';
window.BRIEF_USER    = '재현';
window.BRIEF_DATA    = TODAY;
